Repository fedspendingtransparency/usaspending-website, pull requests merged in 2019-11, with the labels that each got.

#1361 Dev-3094 Dates Section Labels Empty Strings for Unknown Award Type
  src/js/components/awardv2/shared/overview/AwardDates.jsx
Labels: warm-fix

#1376 Staging --> DEV
  src/js/components/awardv2/shared/overview/AwardDates.jsx
Labels: do not merge

#1383 Staging --> DEV
  src/_scss/pages/awardV2/awardFinancialAssistance.scss
  src/_scss/pages/awardV2/awardPage.scss
  src/_scss/pages/awardV2/shared/_expandableAwardSection.scss
  src/_scss/pages/awardV2/visualizations/description/_description.scss
  src/js/dataMapping/awardsv2/additionalDetailsContract.js
  src/js/dataMapping/awardsv2/additionalDetailsIdv.js
  src/js/models/v2/awardsV2/BaseIdv.js
Labels: down merge

#1384 WarmFix Update Spacing for PSC Title
  src/js/components/awardv2/shared/description/AwardDescription.jsx
Labels: warm-fix

#1385 [warm-fix-awardamounts-asst-tooltips] Fixing Award Amounts Section & Chart tool tips
  src/js/components/awardv2/shared/InfoTooltipContent.jsx
  src/js/components/awardv2/shared/awardAmountsSection/Tooltips.jsx
  src/js/dataMapping/awardsv2/tooltips.js
Labels: warm-fix
