Repository fedspendingtransparency/usaspending-website, pull requests merged in 2019-12, with the labels that each got.

#1412 [DEV-4013] Fixes Award Summary Tooltips in Internet Explorer
  src/_scss/components/tooltips/_index.scss
  src/js/components/awardv2/shared/awardAmountsSection/Tooltips.jsx
Labels: warm-fix

#1420 [DEV-1976] Adds spacing to items within the Award Overview Section, w/ IE polish
  src/_scss/pages/awardV2/visualizations/overview/overview.scss
  src/js/components/awardv2/financialAssistance/CFDAOverview.jsx
  src/js/components/awardv2/shared/overview/AwardDates.jsx
  src/js/components/awardv2/shared/overview/AwardingAgency.jsx
  src/js/components/awardv2/shared/overview/Recipient.jsx
  src/js/components/awardv2/shared/overview/RelatedAwards.jsx
Labels: warm-fix

#1427 Dev-1976 IDV Related Awards Links
  src/js/components/awardv2/shared/overview/AwardOverviewRightSection.jsx
Labels: warm-fix

#1426 Warm Fix Dev-1976 Recipient Location
  src/js/components/awardv2/shared/overview/Recipient.jsx
Labels: warm-fix

#1445 Warm-Fix Dev-4019 Dates Section Null Dates
  src/js/helpers/awardSummaryHelper.js
  tests/helpers/awardSummaryHelper-test.js
Labels: warm-fix

#1446 Staging -> Dev Handle Null Award Dates
  src/js/helpers/awardSummaryHelper.js
  tests/helpers/awardSummaryHelper-test.js
Labels: down merge

#1440 Ops-908 Remove Jquery by Removing USWDS
  package-lock.json
  package.json
Labels: hotfix

#1447 Master -> Staging Remove USWDS NPM Package
  package-lock.json
  package.json
Labels: down merge

#1448 Downmerge Staging -> Dev Remove USWDS NPM Package
  package-lock.json
  package.json
Labels: down merge

#1444 [DEV-3967] Updating activity chart piid link in tooltip
  src/js/components/award/idv/activity/ActivityChartTooltip.jsx
  src/js/models/v2/awardsV2/BaseIdvActivityBar.js
Labels: warm-fix

#1442 [data-transparency-ui] migrating to semver for data-transparency-ui dependency
  package-lock.json
  package.json
Labels: warm-fix

#1450 Warm Fix Dev-4019 Re-render component when dates or milestone change
  src/js/components/award/shared/overview/ProgressBar.jsx
Labels: warm-fix

#1449 Staging --> DEV
  package-lock.json
  package.json
  src/js/components/award/idv/activity/ActivityChartTooltip.jsx
  src/js/components/award/shared/overview/ProgressBar.jsx
  src/js/models/v2/awardsV2/BaseIdvActivityBar.js
Labels: down merge

#1441 [dev-3831] updating readme
  README.md
Labels: hotfix
