Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-05, with the labels that each got.

#1619 [DEV-4845] Building TAS Request Object for API and Loading Tree / Search Results from URL
  src/js/components/search/topFilterBar/filterGroups/ProgramSourceFilterGroup.jsx
  src/js/containers/search/SearchContainer.jsx
  src/js/containers/search/filters/naics/NAICSContainer.jsx
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
  src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
  src/js/dataMapping/search/awardsOperationKeys.js
  src/js/helpers/checkboxTreeHelper.js
  src/js/helpers/searchHelper.js
  src/js/helpers/sidebarHelper.js
  src/js/helpers/tasHelper.js
  src/js/models/search/SearchAwardsOperation.js
  src/js/redux/actions/search/searchFilterActions.js
  src/js/redux/reducers/search/searchFiltersReducer.js
  src/js/redux/reducers/search/tasReducer/tasReducer.js
  tests/containers/search/filters/programSource/TASCheckboxContainer-test.jsx
  tests/containers/search/filters/programSource/mockTas.js
  tests/containers/search/mockSearchHashes.js
  tests/helpers/checkboxTreeHelper-test.js
  tests/helpers/tasHelper-test.js
  tests/testResources/defaultReduxFilters.js
Labels: do not merge

#1646 [DEV-4526] Implements PSC Checkbox Tree w/o Submit Search
  src/_scss/pages/search/_filters.scss
  src/_scss/pages/search/filters/otherFilters/_pscCheckbox.scss
  src/js/components/search/SearchSidebar.jsx
  src/js/containers/search/filters/naics/NAICSContainer.jsx
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
  src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
  src/js/helpers/checkboxTreeHelper.js
  src/js/helpers/naicsHelper.js
  src/js/helpers/pscHelper.js
  src/js/helpers/searchHelper.js
  src/js/helpers/tasHelper.js
  src/js/redux/actions/search/pscActions.js
  src/js/redux/reducers/index.js
  src/js/redux/reducers/search/naicsReducer.js
  src/js/redux/reducers/search/pscReducer.js
  src/js/redux/reducers/search/tasReducer.js
  tests/containers/search/filters/psc/PSCCheckboxTreeContainer-test.jsx
  tests/containers/search/filters/psc/mockPSC.js
  tests/helpers/checkboxTreeHelper-test.js
  tests/helpers/pscHelper-test.js
  tests/redux/reducers/naics/naicsReducer-test.js
Labels: do not merge

#1663 [DEV-4527] Expand Collapse Overwrites Nodes from Search Results
  Dockerfile
  package-lock.json
  package.json
  src/js/helpers/checkboxTreeHelper.js
  src/js/redux/reducers/search/naicsReducer.js
  src/js/redux/reducers/search/pscReducer.js
  src/js/redux/reducers/search/tasReducer.js
  tests/helpers/checkboxTreeHelper-test.js
Labels: warm-fix

#1669 [DEV-5120] Updating the Active Filter Tag Title
  src/js/components/search/topFilterBar/filterGroups/ProgramSourceFilterGroup.jsx
Labels: warm-fix

#1670 Down Merge QAT -> Dev TAS Pill Bug
  src/js/components/search/topFilterBar/filterGroups/ProgramSourceFilterGroup.jsx
Labels: down merge

#1682 Warm-Fix Bug Dev-4556 Potential Award Amount Line Upper Bound
  src/js/components/sharedComponents/SVGLine.jsx
Labels: warm-fix

#1683 [DEV-4794&4530] Consistent Implementation to Load Tree from Hash across TAS/PSC/NAICS
  src/_scss/components/_checkboxTree.scss
  src/js/components/search/SearchSidebar.jsx
  src/js/components/search/topFilterBar/filterGroups/PSCFilterGroup.jsx
  src/js/containers/search/SearchContainer.jsx
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
  src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
  src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
  src/js/dataMapping/search/awardsOperationKeys.js
  src/js/helpers/checkboxTreeHelper.js
  src/js/helpers/pscHelper.js
  src/js/helpers/sidebarHelper.js
  src/js/helpers/tasHelper.js
  src/js/models/search/SearchAwardsOperation.js
  src/js/redux/actions/search/naicsActions.js
  src/js/redux/actions/search/searchFilterActions.js
  src/js/redux/reducers/search/naicsReducer.js
  src/js/redux/reducers/search/pscReducer.js
  src/js/redux/reducers/search/searchFiltersReducer.js
  tests/containers/search/SearchContainer-test.jsx
  tests/containers/search/filters/naics/NAICSCheckboxTree-test.jsx
  tests/containers/search/filters/naics/NAICSContainer-test.jsx
  tests/containers/search/filters/naics/NAICSSearchContainer-test.jsx
  tests/containers/search/filters/naics/mockNaics_v2.js
  tests/containers/search/filters/programSource/TASCheckboxContainer-test.jsx
  tests/containers/search/filters/programSource/mockTas.js
  tests/containers/search/filters/psc/PSCCheckboxTreeContainer-test.jsx
  tests/containers/search/filters/psc/mockPSC.js
  tests/containers/search/mockSearchHashes.js
  tests/helpers/checkboxTreeHelper-test.js
  tests/testResources/defaultReduxFilters.js
Labels: warm-fix

#1684 Demote warmfixes qat -> dev
  src/_scss/components/_checkboxTree.scss
  src/js/components/search/SearchSidebar.jsx
  src/js/components/search/filters/programSource/ProgramSourceSection.jsx
  src/js/components/search/filters/programSource/TreasuryAccountFilters.jsx
  src/js/components/search/topFilterBar/filterGroups/PSCFilterGroup.jsx
  src/js/components/sharedComponents/SVGLine.jsx
  src/js/containers/search/SearchContainer.jsx
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
  src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
  src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
  src/js/dataMapping/search/awardsOperationKeys.js
  src/js/helpers/checkboxTreeHelper.js
  src/js/helpers/pscHelper.js
  src/js/helpers/sidebarHelper.js
  src/js/helpers/tasHelper.js
  src/js/models/search/SearchAwardsOperation.js
  src/js/redux/actions/search/naicsActions.js
  src/js/redux/actions/search/searchFilterActions.js
  src/js/redux/reducers/search/naicsReducer.js
  src/js/redux/reducers/search/pscReducer.js
  src/js/redux/reducers/search/searchFiltersReducer.js
  tests/containers/search/SearchContainer-test.jsx
  tests/containers/search/filters/naics/NAICSCheckboxTree-test.jsx
  tests/containers/search/filters/naics/NAICSContainer-test.jsx
  tests/containers/search/filters/naics/NAICSSearchContainer-test.jsx
  tests/containers/search/filters/naics/mockNaics_v2.js
  tests/containers/search/filters/programSource/TASCheckboxContainer-test.jsx
  tests/containers/search/filters/programSource/mockTas.js
  tests/containers/search/filters/psc/PSCCheckboxTreeContainer-test.jsx
  tests/containers/search/filters/psc/mockPSC.js
  tests/containers/search/mockSearchHashes.js
  tests/helpers/checkboxTreeHelper-test.js
  tests/testResources/defaultReduxFilters.js
Labels: down merge

#1703 [DEV-4180] onHover, ensuring copy link doesn't wrap into two lines
  src/_scss/layouts/default/stickyHeader/_toolbar.scss
Labels: warm-fix

#1704 QAT -> Dev Picker CSS Change
  src/_scss/layouts/default/stickyHeader/_toolbar.scss
Labels: down merge

#1705 [DEV-4180] Share Icon: Hiding on Explorer Detail Page and Fixing Email Body Content
  src/js/components/accountLanding/AccountLandingPage.jsx
  src/js/components/agencyLanding/AgencyLandingPage.jsx
  src/js/components/explorer/ExplorerWrapperPage.jsx
  src/js/components/explorer/landing/ExplorerLanding.jsx
  src/js/components/recipientLanding/RecipientLandingPage.jsx
  src/js/components/stateLanding/StateLandingPage.jsx
Labels: warm-fix

#1698 Mod/dev 4176 add data dict color
  src/_scss/pages/bulkDownload/dictionary/_dictionaryTable.scss
  src/js/containers/bulkDownload/dictionary/DataDictionaryContainer.jsx
Labels: warm-fix
