Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-10, with the labels that each got.

#2128 [DEV-2698] Fixing some Tooltip Styling issues
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/components/tooltips/_index.scss
  src/_scss/components/visualizations/tooltip/_arrow.scss
  src/_scss/layouts/search/header/_downloadButton.scss
  src/_scss/layouts/tabbedSearch/header/_downloadTooltip.scss
  src/_scss/pages/award/shared/contractGrantsActivity.scss
  src/_scss/pages/covid19/visualizations/_amounts.scss
  src/js/components/covid19/AmountsVisualization.jsx
  src/js/components/covid19/Covid19Tooltips.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
Labels: warm-fix

#2139 Down Merge Warmfixes
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/components/tooltips/_index.scss
  src/_scss/components/visualizations/tooltip/_arrow.scss
  src/_scss/layouts/search/header/_downloadButton.scss
  src/_scss/layouts/tabbedSearch/header/_downloadTooltip.scss
  src/_scss/pages/award/shared/contractGrantsActivity.scss
  src/_scss/pages/covid19/visualizations/_amounts.scss
  src/js/components/covid19/AmountsVisualization.jsx
  src/js/components/covid19/Covid19Tooltips.jsx
  src/js/containers/AppContainer.jsx
  src/js/containers/award/idv/ReferencedAwardsContainer.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
  src/js/helpers/analytics/Analytics.js
  tests/containers/award/mockAward.js
Labels: do not merge, down merge

#2153 Dev-6199 IE IDV Activity Chart Bug
  src/js/components/award/idv/activity/chart/ActivityChart.jsx
Labels: hotfix

#2155 Down Merge QAT -> Dev #2153
  src/js/components/award/idv/activity/chart/ActivityChart.jsx
Labels: down merge

#2160 [DEV-6220] fix month determining bug
  src/js/containers/explorer/detail/helpers/explorerQuarters.js
  tests/containers/explorer/detail/helpers/explorerQuarters-test.js
Labels: hotfix

#2162 Downmerge #2160
  src/js/containers/explorer/detail/helpers/explorerQuarters.js
  tests/containers/explorer/detail/helpers/explorerQuarters-test.js
Labels: down merge

#2164 [DEV-2698] Award Amounts Viz Tooltips: showing tooltip going left -> right
  src/js/components/award/financialAssistance/RectanglePercentViz.jsx
  src/js/components/award/shared/awardAmountsSection/charts/SharedBarComponents.jsx
Labels: warm-fix

#2163 Qat -> Dev #2160
  jest.config.js
  src/js/components/award/financialAssistance/RectanglePercentViz.jsx
  src/js/components/award/shared/awardAmountsSection/charts/SharedBarComponents.jsx
  src/js/containers/explorer/detail/helpers/explorerQuarters.js
  src/js/containers/search/SearchContainer.jsx
  tests/components/covid19/homepage/TotalAmount-test.jsx
  tests/containers/explorer/detail/helpers/explorerQuarters-test.js
  tests/containers/search/SearchContainer-test.jsx
  tests/containers/search/filters/searchHelper.js
  tests/testResources/test-utils.js
Labels: down merge

#2172 [DEV-6202] Preventing Duplicate API Calls on Covid Profile PG Award Sections (CFDA, Recipient, Agency)
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/helpers/covid19Helper.js
Labels: warm-fix

#2177 Qat -> Dev #2172
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/helpers/covid19Helper.js
Labels: down merge

#2182 Sprint 118 Promotion to QAT
  jest.config.js
  package-lock.json
  package.json
  src/_scss/pages/covid19/_searchBar.scss
  src/_scss/pages/covid19/_tables.scss
  src/_scss/pages/covid19/assistanceListing/_assistanceListing.scss
  src/_scss/pages/covid19/index.scss
  src/js/components/accountLanding/table/cells/AccountLinkCell.jsx
  src/js/components/accountLanding/table/cells/HighlightedCell.jsx
  src/js/components/agencyLanding/table/cells/AgencyLinkCell.jsx
  src/js/components/award/shared/InfoTooltipContent.jsx
  src/js/components/covid19/AmountsVisualization.jsx
  src/js/components/covid19/SearchBar.jsx
  src/js/components/explorer/detail/sidebar/QuarterPicker.jsx
  src/js/components/search/table/ResultsTable.jsx
  src/js/components/sharedComponents/CheckboxTree.jsx
  src/js/components/stateLanding/table/StateLinkCell.jsx
  src/js/containers/Footer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/search/SearchSidebarSubmitContainer.jsx
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
  src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
  src/js/dataMapping/award/federalAccountFunding.js
  src/js/dataMapping/contracts/transactionTable.js
  src/js/dataMapping/recipients/fiscalYearDropdown.js
  src/js/dataMapping/search/awardTableColumns.jsx
  src/js/helpers/checkboxTreeHelper.js
  src/js/helpers/replaceString.jsx
  src/js/redux/reducers/search/naicsReducer.js
  src/js/redux/reducers/search/pscReducer.js
  src/js/redux/reducers/search/tasReducer.js
  tests/containers/search/SearchSidebarSubmitContainer-test.jsx
  tests/helpers/replaceString-test.js
Labels: ENV Promotion

#2183 Bug IDV Activity Chart Date Handling
  package-lock.json
  package.json
  src/js/components/award/idv/activity/IdvActivityVisualization.jsx
  src/js/containers/award/idv/IdvActivityContainer.jsx
  tests/containers/award/idv/IdvActivityContainer-test.jsx
Labels: hotfix

#2185 [DEV-6202] Fixes Obvious Bug in Conditional Logic
  package-lock.json
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
Labels: hotfix

#2192 Mrg/resolve conflix p3
  package-lock.json
  package.json
  src/js/components/award/idv/activity/IdvActivityVisualization.jsx
  src/js/containers/award/idv/IdvActivityContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  tests/containers/award/idv/IdvActivityContainer-test.jsx
Labels: down merge

#2193 Down Merge QAT to DEV
  package-lock.json
  package.json
  src/js/components/award/idv/activity/IdvActivityVisualization.jsx
  src/js/containers/award/idv/IdvActivityContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  tests/containers/award/idv/IdvActivityContainer-test.jsx
Labels: down merge
