Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-11, with the labels that each got.

#2202 Sprint 118 Promotion to Production
  jest.config.js
  src/_scss/pages/covid19/_searchBar.scss
  src/_scss/pages/covid19/_tables.scss
  src/_scss/pages/covid19/assistanceListing/_assistanceListing.scss
  src/_scss/pages/covid19/index.scss
  src/js/components/accountLanding/table/cells/AccountLinkCell.jsx
  src/js/components/accountLanding/table/cells/HighlightedCell.jsx
  src/js/components/agencyLanding/table/cells/AgencyLinkCell.jsx
  src/js/components/award/shared/InfoTooltipContent.jsx
  src/js/components/covid19/AmountsVisualization.jsx
  src/js/components/covid19/SearchBar.jsx
  src/js/components/explorer/detail/sidebar/QuarterPicker.jsx
  src/js/components/search/table/ResultsTable.jsx
  src/js/components/sharedComponents/CheckboxTree.jsx
  src/js/components/stateLanding/table/StateLinkCell.jsx
  src/js/containers/Footer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/search/SearchSidebarSubmitContainer.jsx
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
  src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
  src/js/dataMapping/award/federalAccountFunding.js
  src/js/dataMapping/contracts/transactionTable.js
  src/js/dataMapping/recipients/fiscalYearDropdown.js
  src/js/dataMapping/search/awardTableColumns.jsx
  src/js/helpers/checkboxTreeHelper.js
  src/js/helpers/replaceString.jsx
  src/js/redux/reducers/search/naicsReducer.js
  src/js/redux/reducers/search/pscReducer.js
  src/js/redux/reducers/search/tasReducer.js
  tests/containers/search/SearchSidebarSubmitContainer-test.jsx
  tests/helpers/replaceString-test.js
Labels: ENV Promotion

#2207 [BRUS2DTI-419] Add new ENV to specify DTI
  src/js/GlobalConstants.js
  src/js/components/about/DataQuality.jsx
  src/js/components/bulkDownload/accounts/AccountDataContent.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
  src/js/models/v2/state/BaseStateProfile.js
  tests/models/state/BaseStateProfile-test.js
Labels: warm-fix

#2208 Downmerge QAT -> DEV
  src/js/GlobalConstants.js
  src/js/components/about/DataQuality.jsx
  src/js/components/bulkDownload/accounts/AccountDataContent.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
  src/js/models/v2/state/BaseStateProfile.js
  tests/models/state/BaseStateProfile-test.js
Labels: down merge

#2204 Advanced Search Bug Fixes & Spending Explorer 2020 Period Selection fix
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/LinkToAdvancedSearchContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/homepage/CovidFeatureContainer.jsx
  src/js/containers/search/SearchContainer.jsx
Labels: hotfix

#2209 Master -> QAT
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/LinkToAdvancedSearchContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/homepage/CovidFeatureContainer.jsx
  src/js/containers/search/SearchContainer.jsx
Labels: down merge

#2210 QAT --> DEV Down Merge Hotfixes to Advanced Search
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/LinkToAdvancedSearchContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/homepage/CovidFeatureContainer.jsx
  src/js/containers/search/SearchContainer.jsx
Labels: down merge

#2212 Fix about page
  src/js/components/about/DataSources.jsx
  src/js/dataMapping/award/additionalDetailsContract.js
  src/js/dataMapping/award/additionalDetailsIdv.js
Labels: do not merge

#2213 Qat to Dev
  src/js/components/about/DataSources.jsx
  src/js/dataMapping/award/additionalDetailsContract.js
  src/js/dataMapping/award/additionalDetailsIdv.js
Labels: down merge

#2218 Hotfix Budget Category table Federal Account links
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
Labels: hotfix

#2219 Master -> QAT #2218
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
Labels: down merge

#2220 Demote hotfix qat -> dev
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
Labels: down merge

#2222 Warmfix DEV-6441 homepage links to files.usaspending.gov
  src/js/components/homepage/download/DownloadDetail.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: warm-fix

#2224 Qat -> Dev #2222
  src/js/components/homepage/download/DownloadDetail.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge

#2231 DEV-6420 & DEV-6414 COVID Budget Category table resiliency
  src/_scss/layouts/default/header/_warning.scss
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
Labels: warm-fix

#2232 Qat -> Dev
  src/_scss/layouts/default/header/_warning.scss
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
Labels: down merge

#2235 [DEV-6380] Adds markup to Column Title
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
Labels: warm-fix

#2238 Demote warmfix qat -> dev
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
Labels: down merge

#2243 DEV-6475 Warmfix Recipient Unlinked Data row
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
Labels: warm-fix

#2244 Dev-6379 Bumps DTUI to use 1.3.2
  package-lock.json
  package.json
Labels: warm-fix

#2247 Demote warmfixes qat -> dev w/ resolved merge conflicts
  package-lock.json
  package.json
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
Labels: down merge

#2249 Sprint 120 Prod Deploy
  .gitignore
  Dockerfile
  package-lock.json
  package.json
  scripts/sitemaps/Dockerfile
  scripts/sitemaps/buildSitemap.js
  scripts/sitemaps/package-lock.json
  scripts/sitemaps/package.json
  scripts/sitemaps/pages.js
  src/_scss/layouts/default/header/_warning.scss
  src/_scss/pages/aboutTheData/agenciesDetailPage.scss
  src/_scss/pages/aboutTheData/agenciesPage.scss
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/recipient/RecipientPage.jsx
  src/js/components/sharedComponents/metaTags/MetaTags.jsx
  src/js/components/sharedComponents/stickyHeader/StickyHeader.jsx
  src/js/containers/AppContainer.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgenciesDetailContainer.jsx
  src/js/containers/agency/AgencyContainer.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/recipient/RecipientContainer.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/containers/state/StateContainer.jsx
  src/js/helpers/analytics/Analytics.js
  src/js/redux/reducers/recipient/recipientReducer.js
  tests/scripts/buildSitemap-test.js
Labels: ENV Promotion
