Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-01, with the labels that each got.

#1452 [DEV-3836] Bug in IE when using TAS section of Advanced Search
  src/js/components/search/filters/programSource/ProgramSourceSection.jsx
  src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
Labels: ie-bug

#1460 Bug Rectangle Pattern Component No Data
  src/js/components/sharedComponents/patterns/RectanglePattern.jsx
Labels: warm-fix

#1463 Staging --> Dev down merge
  src/js/components/sharedComponents/patterns/RectanglePattern.jsx
Labels: down merge

#1470 [DEV-4036] adding robots.txt back to webpack copy plugin
  webpack/webpack.common.js
Labels: warm-fix

#1471 Downmerge for Webpack copy plugin warm fix
  webpack/webpack.common.js
Labels: down merge

#1472 Warm Fix Dev-1976 provide state for foreign contracts
  src/js/dataMapping/awards/awardOverview.js
  src/js/models/v2/CoreLocation.js
  tests/models/CoreLocation-test.js
Labels: warm-fix

#1481 [DEV-4100] removes unnecessary conditional from subaward scroll fn
  src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
  tests/containers/state/StateContainer-test.jsx
  tests/containers/state/mockData.js
Labels: warm-fix

#1484 [DEV-4100] Adding Conditional Back & Resetting Redux Award Namespace on unMount
  src/js/components/award/contract/ContractContent.jsx
  src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
  src/js/containers/award/AwardContainer.jsx
  tests/containers/award/AwardContainer-test.jsx
Labels: warm-fix

#1485 Staging --> DEV, w/ conflicts Resolved
  src/js/components/award/contract/ContractContent.jsx
  src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
  src/js/containers/award/AwardContainer.jsx
  tests/containers/award/AwardContainer-test.jsx
  tests/containers/state/StateContainer-test.jsx
Labels: down merge

#1491 [DEV-4062] Fixes formatting on Featured Content in IE & Allows for Click
  src/_scss/pages/homepage/features/_featurePane.scss
  src/js/components/homepage/features/PaneFeature.jsx
Labels: hotfix
