Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-07, with the labels that each got.

#1774 DEV-5288 award spending agencies table
  src/_scss/components/_moreOptionsTabs.scss
  src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/sharedComponents/moreOptionsTabs/MoreOptionsTabs.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/dataMapping/covid19/awardSpendingAgency/awardSpendingAgencyTableTabs.js
  src/js/helpers/disasterHelper.js
  src/js/helpers/moreOptionsTabs/moreOptionsTabsHelper.js
  src/js/models/covid19/awardSpendingAgency/BaseAwardSpendingByAgencyRow.js
  tests/helpers/moreOptionsTabs/moreOptionsTabsHelper-test.js
  tests/models/covid19/awardSpendingAgency/BaseAwardSpendingByAgencyRow-test.js
Labels: pending-api

#1778 DEV-5458 COVID profile CFDA section award type tabs
  src/_scss/pages/covid19/assistanceListing/_assistanceListing.scss
  src/_scss/pages/covid19/spendingOverTime/_awardSpendingOverTime.scss
  src/_scss/pages/search/results/table/_tableTypes.scss
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/assistanceListing/SummaryInsightsContainer.jsx
  src/js/dataMapping/covid19/covid19.js
Labels: pending-api

#1785 [DEV-5136] fixing expected idv_agg response object shape
  src/js/components/award/idv/amounts/AwardAmounts.jsx
  src/js/dataMapping/award/awardAmountsSection.js
  src/js/models/v2/award/BaseAwardAmounts.js
  tests/models/award/BaseAwardAmounts-test.js
  tests/models/award/mockAwardApi.js
Labels: warm-fix

#1787 DEV-5509 CFDA table loans tab
  src/_scss/pages/covid19/assistanceListing/_assistanceListing.scss
  src/_scss/pages/covid19/index.scss
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/dataMapping/covid19/covid19.js
  src/js/helpers/disasterHelper.js
  src/js/models/v2/covid19/BaseSpendingByCfdaRow.js
  tests/containers/covid19/SpendingByCFDAContainer-test.jsx
  tests/models/covid19/BaseSpendingByCfdaRow-test.js
  tests/models/covid19/mockData.js
Labels: pending-api

#1784 DEV-5518 update spending by agency loan column
  src/_scss/components/_moreOptionsTabs.scss
  src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
  src/js/components/sharedComponents/moreOptionsTabs/MoreOptionsTabs.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/dataMapping/covid19/awardSpendingAgency/awardSpendingAgencyTableTabs.js
  src/js/helpers/disasterHelper.js
  src/js/helpers/moreOptionsTabs/moreOptionsTabsHelper.js
Labels: pending-api

#1794 [DEV-5572] cfdaPropgram --> cfdaProgram
  src/js/components/award/shared/overview/AwardOverviewRightSection.jsx
Labels: warm-fix

#1795 Demote warmfix qat --> dev
  src/js/components/award/shared/overview/AwardOverviewRightSection.jsx
Labels: down merge

#1772 Ftr/dev 5402/fiscal data announcement
  src/_scss/pages/homepage/features/_featurePane.scss
  src/img/homepage-fiscal-data.png
  src/js/components/homepage/features/PaneFeature.jsx
Labels: warm-fix

#1779 [DEV-5197] Implement new Quarter Picker with Periods on Account Download Page (Pt 1)
  package-lock.json
  package.json
  src/_scss/pages/bulkDownload/form/downloadForm.scss
  src/js/components/bulkDownload/accounts/AccountDataContent.jsx
  src/js/components/bulkDownload/accounts/UserSelections.jsx
  src/js/components/bulkDownload/accounts/filters/FiscalYearFilter.jsx
  src/js/components/sharedComponents/QuarterPickerWithFY.jsx
  src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
  src/js/containers/explorer/detail/helpers/explorerQuarters.js
  src/js/helpers/downloadHelper.js
  src/js/redux/reducers/bulkDownload/bulkDownloadReducer.js
  tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
  tests/containers/bulkDownload/mockData.js
  tests/containers/explorer/detail/helpers/explorerQuarters-test.js
  tests/helpers/downloadHelper-test.js
Labels: do not merge, pending-api

#1799 Demote warmfix qat -> dev
  src/_scss/pages/homepage/features/_featurePane.scss
  src/img/homepage-fiscal-data.png
  src/js/components/homepage/features/PaneFeature.jsx
Labels: down merge

#1806 DEV-5402 Warmfix Fiscal Data site url
  src/js/components/homepage/features/PaneFeature.jsx
Labels: warm-fix

#1807 Warm Fix Down Merge: Fixed fiscal data site url (#1806)
  src/js/components/homepage/features/PaneFeature.jsx
Labels: down merge

#1819 Warmfix/dev 5403/fix broken feature pane link
  src/js/components/homepage/features/PaneFeature.jsx
Labels: warm-fix

#1822 DEV-5347 warmfix tab counts
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
Labels: warm-fix

#1820 Down Merge: QAT Release, DL Link HREF, TAS Components Hotfix, Standardize Colors
  src/_scss/core/_variables.scss
  src/_scss/pages/award/awardPage.scss
  src/_scss/pages/award/shared/awardAmountsSection/_charts.scss
  src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/search/filters/otherFilters/_defCheckbox.scss
  src/js/GlobalConstants.js
  src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/homepage/features/PaneFeature.jsx
  src/js/dataMapping/award/awardAmountsSection.js
  src/js/dataMapping/covid19/covid19.js
  src/js/models/search/SearchAwardsOperation.js
  tests/models/search/SearchAwardsOperation-test.js
Labels: down merge

#1827 Off-cycle QAT deploy
  src/js/components/covid19/OverviewData.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/homepage/features/PaneFeature.jsx
  src/js/components/sharedComponents/stickyHeader/ShareIcon.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/dataMapping/covid19/covid19.js
  src/js/dataMapping/search/awardTableColumnTypes.js
  src/js/helpers/socialShare.jsx
  tests/helpers/socialShare-test.js
Labels: Testing Must Merge

#1857 QAT Off Cycle Release
  src/_scss/components/_baseModal.scss
  src/_scss/components/_moreOptionsTabs.scss
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/layouts/default/header/_warning.scss
  src/_scss/pages/award/shared/awardAmountsSection/_charts.scss
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/_scss/pages/homepage/hero/_covid-hero.scss
  src/_scss/pages/homepage/homePage.scss
  src/_scss/pages/modals/all.scss
  src/_scss/pages/modals/covid19/_covid19.scss
  src/_scss/pages/modals/redirect/_redirect.scss
  src/_scss/pages/modals/stayInTouch/_stayInTouch.scss
  src/_scss/pages/search/results/table/_tableTypes.scss
  src/js/components/award/financialAssistance/RectanglePercentViz.jsx
  src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
  src/js/components/award/shared/awardAmountsSection/charts/SharedBarComponents.jsx
  src/js/components/bulkDownload/accounts/AccountDataContent.jsx
  src/js/components/bulkDownload/awards/SubmitButton.jsx
  src/js/components/covid19/AmountsVisualization.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/covid19/recipient/map/MapFilters.jsx
  src/js/components/homepage/Homepage.jsx
  src/js/components/homepage/hero/CovidTooltip.jsx
  src/js/components/homepage/hero/TotalAmount.jsx
  src/js/components/search/table/ResultsTableTabItem.jsx
  src/js/components/sharedComponents/RedirectModal.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/components/sharedComponents/moreOptionsTabs/MoreOptionsTabs.jsx
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/SummaryInsightsContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/covid19/recipient/SummaryInsightsContainer.jsx
  src/js/dataMapping/award/awardAmountsSection.js
  src/js/dataMapping/covid19/budgetCategories/BudgetCategoriesTableColumns.js
  src/js/dataMapping/covid19/covid19.js
  src/js/dataMapping/covid19/recipient/map/map.js
  src/js/helpers/apiRequest.js
  src/js/helpers/covid19Helper.js
  src/js/helpers/disasterHelper.js
  src/js/helpers/scrollToHelper.js
  src/js/models/v2/covid19/BaseBudgetCategoryRow.js
  src/js/redux/reducers/covid19/covid19Reducer.js
  tests/containers/covid19/homepage/CovidHighlights-test.jsx
  tests/models/covid19/BaseBudgetCategoryRow-test.js
Labels: ENV Promotion

#1860 dev -> staging deploy
  src/_scss/components/_baseModal.scss
  src/_scss/components/_moreOptionsTabs.scss
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/layouts/default/header/_warning.scss
  src/_scss/pages/award/shared/awardAmountsSection/_charts.scss
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/_scss/pages/homepage/hero/_covid-hero.scss
  src/_scss/pages/homepage/homePage.scss
  src/_scss/pages/modals/all.scss
  src/_scss/pages/modals/covid19/_covid19.scss
  src/_scss/pages/modals/redirect/_redirect.scss
  src/_scss/pages/modals/stayInTouch/_stayInTouch.scss
  src/_scss/pages/search/results/table/_tableTypes.scss
  src/js/components/award/financialAssistance/RectanglePercentViz.jsx
  src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
  src/js/components/award/shared/awardAmountsSection/charts/SharedBarComponents.jsx
  src/js/components/bulkDownload/accounts/AccountDataContent.jsx
  src/js/components/bulkDownload/awards/SubmitButton.jsx
  src/js/components/covid19/AmountsVisualization.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/covid19/recipient/map/MapFilters.jsx
  src/js/components/homepage/Homepage.jsx
  src/js/components/homepage/hero/CovidTooltip.jsx
  src/js/components/homepage/hero/TotalAmount.jsx
  src/js/components/search/table/ResultsTableTabItem.jsx
  src/js/components/sharedComponents/RedirectModal.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/components/sharedComponents/moreOptionsTabs/MoreOptionsTabs.jsx
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/SummaryInsightsContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/covid19/recipient/SummaryInsightsContainer.jsx
  src/js/dataMapping/award/awardAmountsSection.js
  src/js/dataMapping/covid19/budgetCategories/BudgetCategoriesTableColumns.js
  src/js/dataMapping/covid19/covid19.js
  src/js/dataMapping/covid19/recipient/map/map.js
  src/js/helpers/apiRequest.js
  src/js/helpers/covid19Helper.js
  src/js/helpers/disasterHelper.js
  src/js/helpers/scrollToHelper.js
  src/js/models/v2/covid19/BaseBudgetCategoryRow.js
  src/js/redux/reducers/covid19/covid19Reducer.js
  tests/containers/covid19/homepage/CovidHighlights-test.jsx
  tests/models/covid19/BaseBudgetCategoryRow-test.js
Labels: ENV Promotion

#1867 Off Cycle Release to QAT
  src/_scss/pages/covid19/_sidebar.scss
  src/_scss/pages/covid19/_sidebarFooter.scss
  src/_scss/pages/covid19/_tableMessages.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/search/_tooltips.scss
  src/js/components/covid19/SidebarFooter.jsx
  src/js/components/search/SearchSidebar.jsx
  src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
  src/js/components/sharedComponents/sidebar/Sidebar.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/helpers/covid19.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/dataMapping/covid19/budgetCategories/BudgetCategoriesTableColumns.js
  src/js/dataMapping/covid19/covid19.js
  src/js/helpers/covid19Helper.js
  src/js/models/v2/award/BaseFederalAccountFunding.js
  src/js/models/v2/covid19/CoreSpendingTableRow.js
  tests/containers/covid19/SpendingByRecipientContainer-test.jsx
  tests/models/award/BaseFederalAccountFunding-test.js
  tests/models/covid19/BaseBudgetCategoryRow-test.js
  tests/models/covid19/BaseSpendingByCfdaRow-test.js
  tests/models/covid19/BaseSpendingByRecipientRow-test.js
  tests/models/covid19/CoreSpendingTableRow-test.js
  tests/models/covid19/mockData.js
Labels: ENV Promotion

#1868 DEV --> Staging
  src/_scss/pages/covid19/_sidebar.scss
  src/_scss/pages/covid19/_sidebarFooter.scss
  src/_scss/pages/covid19/_tableMessages.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/search/_tooltips.scss
  src/js/components/covid19/SidebarFooter.jsx
  src/js/components/search/SearchSidebar.jsx
  src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
  src/js/components/sharedComponents/sidebar/Sidebar.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/helpers/covid19.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/dataMapping/covid19/budgetCategories/BudgetCategoriesTableColumns.js
  src/js/dataMapping/covid19/covid19.js
  src/js/helpers/covid19Helper.js
  src/js/models/v2/award/BaseFederalAccountFunding.js
  src/js/models/v2/covid19/CoreSpendingTableRow.js
  tests/containers/covid19/SpendingByRecipientContainer-test.jsx
  tests/models/award/BaseFederalAccountFunding-test.js
  tests/models/covid19/BaseBudgetCategoryRow-test.js
  tests/models/covid19/BaseSpendingByCfdaRow-test.js
  tests/models/covid19/BaseSpendingByRecipientRow-test.js
  tests/models/covid19/CoreSpendingTableRow-test.js
  tests/models/covid19/mockData.js
Labels: ENV Promotion

#1886 Off-cycle QAT deploy
  src/_scss/pages/covid19/_tableMessages.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/covid19/recipient/_spendingByRecipient.scss
  src/_scss/pages/search/filters/otherFilters/_defCheckbox.scss
  src/js/GlobalConstants.js
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/covid19/recipient/SpendingByRecipient.jsx
  src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
  src/js/components/sharedComponents/CheckboxTree.jsx
  src/js/components/sharedComponents/CheckboxTreeLabel.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/helpers/scrollHelper.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/search/filters/def/DEFCheckboxTree.jsx
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/dataMapping/covid19/recipient/recipient.js
  tests/containers/search/filters/DEFCheckboxxTree-test.jsx
Labels: ENV Promotion

#1887 Off-cycle Staging deploy
  src/_scss/pages/covid19/_tableMessages.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/covid19/recipient/_spendingByRecipient.scss
  src/_scss/pages/homepage/features/_covidFeature.scss
  src/_scss/pages/homepage/features/features.scss
  src/_scss/pages/homepage/hero/_covid-hero.scss
  src/_scss/pages/search/filters/otherFilters/_defCheckbox.scss
  src/img/header--people-buildings-transparent@1x.png
  src/img/header--people-buildings-transparent@2x.png
  src/img/header--people-buildings-transparent@3x.png
  src/img/header-img-people-1000x400@2x.png
  src/img/header-img-people-1280x400@2x.png
  src/img/header-img-people-384x486@2x.png
  src/img/header-img-people-512x687@2x.png
  src/img/header-img-people-720x619@2x.png
  src/img/homepage-covid-official-spending-data.png
  src/img/homepage-covid-ss-adv-search.png
  src/img/homepage-covid-ss-award-summary.png
  src/img/homepage-covid-ss-profile.png
  src/js/GlobalConstants.js
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/covid19/recipient/SpendingByRecipient.jsx
  src/js/components/homepage/features/Features.jsx
  src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
  src/js/components/sharedComponents/CheckboxTree.jsx
  src/js/components/sharedComponents/CheckboxTreeLabel.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/helpers/scrollHelper.jsx
  src/js/containers/covid19/homepage/CovidFeatureContainer.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/search/filters/def/DEFCheckboxTree.jsx
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/dataMapping/covid19/recipient/recipient.js
  tests/containers/search/filters/DEFCheckboxxTree-test.jsx
Labels: ENV Promotion

#1920 QAT DEV-5602 clear search min chars
  src/js/components/covid19/SearchBar.jsx
Labels: warm-fix

#1884 QAT Fix/dev 5707 new flag profiles section
  src/_scss/components/_newBadge.scss
  src/_scss/layouts/default/header/nav/_dropdownMenu.scss
  src/_scss/layouts/default/header/nav/mobile/_dropdown.scss
  src/js/components/sharedComponents/header/Dropdown.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdown.jsx
Labels: warm-fix
