Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-02, with the labels that each got.

#1492 Master -> Staging
  src/_scss/pages/homepage/features/_featurePane.scss
  src/js/components/homepage/features/PaneFeature.jsx
Labels: down merge

#1494 Staging --> DEV
  src/_scss/pages/homepage/features/_featurePane.scss
  src/js/components/homepage/features/PaneFeature.jsx
Labels: down merge

#1495 [DEV-4036] Fixes XML Syntax for indexed sitemap
  scripts/buildSitemap.js
Labels: hotfix

#1496 [DEV-4036] Changing change frequency value to monthly from invalid value of quarterly
  scripts/pages.js
Labels: hotfix

#1498 Down Merge Sitemap Hotfixes
  scripts/buildSitemap.js
  scripts/pages.js
Labels: down merge

#1497 [DEV-3942 && DEV-3194] Refactors componentDidUpdate to handle update to fy url param and updates links
  src/js/components/recipient/modal/table/RecipientModalTable.jsx
  src/js/containers/recipient/RecipientContainer.jsx
  src/js/containers/state/StateContainer.jsx
  src/js/dataMapping/awards/additionalDetailsContract.js
  src/js/dataMapping/awards/additionalDetailsFinancialAssistance.js
  src/js/dataMapping/awards/additionalDetailsIdv.js
  tests/containers/recipient/RecipientContainer-test.jsx
  tests/containers/state/StateContainer-test.jsx
Labels: warm-fix

#1499 Down-merge State/Recipient warmfixes and sitemap hotfixes
  scripts/buildSitemap.js
  scripts/pages.js
  src/js/components/recipient/modal/table/RecipientModalTable.jsx
  src/js/containers/recipient/RecipientContainer.jsx
  src/js/containers/state/StateContainer.jsx
  src/js/dataMapping/awards/additionalDetailsContract.js
  src/js/dataMapping/awards/additionalDetailsFinancialAssistance.js
  src/js/dataMapping/awards/additionalDetailsIdv.js
  tests/containers/recipient/RecipientContainer-test.jsx
  tests/containers/state/StateContainer-test.jsx
Labels: down merge

#1506 [DEV-3994] EncodeURI --> encodeURIComponent
  scripts/buildSitemap.js
  src/js/containers/explorer/detail/DetailContentContainer.jsx
  src/js/containers/keyword/table/ResultsTableContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/models/v2/awardsV2/BaseAwardAmounts.js
  src/js/models/v2/awardsV2/BaseFederalAccountFunding.js
  src/js/models/v2/awardsV2/BaseIdvActivityBar.js
  src/js/models/v2/awardsV2/BaseParentAwardDetails.js
  src/js/models/v2/awardsV2/BaseReferencedAwardResult.js
  src/js/models/v2/awardsV2/CoreAward.js
Labels: hotfix

#1508 Staging --> DEV
  scripts/buildSitemap.js
  src/js/containers/explorer/detail/DetailContentContainer.jsx
  src/js/containers/keyword/table/ResultsTableContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/models/v2/awardsV2/BaseAwardAmounts.js
  src/js/models/v2/awardsV2/BaseFederalAccountFunding.js
  src/js/models/v2/awardsV2/BaseIdvActivityBar.js
  src/js/models/v2/awardsV2/BaseParentAwardDetails.js
  src/js/models/v2/awardsV2/BaseReferencedAwardResult.js
  src/js/models/v2/awardsV2/CoreAward.js
Labels: down merge

#1515 [DEV-4373] Lowering value of z-index for sankey
  src/_scss/pages/agency/v2/index.scss
  src/_scss/pages/bulkDownload/form/_fyPicker.scss
Labels: warm-fix

#1514 [DEV-4504] decoding award IDs on POST request Objects, adding tests for every case
  src/js/containers/keyword/table/ResultsTableContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/helpers/apiRequest.js
  tests/containers/explorer/detail/DetailContentContainer-test.jsx
  tests/containers/explorer/detail/mockData.js
  tests/containers/keyword/mockResults.js
  tests/containers/keyword/table/ResultsTableContainer-test.jsx
  tests/containers/search/table/ResultsTableContainer-test.jsx
  tests/containers/search/table/mockAwards.js
  tests/helpers/apiRequest-test.js
  tests/mockData.js
  tests/models/awardsV2/BaseAwardAmounts-test.js
  tests/models/awardsV2/BaseFederalAccountFunding-test.js
  tests/models/awardsV2/BaseParentAwardDetails-test.js
  tests/models/awardsV2/BaseReferencedAwardResult-test.js
  tests/models/awardsV2/CoreAward-test.js
Labels: hotfix

#1520 Downmerge hotfix of URL Encoded Post Request Object Properties
  src/js/containers/keyword/table/ResultsTableContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/helpers/apiRequest.js
  tests/containers/explorer/detail/DetailContentContainer-test.jsx
  tests/containers/explorer/detail/mockData.js
  tests/containers/keyword/mockResults.js
  tests/containers/keyword/table/ResultsTableContainer-test.jsx
  tests/containers/search/table/ResultsTableContainer-test.jsx
  tests/containers/search/table/mockAwards.js
  tests/helpers/apiRequest-test.js
  tests/mockData.js
  tests/models/awardsV2/BaseAwardAmounts-test.js
  tests/models/awardsV2/BaseFederalAccountFunding-test.js
  tests/models/awardsV2/BaseParentAwardDetails-test.js
  tests/models/awardsV2/BaseReferencedAwardResult-test.js
  tests/models/awardsV2/CoreAward-test.js
Labels: down merge

#1519 [DEV-4373] Account FY Sort in Descending order
  src/js/components/sharedComponents/pickers/FYPicker.jsx
Labels: warm-fix

#1521 Downmerge Staging -> Dev
  src/_scss/pages/agency/v2/index.scss
  src/_scss/pages/bulkDownload/form/_fyPicker.scss
  src/js/components/sharedComponents/pickers/FYPicker.jsx
  src/js/containers/keyword/table/ResultsTableContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/helpers/apiRequest.js
  tests/containers/explorer/detail/DetailContentContainer-test.jsx
  tests/containers/explorer/detail/mockData.js
  tests/containers/keyword/mockResults.js
  tests/containers/keyword/table/ResultsTableContainer-test.jsx
  tests/containers/search/table/ResultsTableContainer-test.jsx
  tests/containers/search/table/mockAwards.js
  tests/helpers/apiRequest-test.js
  tests/mockData.js
  tests/models/awardsV2/BaseAwardAmounts-test.js
  tests/models/awardsV2/BaseFederalAccountFunding-test.js
  tests/models/awardsV2/BaseParentAwardDetails-test.js
  tests/models/awardsV2/BaseReferencedAwardResult-test.js
  tests/models/awardsV2/CoreAward-test.js
Labels: down merge

#1526 DOWNMERGE #2 Encoded Award IDs in Post Requests
  src/js/helpers/apiRequest.js
Labels: down merge

#1530 [DEV-4516] spending explorer dropdown 2017 not clickable
  src/_scss/pages/explorer/detail/sidebar/_fyPicker.scss
Labels: hotfix
