Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-04, with the labels that each got.

#1595 [DEV-3484] Follow up -- Ensuring Submit Search not only clears out all checked but also all Counts
  src/js/containers/search/filters/naics/NAICSContainer.jsx
Labels: warm-fix

#1599 [WARMFIX] Add cfda to loan transaction table
  src/js/dataMapping/awards/transactionHistoryTable/loanTransactionHistoryTable.js
  src/js/models/v2/awards/transactions/BaseLoanTransaction.js
  tests/models/awards/transactions/BaseTransactions-test.js
Labels: warm-fix

#1601 Down Merge QAT -> Dev
  src/js/components/award/financialAssistance/CFDATable.jsx
  src/js/components/award/financialAssistance/CFDATree.jsx
  src/js/components/award/financialAssistance/CFDATreeTooltip.jsx
  src/js/containers/award/financialAssistance/CFDAVizContainer.jsx
  src/js/containers/search/filters/naics/NAICSContainer.jsx
  src/js/dataMapping/awards/transactionHistoryTable/loanTransactionHistoryTable.js
  src/js/models/v2/awards/transactions/BaseLoanTransaction.js
  tests/models/awards/transactions/BaseTransactions-test.js
Labels: down merge

#1600 Down Merge QAT -> Staging
  src/js/components/award/financialAssistance/CFDATable.jsx
  src/js/components/award/financialAssistance/CFDATree.jsx
  src/js/components/award/financialAssistance/CFDATreeTooltip.jsx
  src/js/containers/award/financialAssistance/CFDAVizContainer.jsx
  src/js/containers/search/filters/naics/NAICSContainer.jsx
  src/js/dataMapping/awards/transactionHistoryTable/loanTransactionHistoryTable.js
  src/js/models/v2/awards/transactions/BaseLoanTransaction.js
  tests/models/awards/transactions/BaseTransactions-test.js
Labels: down merge

#1609 HotFix Dev-4833 Fed Account Program Activity Object Class Filter Bug
  src/js/components/account/filters/programActivity/ProgramActivityFilter.jsx
  src/js/containers/account/filters/AccountObjectClassContainer.jsx
  tests/containers/account/filters/AccountObjectClassContainer-test.jsx
Labels: hotfix

#1610 Downmerge Prod -> QAT Dev-4833 Fed Account Filters
  src/js/components/account/filters/programActivity/ProgramActivityFilter.jsx
  src/js/containers/account/filters/AccountObjectClassContainer.jsx
  tests/containers/account/filters/AccountObjectClassContainer-test.jsx
Labels: down merge

#1611 Downmerge QAT -> Dev Dev-4833 Fed Account Filters
  src/js/components/account/filters/programActivity/ProgramActivityFilter.jsx
  src/js/containers/account/filters/AccountObjectClassContainer.jsx
  tests/containers/account/filters/AccountObjectClassContainer-test.jsx
Labels: down merge

#1614 [DEV-4157] Relying on ENV VARs for GA config + Adding new ENV VAR for env [dev, qat, prod]
  src/index.ejs
  src/js/GlobalConstants.js
  src/js/helpers/analytics/Analytics.js
  webpack/webpack.common.js
  webpack/webpack.dev.config.js
  webpack/webpack.prod.config.js
Labels: do not merge

#1630 Warmfix Dev-4787 Amount CFDA Bad Data Height
  src/_scss/pages/award/visualizations/cfdaSectionViz.scss
Labels: warm-fix

#1633 Down Merge QAT -> Dev
  src/_scss/pages/award/visualizations/cfdaSectionViz.scss
Labels: down merge

#1634 WarmFix Dev-4787 Add More Z-Index
  src/_scss/pages/award/visualizations/cfdaSectionViz.scss
Labels: warm-fix

#1637 Downmerge Dev-4787 Add More Z-Index
  src/_scss/pages/award/visualizations/cfdaSectionViz.scss
Labels: down merge

#1640 [bug-hotfix-TAS-search-component-title] Fixing the title for the search sidebar
  src/js/components/search/SearchSidebar.jsx
Labels: hotfix

#1643 Down Merge from Master w/ Conflicts resolved
  src/js/components/search/SearchSidebar.jsx
Labels: down merge

#1644 Down Merge Qat -> Dev
  src/js/components/search/SearchSidebar.jsx
Labels: down merge
