Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-09, with the labels that each got.

#2045 DEV-5031 fix case where unchecking one checkbox would show message
  src/js/containers/search/filters/TimePeriodContainer.jsx
  tests/containers/search/filters/TimePeriodContainer-test.jsx
Labels: warm-fix

#2046 DEV-5655 fixes analytics firing for DEFC filters
  src/js/containers/search/filters/def/DEFCheckboxTree.jsx
  src/js/containers/search/helpers/searchAnalytics.js
Labels: warm-fix

#2044 [DEV-4478] WarmFix: Search Page Loads Hash Correctly
  src/js/containers/AppContainer.jsx
  src/js/containers/search/SearchContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/redux/reducers/search/searchFiltersReducer.js
  tests/containers/search/filters/searchHelper.js
  tests/containers/search/table/ResultsTableContainer-test.jsx
Labels: warm-fix

#2049 Sprint 115 Downmerge -- Time Period, Google Analytics, Router Bugs
  src/js/containers/AppContainer.jsx
  src/js/containers/search/SearchContainer.jsx
  src/js/containers/search/filters/TimePeriodContainer.jsx
  src/js/containers/search/filters/def/DEFCheckboxTree.jsx
  src/js/containers/search/helpers/searchAnalytics.js
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/redux/reducers/search/searchFiltersReducer.js
  tests/containers/search/filters/TimePeriodContainer-test.jsx
  tests/containers/search/filters/searchHelper.js
  tests/containers/search/table/ResultsTableContainer-test.jsx
Labels: down merge

#2050 Dev-5586 Add COVID-19 Spending Data Announcement
  src/index.ejs
Labels: hotfix

#2043 [DEV-5939] removes broken links for agencies in spending explorer
  src/js/components/explorer/detail/DetailContent.jsx
  src/js/components/explorer/detail/header/DetailHeader.jsx
  src/js/containers/explorer/detail/DetailContentContainer.jsx
  src/js/containers/explorer/detail/table/ExplorerTableContainer.jsx
Labels: pending-api

#2052 DownMerge [DEV-5586] Add announcement for COVID-19 (PR #2050)
  src/index.ejs
Labels: down merge

#2058 [router-upgrade-warmfix] Clear table when filters are manually deselected
  src/js/containers/search/SearchSidebarSubmitContainer.jsx
  tests/containers/search/SearchSidebarSubmitContainer-test.jsx
Labels: warm-fix

#2056 Down Merge Qat -> Dev COVID-19 Announcement
  src/index.ejs
  src/js/containers/search/SearchSidebarSubmitContainer.jsx
  tests/containers/search/SearchSidebarSubmitContainer-test.jsx
Labels: down merge

#2063 Bug Dev-4478 Advanced Search Download Availability
  src/js/containers/search/SearchContainer.jsx
Labels: warm-fix

#2064 Dev-5586 Remove Hashes from Google Announcement Links
  src/index.ejs
Labels: warm-fix

#2062 [DEV-5401] fix css/ period selection
  src/js/components/explorer/detail/sidebar/ExplorerSidebar.jsx
  src/js/containers/explorer/detail/helpers/explorerQuarters.js
  src/js/redux/reducers/explorer/explorerReducer.js
  tests/containers/explorer/detail/DetailContentContainer-test.jsx
  tests/redux/reducers/explorer/mockQuarterHelper.js
Labels: warm-fix

#2065 Down Merge Qat -> Dev
  src/index.ejs
  src/js/components/explorer/detail/sidebar/ExplorerSidebar.jsx
  src/js/containers/explorer/detail/helpers/explorerQuarters.js
  src/js/containers/search/SearchContainer.jsx
  src/js/redux/reducers/explorer/explorerReducer.js
  tests/containers/explorer/detail/DetailContentContainer-test.jsx
  tests/redux/reducers/explorer/mockQuarterHelper.js
Labels: down merge

#2053 [DEV-5734] Implement all COVID-19 Related Tooltips
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/pages/covid19/index.scss
  src/js/components/covid19/Covid19Section.jsx
  src/js/components/covid19/Covid19Tooltips.jsx
  src/js/components/covid19/recipient/map/MapFiltersHeader.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/helpers/covid19.jsx
Labels: pending design review

#2068 [DEV-6062] Updating text on COVID Profile Page per request from SBA
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
Labels: hotfix

#2069 Down Merge Prod -> QAT #2068
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
Labels: down merge

#2070 Down Merge #2068
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
Labels: down merge

#2073 [sitemap-hash] removing hash from static.xml sitemap
  src/js/scripts/buildSitemap.js
Labels: hotfix

#2075 Dev-5586 Google Announcement Additional Fields
  src/index.ejs
Labels: hotfix

#2076 [DEV-6081] Fixing Link per request on the About Page
  src/js/components/about/DataQuality.jsx
Labels: hotfix

#2074 Down Merge Prod -> QAT #2073 Sitemap Hashes
  src/index.ejs
  src/js/components/about/DataQuality.jsx
  src/js/scripts/buildSitemap.js
Labels: down merge

#2077 [DEV-5229] Handling Top Tier Search Result w/ no children when existing tree has those Children
  src/js/helpers/checkboxTreeHelper.js
  tests/helpers/checkboxTreeHelper-test.js
Labels: warm-fix

#2080 [DEV-6076] updating hard-coded text on home page from June to July
  src/js/containers/covid19/homepage/CovidHighlights.jsx
Labels: hotfix

#2079 Dev-6079 COVID-19 Profile Page Mobile Bugs
  src/_scss/pages/covid19/_dataSourcesAndMethodology.scss
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/js/components/covid19/AmountsVisualization.jsx
  src/js/components/covid19/DataSourcesAndMethodology.jsx
  src/js/components/covid19/OtherResources.jsx
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/helpers/covid19.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
Labels: warm-fix

#2081 Prod -> QAT #2080
  src/js/containers/covid19/homepage/CovidHighlights.jsx
Labels: down merge

#2078 Down Merging 3 Hotfixes from #2074
  src/_scss/pages/covid19/_dataSourcesAndMethodology.scss
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/index.ejs
  src/js/components/about/DataQuality.jsx
  src/js/components/covid19/AmountsVisualization.jsx
  src/js/components/covid19/DataSourcesAndMethodology.jsx
  src/js/components/covid19/OtherResources.jsx
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/helpers/covid19.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
  src/js/helpers/checkboxTreeHelper.js
  src/js/scripts/buildSitemap.js
  tests/helpers/checkboxTreeHelper-test.js
Labels: do not merge, down merge

#2085 [DEV-5734] Covid tooltips text fixes
  src/js/components/covid19/Covid19Tooltips.jsx
Labels: warm-fix

#2086 Down Merge qat -> dev
  src/js/components/covid19/Covid19Tooltips.jsx
Labels: down merge

#2088 [DEV-4644] - Add 'unique award key' box to Additional Information section of award summary v2.0
  src/_scss/pages/award/visualizations/_additionalInfo.scss
  src/js/app.jsx
  src/js/components/award/shared/additionalInfo/Accordion.jsx
  src/js/components/award/shared/additionalInfo/AdditionalInfo.jsx
  src/js/components/award/shared/overview/RelatedAwards.jsx
  src/js/dataMapping/award/additionalDetailsContract.js
  src/js/dataMapping/award/additionalDetailsFinancialAssistance.js
  src/js/dataMapping/award/additionalDetailsIdv.js
  src/js/helpers/awardSummaryHelper.js
  src/js/models/v2/award/BaseParentAwardDetails.js
  tests/helpers/awardSummaryHelper-test.js
Labels: do not merge, pending design review

#2067 Fix dev 5819 covid19map
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/helpers/covid19Helper.js
Labels: warm-fix

#2094 [DEV-5551][DEV-5549] Fix wording and some award counts
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/SummaryInsightsContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/helpers/covid19Helper.js
  src/js/redux/actions/covid19/covid19Actions.js
  src/js/redux/reducers/covid19/covid19Reducer.js
  tests/helpers/covid19Helper-test.js
  tests/redux/reducers/covid19/covid19Reducer-test.js
Labels: warm-fix

#2097 Dev-5962 CFDA Modal URL Wrap
  src/_scss/pages/modals/covid19/_cfdaTable.scss
Labels: warm-fix

#2089 [DEV-5971] using the funding agency for the site description rather than the awarding agency
  src/js/helpers/metaTagHelper.js
Labels: warm-fix

#2098 Qat -> Dev #2067
  src/_scss/pages/modals/covid19/_cfdaTable.scss
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/SummaryInsightsContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/helpers/covid19Helper.js
  src/js/helpers/metaTagHelper.js
  src/js/redux/actions/covid19/covid19Actions.js
  src/js/redux/reducers/covid19/covid19Reducer.js
  tests/helpers/covid19Helper-test.js
  tests/redux/reducers/covid19/covid19Reducer-test.js
Labels: down merge

#2104 Dev-5962 update min width for the modal on large screens
  src/_scss/pages/modals/covid19/_cfdaTable.scss
Labels: warm-fix

#2103 [DEV-5551] Clear out old values in Redux when switching tabs
  src/js/containers/covid19/SummaryInsightsContainer.jsx
Labels: warm-fix

#2106 [DEV-5971] Updating Spending Explorer Site Title and Agency Title Description for ASST_AGG Awards
  src/js/helpers/metaTagHelper.js
Labels: warm-fix

#2108 removing .gov from all site titles
  src/js/helpers/metaTagHelper.js
Labels: warm-fix

#2111 [DEV-6128] updating url
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/containers/covid19/Covid19Container.jsx
Labels: hotfix

#2112 Down merge master w/ conflicts resolved
  src/data/data-limitations-v2.pdf
  src/data/data-limitations.pdf
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/recipient/RecipientContainer.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
Labels: down merge

#2114 [DEV-6070] Update range for mapping scale
  src/js/components/covid19/recipient/map/MapWrapper.jsx
Labels: warm-fix

#2115 [DEV-5819] COVID-Map Warm Fix PR #2114
  src/js/components/covid19/recipient/map/MapWrapper.jsx
Labels: down merge

#2117 Bug cfda icon click
  src/data/data-limitations.pdf
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/recipient/RecipientContainer.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
Labels: hotfix

#2119 Downmerge Prod -> QAT #2117
  src/data/data-limitations.pdf
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/recipient/RecipientContainer.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
Labels: down merge

#2123 Bug Dev-6152 Update Links
  src/js/components/award/shared/federalAccounts/FederalAccountsTable.jsx
Labels: warm-fix

#2124 [DEV-5766] warmfix - fix sorting error for new DEFC column
  src/js/components/search/table/ResultsTable.jsx
  src/js/dataMapping/search/awardTableColumns.jsx
Labels: warm-fix

#2125 DownMerge Qat -> Dev #2123 & #2124
  src/js/components/award/shared/federalAccounts/FederalAccountsTable.jsx
  src/js/components/search/table/ResultsTable.jsx
  src/js/dataMapping/search/awardTableColumns.jsx
Labels: down merge

#2129 [DEV-4976] updating key on award object in Referenced Awards Container from counts to idvDetails
  src/js/containers/award/idv/ReferencedAwardsContainer.jsx
  tests/containers/award/mockAward.js
Labels: hotfix

#2130 Down Merge Prod -> QAT #2129 Referenced Award Container
  src/js/containers/award/idv/ReferencedAwardsContainer.jsx
  tests/containers/award/mockAward.js
Labels: down merge

#2134 [DEV-6182] logging pageviews when a user changes their route via client side router
  src/js/containers/AppContainer.jsx
  src/js/helpers/analytics/Analytics.js
Labels: hotfix

#2138 Down merge Hotfix
  src/js/containers/AppContainer.jsx
  src/js/helpers/analytics/Analytics.js
Labels: down merge
