Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-08, with the labels that each got.

#1979 Dev-5825 Recipient Loan Sort & API Request Bug
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
Labels: warm-fix

#1984 Dev-5718 Recipient Map Min Zoom Territory Filters 2
  src/js/dataMapping/covid19/recipient/map/map.js
Labels: warm-fix

#1981 [DEV-5832] Make the Covid Banner Sticky and Dismissible
  src/_scss/pages/covid19/_sidebar.scss
  src/_scss/pages/covid19/_stickyHeader.scss
  src/_scss/pages/covid19/index.scss
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/components/sharedComponents/sidebar/Sidebar.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/dataMapping/covid19/covid19.js
  src/js/helpers/covid19Helper.js
Labels: warm-fix

#1985 change scale to exponential for covid19 map
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/dataMapping/covid19/recipient/map/map.js
  src/js/helpers/covid19Helper.js
Labels: warm-fix

#1992 Ftr/dev 5830/add disclaimer line about utah to map
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/js/components/covid19/recipient/map/MapWrapper.jsx
Labels: warm-fix

#1991 DEV-5838 COVID global modal disclaimer
  src/_scss/pages/modals/covid19/_covid19.scss
  src/js/containers/covid19/CovidModalContainer.jsx
Labels: warm-fix

#1987 Advanced Search No Zoom for Congressional Districts and Counties
  src/js/components/search/visualizations/geo/MapWrapper.jsx
Labels: warm-fix

#1989 [DEV-5833] COVID Data Limitations Banner on DS&M Page
  src/_scss/layouts/default/header/_warning.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/data-sources/index.scss
  src/data/data-limitations.pdf
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/components/covid19/SidebarFooter.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/dataMapping/covid19/covid19.js
  src/js/helpers/covid19Helper.js
  webpack/webpack.common.js
Labels: warm-fix

#1993 DEV-5838 fix typo & console error
  src/js/components/homepage/hero/TotalAmount.jsx
  src/js/containers/covid19/CovidModalContainer.jsx
Labels: warm-fix

#1997 DEV-5840 Fix data as of notes
  src/js/components/covid19/DateNote.jsx
  src/js/helpers/covid19Helper.js
  tests/helpers/covid19Helper-test.js
Labels: warm-fix

#2004 Demote Hotfix master -> qat
  src/js/GlobalConstants.js
Labels: down merge

#2005 QAT -> Dev
  src/_scss/layouts/default/header/_warning.scss
  src/_scss/pages/covid19/_budgetCategoriesTable.scss
  src/_scss/pages/covid19/_sidebar.scss
  src/_scss/pages/covid19/_stickyHeader.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/_scss/pages/data-sources/index.scss
  src/_scss/pages/modals/covid19/_covid19.scss
  src/data/data-limitations.pdf
  src/js/GlobalConstants.js
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/components/covid19/DateNote.jsx
  src/js/components/covid19/SidebarFooter.jsx
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/components/homepage/hero/TotalAmount.jsx
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/components/sharedComponents/sidebar/Sidebar.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/CovidModalContainer.jsx
  src/js/containers/covid19/homepage/CovidFeatureContainer.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
  src/js/containers/covid19/recipient/RecipientContainer.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/dataMapping/covid19/covid19.js
  src/js/dataMapping/covid19/recipient/map/map.js
  src/js/helpers/covid19Helper.js
  tests/helpers/covid19Helper-test.js
  webpack/webpack.common.js
Labels: down merge

#2016 [DEV-5405] warmfix - reorder resources links
  src/js/containers/Footer.jsx
Labels: warm-fix

#2020 Down Merge: Data Dictionary Link Order in Footer
  src/js/containers/Footer.jsx
Labels: down merge

#2021 DEV-5776 [Warm-fix] added WebGL error messages to state profile and advanced search maps
  src/_scss/pages/search/results/_tables.scss
  src/_scss/pages/search/results/searchResults.scss
  src/_scss/pages/state/_contentWrap.scss
  src/_scss/pages/state/_tables.scss
  src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
  src/js/components/state/visualizations/geo/GeoVisualizationSection.jsx
Labels: warm-fix

#2022 QAT -> Dev MapBoxGL
  src/_scss/pages/search/results/_tables.scss
  src/_scss/pages/search/results/searchResults.scss
  src/_scss/pages/state/_contentWrap.scss
  src/_scss/pages/state/_tables.scss
  src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
  src/js/components/state/visualizations/geo/GeoVisualizationSection.jsx
Labels: down merge

#2019 Fix dev 5819 covid19map
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/_scss/pages/search/results/visualizations/geo/map/_legend.scss
  src/js/components/covid19/recipient/map/MapLegend.jsx
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/helpers/covid19Helper.js
Labels: do not merge, pending design review

#2030 HotFix Dev-5745 Recipient Map Loan Filter Bug
  src/js/components/covid19/recipient/AwardFilterButtons.jsx
  src/js/components/covid19/recipient/SpendingByRecipient.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
Labels: hotfix

#2032 Down Merge Hot Fix for AC 1 of DEV-5745 (#2030)
  src/js/components/covid19/recipient/AwardFilterButtons.jsx
  src/js/components/covid19/recipient/SpendingByRecipient.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
Labels: down merge

#2033 Qat -> Dev Downmerge #2030
  src/js/components/covid19/recipient/AwardFilterButtons.jsx
  src/js/components/covid19/recipient/SpendingByRecipient.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
Labels: down merge

#2035 [DEV-5796] Remove whitespace from search bar input
  src/js/components/covid19/SearchBar.jsx
Labels: warm-fix

#2034 [DEV-5969] Glossary Icon Click Scrolls Window to Top of Screen
  src/js/components/award/shared/description/AwardDescription.jsx
  src/js/components/bulkDownload/accounts/AccountDataContent.jsx
  src/js/components/explorer/landing/ExplorerLanding.jsx
  src/js/components/explorer/landing/ExplorerLandingOption.jsx
  src/js/components/sharedComponents/filterSidebar/FilterSidebar.jsx
Labels: warm-fix

#2037 Downmerge QAT -> DEV
  src/js/components/award/shared/description/AwardDescription.jsx
  src/js/components/bulkDownload/accounts/AccountDataContent.jsx
  src/js/components/covid19/SearchBar.jsx
  src/js/components/explorer/landing/ExplorerLanding.jsx
  src/js/components/explorer/landing/ExplorerLandingOption.jsx
  src/js/components/sharedComponents/filterSidebar/FilterSidebar.jsx
Labels: down merge

#2038 DEV-5031 [FIX] added clear hint logic to hide hint in certain cases in advanced search time period filter
  src/js/components/search/filters/timePeriod/TimePeriod.jsx
Labels: warm-fix

#2039 Qat -> Dev Advanced Search Year Filter
  src/js/components/search/filters/timePeriod/TimePeriod.jsx
Labels: down merge

#2040 DEV-5791 fix casing and css for copy-confirmation
  src/_scss/pages/data-sources/index.scss
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Labels: warm-fix

#2041 Qat -> Dev Text Change
  src/_scss/pages/data-sources/index.scss
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Labels: down merge
