Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-12, with the labels that each got.

#2250 Sprint 121 -> QAT
  jest.config.js
  src/_scss/pages/aboutTheData/_actionCell.scss
  src/_scss/pages/aboutTheData/agenciesDetailPage.scss
  src/_scss/pages/aboutTheData/agenciesPage.scss
  src/_scss/pages/bulkDownload/bulkDownloadPage.scss
  src/_scss/pages/bulkDownload/metadataPage.scss
  src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
  src/_scss/pages/modals/all.scss
  src/_scss/pages/search/results/visualizations/time/timeVisualization.scss
  src/js/app.jsx
  src/js/components/aboutTheData/AboutTheDataModal.jsx
  src/js/components/aboutTheData/AgencyDownloadLinkCell.jsx
  src/js/components/aboutTheData/CellWithModal.jsx
  src/js/components/aboutTheData/DrilldownCell.jsx
  src/js/components/aboutTheData/dataMapping/modals/modalContentMapping.jsx
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/bulkDownload/MetadataDownload.jsx
  src/js/components/search/visualizations/time/TimeVisualizationSection.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgenciesDetailContainer.jsx
  src/js/containers/aboutTheData/modals/MissingAccountBalanceContainer.jsx
  src/js/containers/aboutTheData/modals/PublicationDatesContainer.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/dataMapping/aboutTheData/modals.js
  src/js/dataMapping/aboutTheData/periodToQuarterMapping.js
  src/js/dataMapping/navigation/menuOptions.jsx
  src/js/helpers/aboutTheDataHelper.js
  src/js/helpers/accountHelper.js
  src/js/helpers/browser.js
  src/js/helpers/metaTagHelper.js
  src/js/helpers/monthHelper.js
  src/js/redux/actions/account/accountActions.js
  src/js/redux/reducers/account/accountReducer.js
  tests/components/aboutTheData/AboutTheDataModal-test.jsx
  tests/components/aboutTheData/CellWithModal-test.jsx
  tests/components/covid19/homepage/TotalAmount-test.jsx
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/containers/aboutTheData/MissingAccountBalanceContainer-test.jsx
  tests/containers/aboutTheData/PublicationDatesContainer-test.jsx
  tests/helpers/aboutTheDataHelper-test.js
  tests/helpers/accountHelper-test.js
  tests/helpers/monthHelper-test.js
  tests/mockData.js
  tests/redux/reducers/account/accountReducer-test.js
  tests/testResources/stylesStub.js
Labels: ENV Promotion

#2251 Bug Show About The Data Agencies in QAT
  src/js/containers/router/RouterRoutes.js
Labels: warm-fix

#2253 Demote warmfix qat -> dev
  src/js/containers/router/RouterRoutes.js
Labels: down merge

#2254 Hotfix Semicolon
  src/js/components/search/visualizations/time/TimeVisualization.jsx
Labels: hotfix

#2255 Downmerge semicolon bug into qat
  src/js/components/search/visualizations/time/TimeVisualization.jsx
Labels: down merge

#2265 Dev-6516 Default Modal Size
  src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
  src/_scss/pages/modals/covid19/_cfdaTable.scss
Labels: warm-fix

#2267 Demote warmfixes qat -> dev
  src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
  src/_scss/pages/modals/covid19/_cfdaTable.scss
  src/js/components/search/visualizations/time/TimeVisualization.jsx
Labels: down merge

#2275 Sprint 121 -> Production
  jest.config.js
  src/_scss/pages/aboutTheData/_actionCell.scss
  src/_scss/pages/aboutTheData/agenciesDetailPage.scss
  src/_scss/pages/aboutTheData/agenciesPage.scss
  src/_scss/pages/bulkDownload/bulkDownloadPage.scss
  src/_scss/pages/bulkDownload/metadataPage.scss
  src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
  src/_scss/pages/modals/all.scss
  src/_scss/pages/modals/covid19/_cfdaTable.scss
  src/_scss/pages/search/results/visualizations/time/timeVisualization.scss
  src/js/app.jsx
  src/js/components/aboutTheData/AboutTheDataModal.jsx
  src/js/components/aboutTheData/AgencyDownloadLinkCell.jsx
  src/js/components/aboutTheData/CellWithModal.jsx
  src/js/components/aboutTheData/DrilldownCell.jsx
  src/js/components/aboutTheData/dataMapping/modals/modalContentMapping.jsx
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/bulkDownload/MetadataDownload.jsx
  src/js/components/search/visualizations/time/TimeVisualizationSection.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgenciesDetailContainer.jsx
  src/js/containers/aboutTheData/modals/MissingAccountBalanceContainer.jsx
  src/js/containers/aboutTheData/modals/PublicationDatesContainer.jsx
  src/js/dataMapping/aboutTheData/modals.js
  src/js/dataMapping/aboutTheData/periodToQuarterMapping.js
  src/js/dataMapping/navigation/menuOptions.jsx
  src/js/helpers/aboutTheDataHelper.js
  src/js/helpers/accountHelper.js
  src/js/helpers/browser.js
  src/js/helpers/metaTagHelper.js
  src/js/helpers/monthHelper.js
  src/js/redux/actions/account/accountActions.js
  src/js/redux/reducers/account/accountReducer.js
  tests/components/aboutTheData/AboutTheDataModal-test.jsx
  tests/components/aboutTheData/CellWithModal-test.jsx
  tests/components/covid19/homepage/TotalAmount-test.jsx
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/containers/aboutTheData/MissingAccountBalanceContainer-test.jsx
  tests/containers/aboutTheData/PublicationDatesContainer-test.jsx
  tests/helpers/aboutTheDataHelper-test.js
  tests/helpers/accountHelper-test.js
  tests/helpers/monthHelper-test.js
  tests/mockData.js
  tests/redux/reducers/account/accountReducer-test.js
  tests/testResources/stylesStub.js
Labels: ENV Promotion

#2277 dev-6486 final wording fix
  src/js/components/search/visualizations/time/TimeVisualizationSection.jsx
Labels: warm-fix

#2279 Qat -> Dev #2277
  src/js/components/search/visualizations/time/TimeVisualizationSection.jsx
Labels: down merge
