Repository fedspendingtransparency/usaspending-website, pull requests merged in 2020-06, with the labels that each got.

#1711 Hot Fix Cares Act Homepage Update
  src/_scss/layouts/default/header/_warning.scss
  src/_scss/pages/homepage/features/_featurePane.scss
  src/js/components/homepage/features/PaneFeature.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
Labels: warm-fix

#1713 Demote homepage warmfix qat --> dev
  src/_scss/layouts/default/header/_warning.scss
  src/_scss/pages/homepage/features/_featurePane.scss
  src/js/components/homepage/features/PaneFeature.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
Labels: down merge

#1721 Qat -> Dev Bug Expand Time Period Advanced Search Filter
  src/js/components/search/SearchSidebar.jsx
Labels: down merge

#1722 Bug Dev-5166 Typo pack -> back
  src/js/components/award/shared/InfoTooltipContent.jsx
  src/js/dataMapping/shared/tableTabsTooltips.jsx
Labels: warm-fix

#1723 Demote warmfix qat -> dev
  src/js/components/award/shared/InfoTooltipContent.jsx
  src/js/dataMapping/shared/tableTabsTooltips.jsx
Labels: down merge

#1726 [DEV-5198 & 5166] Warmfix IE Tooltip Bugs - Nested tooltips inside buttons
  src/_scss/pages/award/idv/_referencedAwards.scss
  src/_scss/pages/award/shared/_awardHistorySection.scss
  src/_scss/pages/recipientLanding/recipientLandingPage.scss
  src/_scss/pages/search/_tooltips.scss
  src/_scss/pages/search/results/table/_resultsTablePicker.scss
  src/_scss/pages/search/results/table/_tableTypes.scss
  src/_scss/pages/state/topFive/_topFive.scss
  src/js/components/award/table/DetailsTabItem.jsx
  src/js/components/search/table/ResultsTableTabItem.jsx
  src/js/components/sharedComponents/filterSidebar/FilterExpandButton.jsx
Labels: warm-fix

#1727 Down Merge Qat -> Dev Tooltip CSS
  src/_scss/pages/award/idv/_referencedAwards.scss
  src/_scss/pages/award/shared/_awardHistorySection.scss
  src/_scss/pages/recipientLanding/recipientLandingPage.scss
  src/_scss/pages/search/_tooltips.scss
  src/_scss/pages/search/results/table/_resultsTablePicker.scss
  src/_scss/pages/search/results/table/_tableTypes.scss
  src/_scss/pages/state/topFive/_topFive.scss
  src/js/components/award/table/DetailsTabItem.jsx
  src/js/components/search/table/ResultsTableTabItem.jsx
  src/js/components/sharedComponents/filterSidebar/FilterExpandButton.jsx
Labels: down merge

#1734 Warm Fix Dev-5197 Contract Grant Activity Chart Updates
  src/_scss/pages/award/shared/contractGrantsActivity.scss
  src/js/components/award/shared/activity/ContractGrantActivityChartAreaPaths.jsx
  src/js/components/award/shared/activity/Tooltip.jsx
Labels: warm-fix

#1735 Qat -> Dev
  src/_scss/pages/award/shared/contractGrantsActivity.scss
  src/js/components/award/shared/activity/ContractGrantActivityChartAreaPaths.jsx
  src/js/components/award/shared/activity/Tooltip.jsx
Labels: down merge

#1736 Warm Fix - Release The Contract Grant Activity Container
  src/js/components/award/contract/ContractContent.jsx
  src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
  src/js/containers/award/shared/ContractGrantActivityContainer.jsx
Labels: warm-fix

#1738 Demote warmfix qat -> dev
  src/js/components/award/contract/ContractContent.jsx
  src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
  src/js/containers/award/shared/ContractGrantActivityContainer.jsx
Labels: down merge

#1746 [DEV-5417] Fix bugs on Federal Account page filter
  src/js/components/account/SearchSidebar.jsx
  src/js/models/account/queries/queryBuilders/_programActivityTranslator.js
Labels: hotfix

#1747 Downmerge Master -> QAT
  src/js/components/account/SearchSidebar.jsx
  src/js/models/account/queries/queryBuilders/_programActivityTranslator.js
Labels: down merge

#1748 Qat -> Dev
  src/js/components/account/SearchSidebar.jsx
  src/js/models/account/queries/queryBuilders/_programActivityTranslator.js
Labels: down merge

#1750 [DEV-5318] Correction of Dark Release Logic for Award Amounts Viz
  src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
Labels: warm-fix

#1755 [DEV-5254] updating tooltip copy for Tas per A/C 3 and 3a
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
Labels: warm-fix

#1756 Qat -> Dev Tooltip Copy
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
Labels: down merge

#1742 DEV-5295 new awards over time table
  src/_scss/pages/covid19/spendingOverTime/_awardSpendingOverTime.scss
  src/js/components/covid19/spendingOverTime/AmountTab.jsx
  src/js/components/covid19/spendingOverTime/AwardSpendingOverTime.jsx
  src/js/containers/covid19/spendingOverTime/SpendingOverTimeContainer.jsx
  src/js/helpers/disasterHelper.js
  tests/containers/covid19/SpendingOverTimeContainer-test.jsx
Labels: pending-api

#1759 Dev-5254 Update Text
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
Labels: warm-fix

#1760 Demote warmfix qat -> dev
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
Labels: down merge

#1737 DEV-5287 covid19 budget categories section
  src/_scss/pages/agency/v2/_tabs.scss
  src/_scss/pages/agency/v2/index.scss
  src/_scss/pages/covid19/_budgetCategoriesTable.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/search/results/table/_resultsTableMessageContainer.scss
  src/js/components/award/shared/InfoTooltipContent.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/covid19/budgetCategories/BudgetCategoriesCountTab.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesCountTabContainer.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/helpers/covid19.jsx
  src/js/dataMapping/covid19/budgetCategories/BudgetCategoriesTableColumns.js
  src/js/helpers/covid19/budgetCategoriesHelper.js
  src/js/models/covid19/budgetCategories/BaseBudgetCategoryRow.js
  tests/models/covid19/budgetCategories/BaseBudgetCategoryRow-test.js
Labels: pending-api

#1763 Bug & Updates Contract Grant Activity Chart
  src/js/components/award/shared/activity/ContractGrantActivity.jsx
  src/js/components/sharedComponents/DatePicker.jsx
  src/js/helpers/contractGrantActivityHelper.js
  tests/helpers/contractGrantActivityHelper-test.js
Labels: warm-fix

#1765 Bug Fix - updated recipient overview heading in recipient section
  src/js/components/recipient/RecipientOverview.jsx
Labels: warm-fix

#1768 update action type text in circle tooltip
  src/js/components/award/shared/activity/ContractGrantActivity.jsx
Labels: warm-fix

#1771 Demote warmfix qat -> dev
  src/js/components/award/shared/activity/ContractGrantActivity.jsx
Labels: down merge

#1744 [DEV-5132] Award Summary Flag, Dark Release
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/pages/award/awardPage.scss
  src/_scss/pages/award/visualizations/awardViz.scss
  src/js/components/award/contract/ContractContent.jsx
  src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
  src/js/components/award/idv/IdvContent.jsx
  src/js/components/award/shared/AwardPageWrapper.jsx
  src/js/components/award/shared/InfoTooltipContent.jsx
  src/js/containers/award/idv/ReferencedAwardsContainer.jsx
  src/js/helpers/covid19Helper.js
  src/js/models/v2/award/BaseContract.js
  src/js/models/v2/award/BaseFinancialAssistance.js
  src/js/models/v2/award/BaseIdv.js
  src/js/models/v2/award/CoreAward.js
  src/js/propTypes/index.js
Labels: do not merge, pending-api
