Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-06, with the labels that each got.

#2593 Fix Homepage images for XL screens
  src/img/homepage-keyword-search@2x.webp
  src/img/homepage-profile-agency@2x.webp
  src/img/homepage-profile-recipient@2x.webp
Labels: warm-fix

#2595 Demote warmfix qat -> dev
  src/img/homepage-keyword-search@2x.webp
  src/img/homepage-profile-agency@2x.webp
  src/img/homepage-profile-recipient@2x.webp
Labels: down merge

#2597 Demote hotfix master -> qat
  src/js/components/search/SearchPage.jsx
  src/js/components/sharedComponents/PageWrapper.jsx
  src/js/containers/search/SearchContainer.jsx
Labels: down merge

#2598 Qat -> Dev #2596
  src/js/components/search/SearchPage.jsx
  src/js/components/sharedComponents/PageWrapper.jsx
  src/js/containers/search/SearchContainer.jsx
Labels: down merge

#2600 Sprint 134 Dev -> QAT
  package-lock.json
  package.json
  scripts/sitemaps/package-lock.json
  scripts/sitemaps/package.json
  src/_scss/pages/agencyV2/index.scss
  src/_scss/pages/agencyV2/overview/_barChart.scss
  src/_scss/pages/agencyV2/overview/_visualizationSection.scss
  src/_scss/pages/agencyV2/visualizations/_totalObligationsOverTime.scss
  src/_scss/pages/covid19/_dataSourcesAndMethodology.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/covid19/visualizations/_amounts.scss
  src/_scss/pages/homepage/hero/_covid-hero.scss
  src/img/desktop@2x.png
  src/img/mobile@2x.png
  src/js/components/agencyV2/AgencySection.jsx
  src/js/components/agencyV2/overview/BarChart.jsx
  src/js/components/agencyV2/overview/FySummary.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/TodayLineAndtext.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/axis/Axis.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/axis/AxisLabel.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/axis/XAxis.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/axis/YAxis.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/AreaPath.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/Path.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/Paths.jsx
  src/js/components/covid19/Heading.jsx
  src/js/components/covid19/OtherResources.jsx
  src/js/components/covid19/amountsVisualization/AmountsVisualization.jsx
  src/js/components/covid19/amountsVisualization/amounts/PercentLabels.jsx
  src/js/components/covid19/amountsVisualization/amounts/remainingBalance/LinesAndText.jsx
  src/js/components/covid19/amountsVisualization/amounts/remainingBalance/RemainingBalance.jsx
  src/js/components/covid19/amountsVisualization/amounts/shared/DefaultAmountViz.jsx
  src/js/components/covid19/amountsVisualization/amounts/shared/DefaultLine.jsx
  src/js/components/covid19/amountsVisualization/amounts/shared/DefaultLineAndText.jsx
  src/js/components/covid19/amountsVisualization/amounts/shared/Rectangle.jsx
  src/js/components/covid19/amountsVisualization/amounts/shared/TextGroup.jsx
  src/js/components/covid19/amountsVisualization/amounts/totalObligations/LineAndText.jsx
  src/js/components/covid19/amountsVisualization/amounts/totalObligations/TotalObligations.jsx
  src/js/containers/agencyV2/visualizations/TotalObligationsOverTimeContainer.jsx
  src/js/containers/homepage/CovidHighlights.jsx
  src/js/dataMapping/agencyV2/visualizations/totalObligationsOverTime.js
  src/js/dataMapping/covid19/amountsVisualization.js
  src/js/helpers/agencyV2/visualizations/TotalObligationsOverTimeVisualizationHelper.js
  src/js/helpers/covid19/amountsVisualization.js
  src/js/models/v2/agency/BaseAgencyBudgetaryResources.js
  tests/components/agency/overview/BarChart-test.jsx
  tests/components/agency/overview/TotalObligationsOverTimeVisualization-test.jsx
  tests/components/covid19/amountsVisualization-test.jsx
  tests/containers/agencyV2/AgencyContainerV2-test.jsx
  tests/models/agency/BaseAgencyBudgetaryResources-test.js
Labels: ENV Promotion

#2610 DEV-7432 Hotfix homepage images in Safari
  src/_scss/pages/homepage/features/_carousel.scss
  src/_scss/pages/homepage/features/_covidFeature.scss
  src/js/components/homepage/features/ImageCarousel.jsx
  src/js/components/homepage/features/SpendingExplorerFeature.jsx
  src/js/containers/homepage/CovidFeatureContainer.jsx
Labels: hotfix

#2621 DEV-7432 Hotfix --> qat
  src/_scss/pages/homepage/features/_carousel.scss
  src/_scss/pages/homepage/features/_covidFeature.scss
  src/js/components/homepage/features/ImageCarousel.jsx
  src/js/components/homepage/features/SpendingExplorerFeature.jsx
  src/js/containers/homepage/CovidFeatureContainer.jsx
Labels: down merge

#2624 [dev-7401] Fix award spending sub-agency and CFDA copy
  src/js/components/covid19/Covid19Tooltips.jsx
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
Labels: warm-fix

#2625 DEV-7401 Warmfix downmerge to qat
  src/js/components/covid19/Covid19Tooltips.jsx
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
Labels: down merge

#2630 Dev-7525 Federal Account Page Award ID Click Bug
  src/js/components/search/table/ResultsTable.jsx
Labels: hotfix

#2628 flag external links
  src/js/components/bulkDownload/sidebar/BulkDownloadSidebar.jsx
  src/js/components/bulkDownload/sidebar/SidebarButton.jsx
  src/js/components/homepage/download/DownloadDetail.jsx
  src/js/components/sharedComponents/header/DropdownItem.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdownItem.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: hotfix

#2633 Down merge into Staging Dev-7525 fed acct award id link
  src/js/components/search/table/ResultsTable.jsx
Labels: down merge

#2634 Down merge into QAT Dev-7525 fed acct award id link
  src/js/components/search/table/ResultsTable.jsx
Labels: down merge

#2635 Down merge into QAT Dev-7474 fix menu links for mobile
  src/js/components/bulkDownload/sidebar/BulkDownloadSidebar.jsx
  src/js/components/bulkDownload/sidebar/SidebarButton.jsx
  src/js/components/homepage/download/DownloadDetail.jsx
  src/js/components/sharedComponents/header/DropdownItem.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdownItem.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge
