Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-07, with the labels that each got.

#2646 Dev-7567 Homepage Vaccine Link
  src/_scss/layouts/default/header/nav/headerNav.scss
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/_scss/pages/homepage/homePage.scss
  src/img/covid-vaccine-link.svg
  src/js/components/homepage/CovidVaccineLink.jsx
  src/js/components/homepage/Homepage.jsx
Labels: hotfix

#2650 Dev-7567 remove image and source and update css for link
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/img/covid-vaccine-link.svg
  src/js/components/homepage/CovidVaccineLink.jsx
Labels: hotfix

#2652 Dev-7567 Homepage Vaccine Link Downmerge to QAT
  src/_scss/layouts/default/header/nav/headerNav.scss
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/_scss/pages/homepage/homePage.scss
  src/js/components/homepage/CovidVaccineLink.jsx
  src/js/components/homepage/Homepage.jsx
Labels: down merge

#2651 Dev-7567 Homepage Vaccine Link Downmerge to Staging
  src/_scss/layouts/default/header/nav/headerNav.scss
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/_scss/pages/homepage/homePage.scss
  src/js/components/homepage/CovidVaccineLink.jsx
  src/js/components/homepage/Homepage.jsx
Labels: do not merge, down merge

#2653 Hotfix DEV-7575 vaccines.gov banner
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/img/wcdt.png
  src/js/components/homepage/CovidVaccineLink.jsx
Labels: hotfix

#2654 Dev-7575 vaccines banner Downmerge to Staging
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/img/wcdt.png
  src/js/components/homepage/CovidVaccineLink.jsx
Labels: down merge

#2655 Dev-7575 vaccines banner Downmerge to QAT
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/img/wcdt.png
  src/js/components/homepage/CovidVaccineLink.jsx
Labels: down merge
