Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-11, with the labels that each got.

#2783 Qat -> Staging
  src/_scss/lib/bourbon/css3/_selection.scss
  src/_scss/pages/about/_section.scss
  src/_scss/pages/agencyV2/_tables.scss
  src/_scss/pages/agencyV2/index.scss
  src/_scss/pages/agencyV2/statusOfFunds/_drilldownSidebar.scss
  src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
  src/_scss/pages/agencyV2/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/covid19/_header.scss
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/_scss/pages/homepage/hero/_covid-hero.scss
  src/_scss/pages/homepage/homePage.scss
  src/js/apis/agencyV2.js
  src/js/components/about/Careers.jsx
  src/js/components/about/DataQuality.jsx
  src/js/components/about/Development.jsx
  src/js/components/about/MoreInfo.jsx
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/agencyV2/AgencyPage.jsx
  src/js/components/agencyV2/AgencySection.jsx
  src/js/components/agencyV2/accountSpending/AccountSpending.jsx
  src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx
  src/js/components/agencyV2/overview/AgencyOverview.jsx
  src/js/components/agencyV2/overview/FySummary.jsx
  src/js/components/agencyV2/statusOfFunds/DrilldownSidebar.jsx
  src/js/components/agencyV2/statusOfFunds/IntroSection.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx
  src/js/components/award/shared/federalAccounts/FederalAccountsTable.jsx
  src/js/components/covid19/PublicLawPicker.jsx
  src/js/components/homepage/CovidVaccineLink.jsx
  src/js/components/homepage/Homepage.jsx
  src/js/containers/agencyV2/AgencyContainerV2.jsx
  src/js/containers/agencyV2/WithAgencySlugs.jsx
  src/js/containers/agencyV2/accountSpending/CountTabContainer.jsx
  src/js/containers/agencyV2/accountSpending/TableContainer.jsx
  src/js/containers/agencyV2/awardSpending/SubAgencySummaryContainer.jsx
  src/js/containers/agencyV2/awardSpending/SubagencyTableContainer.jsx
  src/js/containers/covid19/WithDefCodes.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/helpers/agencyV2/BudgetCategoryHelper.js
  src/js/models/v2/agency/BaseAccountSpendingRow.js
  src/js/redux/actions/agencyV2/agencyV2Actions.js
  src/js/redux/reducers/agencyV2/agencyV2Reducer.js
  tests/components/agency/StatusOfFunds/IntroSection-test.jsx
  tests/components/agency/overview/FYSummary-test.jsx
  tests/components/agency/visualizations/ObligationsByAwardTypeTooltip-test.jsx
  tests/containers/account/WithLatestFy-test.js
  tests/containers/agencyV2/AgencyContainerV2-test.jsx
  tests/containers/agencyV2/WithAgencySlugs-test.jsx
  tests/containers/agencyV2/accountSpending/CountTabContainer-test.jsx
  tests/containers/agencyV2/accountSpending/TableContainer-test.jsx
  tests/containers/agencyV2/awardSpending/SubagencyTableContainer-test.jsx
  tests/helpers/agencyV2/BudgetCategoryHelper-test.js
  tests/models/agency/BaseAccountSpendingRow-test.js
  tests/redux/reducers/agencyV2/agencyV2Reducer-test.js
Labels: ENV Promotion

#2787 Sprint 142 Staging -> Master
  src/_scss/lib/bourbon/css3/_selection.scss
  src/_scss/pages/about/_section.scss
  src/_scss/pages/agencyV2/_tables.scss
  src/_scss/pages/agencyV2/index.scss
  src/_scss/pages/agencyV2/statusOfFunds/_drilldownSidebar.scss
  src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
  src/_scss/pages/agencyV2/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/covid19/_header.scss
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/_scss/pages/homepage/hero/_covid-hero.scss
  src/_scss/pages/homepage/homePage.scss
  src/js/apis/agencyV2.js
  src/js/components/about/Careers.jsx
  src/js/components/about/DataQuality.jsx
  src/js/components/about/Development.jsx
  src/js/components/about/MoreInfo.jsx
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/agencyV2/AgencyPage.jsx
  src/js/components/agencyV2/AgencySection.jsx
  src/js/components/agencyV2/accountSpending/AccountSpending.jsx
  src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx
  src/js/components/agencyV2/overview/AgencyOverview.jsx
  src/js/components/agencyV2/overview/FySummary.jsx
  src/js/components/agencyV2/statusOfFunds/DrilldownSidebar.jsx
  src/js/components/agencyV2/statusOfFunds/IntroSection.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx
  src/js/components/award/shared/federalAccounts/FederalAccountsTable.jsx
  src/js/components/covid19/PublicLawPicker.jsx
  src/js/components/homepage/CovidVaccineLink.jsx
  src/js/components/homepage/Homepage.jsx
  src/js/containers/agencyV2/AgencyContainerV2.jsx
  src/js/containers/agencyV2/WithAgencySlugs.jsx
  src/js/containers/agencyV2/accountSpending/CountTabContainer.jsx
  src/js/containers/agencyV2/accountSpending/TableContainer.jsx
  src/js/containers/agencyV2/awardSpending/SubAgencySummaryContainer.jsx
  src/js/containers/agencyV2/awardSpending/SubagencyTableContainer.jsx
  src/js/containers/covid19/WithDefCodes.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/helpers/agencyV2/BudgetCategoryHelper.js
  src/js/models/v2/agency/BaseAccountSpendingRow.js
  src/js/redux/actions/agencyV2/agencyV2Actions.js
  src/js/redux/reducers/agencyV2/agencyV2Reducer.js
  tests/components/agency/StatusOfFunds/IntroSection-test.jsx
  tests/components/agency/overview/FYSummary-test.jsx
  tests/components/agency/visualizations/ObligationsByAwardTypeTooltip-test.jsx
  tests/containers/account/WithLatestFy-test.js
  tests/containers/agencyV2/AgencyContainerV2-test.jsx
  tests/containers/agencyV2/WithAgencySlugs-test.jsx
  tests/containers/agencyV2/accountSpending/CountTabContainer-test.jsx
  tests/containers/agencyV2/accountSpending/TableContainer-test.jsx
  tests/containers/agencyV2/awardSpending/SubagencyTableContainer-test.jsx
  tests/helpers/agencyV2/BudgetCategoryHelper-test.js
  tests/models/agency/BaseAccountSpendingRow-test.js
  tests/redux/reducers/agencyV2/agencyV2Reducer-test.js
Labels: ENV Promotion

#2786 Down-merge to QAT: Hotfix DEV-8103 limit downloads
  src/js/components/search/header/NoDownloadHover.jsx
Labels: down merge

#2798 Change download max up to 100k
  src/js/components/search/header/NoDownloadHover.jsx
Labels: hotfix
