Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-05, with the labels that each got.

#2541 [bug-about-the-data] handle null for values on publications tab on current_total_budget_authority_amount.
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: warm-fix

#2542 Demote warmfix qat -> dev
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: down merge

#2546 Hotfix menu mapping in prod
  src/js/components/sharedComponents/header/NavBar.jsx
  src/js/components/sharedComponents/header/mobile/MobileNav.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: hotfix

#2547 Demote hotfix master -> qat
  src/js/components/sharedComponents/header/NavBar.jsx
  src/js/components/sharedComponents/header/mobile/MobileNav.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge

#2549 Qat -> Dev
  src/js/components/sharedComponents/header/NavBar.jsx
  src/js/components/sharedComponents/header/mobile/MobileNav.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge

#2559 COVID-19 Progress Chart Obligation Line Three Overlap
  src/js/components/covid19/amountsVisualization/AmountsVisualization.jsx
  src/js/components/covid19/amountsVisualization/amounts/remainingBalance/LinesAndText.jsx
  src/js/components/covid19/amountsVisualization/amounts/remainingBalance/RemainingBalance.jsx
  src/js/components/covid19/amountsVisualization/amounts/totalObligations/LineAndText.jsx
  src/js/components/covid19/amountsVisualization/amounts/totalObligations/TotalObligations.jsx
Labels: warm-fix

#2564 Demote warmfix qat -> dev
  src/js/components/covid19/amountsVisualization/AmountsVisualization.jsx
  src/js/components/covid19/amountsVisualization/amounts/remainingBalance/LinesAndText.jsx
  src/js/components/covid19/amountsVisualization/amounts/remainingBalance/RemainingBalance.jsx
  src/js/components/covid19/amountsVisualization/amounts/totalObligations/LineAndText.jsx
  src/js/components/covid19/amountsVisualization/amounts/totalObligations/TotalObligations.jsx
Labels: down merge

#2488 [DEV-7086] using isDynamicRenderer property on window to skip animation of total amount on home pg
  src/js/components/homepage/hero/TotalAmount.jsx
  src/js/helpers/browser.js
Labels: warm-fix

#2569 Down Merge: Disable COVID Home PG Animation & Agency v2 Covid Tooltip
  src/_scss/pages/agencyV2/overview/_overview.scss
  src/js/components/homepage/hero/TotalAmount.jsx
  src/js/helpers/browser.js
Labels: down merge

#2573 [DEV-6622] Agency w/ no DEFC was showing a 0
  src/js/components/agencyV2/overview/AgencyOverview.jsx
Labels: warm-fix

#2576 Qat -> Dev #2573
  src/js/components/agencyV2/overview/AgencyOverview.jsx
Labels: down merge

#2590 Dev-7396 COVID-19 Date Note uses Cached Submission Period Data
  src/js/components/covid19/DateNote.jsx
  src/js/helpers/accountHelper.js
Labels: hotfix

#2591 Demote hotfix master -> qat
  src/js/components/covid19/DateNote.jsx
  src/js/helpers/accountHelper.js
Labels: down merge

#2592 Qat -> Dev #2590
  src/js/components/covid19/DateNote.jsx
  src/js/helpers/accountHelper.js
Labels: down merge
