Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-08, with the labels that each got.

#2693 Qat -> Staging
  package-lock.json
  package.json
  src/_scss/pages/homepage/features/_featurePane.scss
  src/js/components/about/About.jsx
  src/js/components/about/DBInfo.jsx
  src/js/components/about/legal/common/LegalPage.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/account/Account.jsx
  src/js/components/account/InvalidAccount.jsx
  src/js/components/account/LoadingAccount.jsx
  src/js/components/accountLanding/AccountLandingPage.jsx
  src/js/components/agency/AgencyPage.jsx
  src/js/components/agencyLanding/AgencyLandingPage.jsx
  src/js/components/agencyV2/AgencyPage.jsx
  src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx
  src/js/components/agencyV2/visualizations/ObligationsByAwardType.jsx
  src/js/components/award/Award.jsx
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/covid19/Covid19Page.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/components/dataDictionary/DataDictionaryPage.jsx
  src/js/components/errorPage/ErrorPage.jsx
  src/js/components/explorer/ExplorerWrapperPage.jsx
  src/js/components/explorer/detail/visualization/table/TableRow.jsx
  src/js/components/homepage/Homepage.jsx
  src/js/components/homepage/features/PaneFeature.jsx
  src/js/components/keyword/KeywordPage.jsx
  src/js/components/recipient/RecipientPage.jsx
  src/js/components/recipientLanding/RecipientLandingPage.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/search/SearchSidebarSubmit.jsx
  src/js/components/search/filters/awardType/AwardType.jsx
  src/js/components/sharedComponents/Loading.jsx
  src/js/components/sharedComponents/PageWrapper.jsx
  src/js/components/sharedComponents/Subscribe.jsx
  src/js/components/sharedComponents/filterSidebar/SubmitHint.jsx
  src/js/components/state/StatePage.jsx
  src/js/components/stateLanding/StateLandingPage.jsx
  src/js/components/testStyles/TestStylePage.jsx
  src/js/containers/Footer.jsx
  src/js/containers/agencyV2/visualizations/ObligationsByAwardTypeContainer.jsx
  src/js/containers/homepage/CovidHighlights.jsx
  src/js/containers/search/SearchSidebarSubmitContainer.jsx
  src/js/containers/search/filters/AwardTypeContainer.jsx
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
  src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
  src/js/containers/search/filters/recipient/RecipientTypeContainer.jsx
  tests/components/search/SearchSideBarSubmit-test.jsx
  tests/containers/search/filters/recipientFilter/RecipientTypeContainer-test.jsx
Labels: ENV Promotion

#2694 Dev-7794 remove agency submission navigation links
  src/js/components/about/DataQuality.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: hotfix

#2695 Downmerge Dev-7794 (Agency Submission Nav Links) into Staging
  src/js/components/about/DataQuality.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge

#2696 Downmerge Dev 7794 (Agency Submission Nav Links) into QAT
  src/js/components/about/DataQuality.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge

#2698 Sprint 138 Production Promotion
  package-lock.json
  package.json
  src/_scss/pages/homepage/features/_featurePane.scss
  src/js/components/about/About.jsx
  src/js/components/about/DBInfo.jsx
  src/js/components/about/legal/common/LegalPage.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/account/Account.jsx
  src/js/components/account/InvalidAccount.jsx
  src/js/components/account/LoadingAccount.jsx
  src/js/components/accountLanding/AccountLandingPage.jsx
  src/js/components/agency/AgencyPage.jsx
  src/js/components/agencyLanding/AgencyLandingPage.jsx
  src/js/components/agencyV2/AgencyPage.jsx
  src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx
  src/js/components/agencyV2/visualizations/ObligationsByAwardType.jsx
  src/js/components/award/Award.jsx
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/covid19/Covid19Page.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/components/dataDictionary/DataDictionaryPage.jsx
  src/js/components/errorPage/ErrorPage.jsx
  src/js/components/explorer/ExplorerWrapperPage.jsx
  src/js/components/explorer/detail/visualization/table/TableRow.jsx
  src/js/components/homepage/Homepage.jsx
  src/js/components/homepage/features/PaneFeature.jsx
  src/js/components/keyword/KeywordPage.jsx
  src/js/components/recipient/RecipientPage.jsx
  src/js/components/recipientLanding/RecipientLandingPage.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/search/SearchSidebarSubmit.jsx
  src/js/components/search/filters/awardType/AwardType.jsx
  src/js/components/sharedComponents/Loading.jsx
  src/js/components/sharedComponents/PageWrapper.jsx
  src/js/components/sharedComponents/Subscribe.jsx
  src/js/components/sharedComponents/filterSidebar/SubmitHint.jsx
  src/js/components/state/StatePage.jsx
  src/js/components/stateLanding/StateLandingPage.jsx
  src/js/components/testStyles/TestStylePage.jsx
  src/js/containers/Footer.jsx
  src/js/containers/agencyV2/visualizations/ObligationsByAwardTypeContainer.jsx
  src/js/containers/homepage/CovidHighlights.jsx
  src/js/containers/search/SearchSidebarSubmitContainer.jsx
  src/js/containers/search/filters/AwardTypeContainer.jsx
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
  src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
  src/js/containers/search/filters/recipient/RecipientTypeContainer.jsx
  tests/components/search/SearchSideBarSubmit-test.jsx
  tests/containers/search/filters/recipientFilter/RecipientTypeContainer-test.jsx
Labels: ENV Promotion

#2706 Downmerge hotfix DEV-7851 into staging
  src/_scss/pages/bulkDownload/_databaseDownloadMessage.scss
  src/_scss/pages/bulkDownload/archive/_archiveTable.scss
  src/_scss/pages/bulkDownload/bulkDownloadPage.scss
  src/_scss/pages/bulkDownload/form/_agencyPicker.scss
  src/_scss/pages/modals/all.scss
  src/_scss/pages/modals/bulkDownload/downloadMessageModal.scss
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/bulkDownload/DatabaseDownload.jsx
  src/js/components/bulkDownload/archive/AwardDataArchiveContent.jsx
  src/js/components/bulkDownload/archive/DownloadMessageModal.jsx
  src/js/components/bulkDownload/archive/table/AwardDataArchiveTable.jsx
  src/js/components/bulkDownload/archive/table/TableRow.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge

#2709 Hotfix DEV-7852 re-enable downloads
  src/_scss/pages/bulkDownload/_databaseDownloadMessage.scss
  src/_scss/pages/bulkDownload/archive/_archiveTable.scss
  src/_scss/pages/bulkDownload/bulkDownloadPage.scss
  src/_scss/pages/modals/all.scss
  src/_scss/pages/modals/bulkDownload/downloadMessageModal.scss
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/bulkDownload/DatabaseDownload.jsx
  src/js/components/bulkDownload/archive/AwardDataArchiveContent.jsx
  src/js/components/bulkDownload/archive/DownloadMessageModal.jsx
  src/js/components/bulkDownload/archive/table/AwardDataArchiveTable.jsx
  src/js/components/bulkDownload/archive/table/TableRow.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: hotfix

#2711 Down merge DEV-7852 into QAT
  src/_scss/pages/bulkDownload/_databaseDownloadMessage.scss
  src/_scss/pages/bulkDownload/archive/_archiveTable.scss
  src/_scss/pages/bulkDownload/bulkDownloadPage.scss
  src/_scss/pages/modals/all.scss
  src/_scss/pages/modals/bulkDownload/downloadMessageModal.scss
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/bulkDownload/DatabaseDownload.jsx
  src/js/components/bulkDownload/archive/AwardDataArchiveContent.jsx
  src/js/components/bulkDownload/archive/DownloadMessageModal.jsx
  src/js/components/bulkDownload/archive/table/AwardDataArchiveTable.jsx
  src/js/components/bulkDownload/archive/table/TableRow.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge

#2710 Down merge DEV-7852 into Staging
  src/_scss/pages/bulkDownload/_databaseDownloadMessage.scss
  src/_scss/pages/bulkDownload/archive/_archiveTable.scss
  src/_scss/pages/bulkDownload/bulkDownloadPage.scss
  src/_scss/pages/modals/all.scss
  src/_scss/pages/modals/bulkDownload/downloadMessageModal.scss
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/bulkDownload/DatabaseDownload.jsx
  src/js/components/bulkDownload/archive/AwardDataArchiveContent.jsx
  src/js/components/bulkDownload/archive/DownloadMessageModal.jsx
  src/js/components/bulkDownload/archive/table/AwardDataArchiveTable.jsx
  src/js/components/bulkDownload/archive/table/TableRow.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge
