Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-04, with the labels that each got.

#2490 update link to DTM
  src/js/components/aboutTheData/AboutTheDataPage.jsx
Labels: warm-fix

#2493 Demote warmfix qat -> dev
  src/js/components/aboutTheData/AboutTheDataPage.jsx
Labels: down merge

#2497 Sprint 129 Production Deploy
  package-lock.json
  package.json
  src/_scss/components/_stickyTable.scss
  src/_scss/pages/aboutTheData/_agenciesPage.scss
  src/_scss/pages/aboutTheData/_agencyDetailsPage.scss
  src/_scss/pages/aboutTheData/_tableControls.scss
  src/_scss/pages/agencyV2/index.scss
  src/_scss/pages/covid19/_budgetCategoriesTable.scss
  src/_scss/pages/covid19/_tables.scss
  src/_scss/pages/covid19/_unlinkedData.scss
  src/_scss/pages/covid19/assistanceListing/_assistanceListing.scss
  src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/_scss/pages/explorer/detail/visualization/visualization.scss
  src/js/components/about/AboutContent.jsx
  src/js/components/about/Careers.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/account/Account.jsx
  src/js/components/account/SearchResults.jsx
  src/js/components/account/visualizations/sankey/SankeyVisualizationHorizontal.jsx
  src/js/components/account/visualizations/sankey/SankeyVisualizationVertical.jsx
  src/js/components/agency/visualizations/objectClass/MajorObjectClasses.jsx
  src/js/components/agency/visualizations/objectClass/MinorObjectClasses.jsx
  src/js/components/agencyV2/AgencySection.jsx
  src/js/components/bulkDownload/awards/AwardDataContent.jsx
  src/js/components/covid19/Covid19Section.jsx
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
  src/js/components/sharedComponents/Note.jsx
  src/js/containers/Footer.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/helpers/covid19.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
  src/js/helpers/aboutTheDataHelper.js
  src/js/models/account/FederalAccount.js
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/components/about/AboutContent-test.jsx
  tests/containers/aboutTheData/mockData.js
  tests/helpers/aboutTheDataHelper-test.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: ENV Promotion

#2502 [DEV-6706] Account Download DEFC User Selection validation logic update
  src/js/components/bulkDownload/accounts/UserSelections.jsx
  tests/components/bulkDownload/accounts/UserSelections-test.jsx
Labels: warm-fix

#2505 Down Merge follow up warmfixes: DEV-6706 & DEV-6889
  src/_scss/components/_header.scss
  src/_scss/components/_picker.scss
  src/_scss/pages/aboutTheData/aboutTheData.scss
  src/_scss/pages/covid19/index.scss
  src/js/components/about/About.jsx
  src/js/components/about/legal/common/LegalPage.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/account/AccountHeader.jsx
  src/js/components/accountLanding/AccountLandingPage.jsx
  src/js/components/agency/AgencyPage.jsx
  src/js/components/agencyLanding/AgencyLandingPage.jsx
  src/js/components/agencyV2/AgencyPage.jsx
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/bulkDownload/accounts/UserSelections.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/components/explorer/ExplorerWrapperPage.jsx
  src/js/components/keyword/KeywordPage.jsx
  src/js/components/recipient/RecipientPage.jsx
  src/js/components/recipientLanding/RecipientLandingPage.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/sharedComponents/Loading.jsx
  src/js/components/state/StatePage.jsx
  src/js/components/stateLanding/StateLandingPage.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/helpers/socialShare.jsx
  tests/components/bulkDownload/accounts/UserSelections-test.jsx
Labels: down merge

#2516 [BUG] COVID Profile Page Mobile responsiveness
  src/_scss/pages/covid19/index.scss
Labels: hotfix

#2518 [DEV-7167] fix broken link
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
Labels: warm-fix

#2514 Dev-7180 Columns Removed for 2017, 2018, 2019, and 2020
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: warm-fix

#2522 Demote hotfix & warmfixes qat -> dev
  src/_scss/pages/covid19/index.scss
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: down merge

#2525 Dev-7178 Handle Null Value for TAS, Difference, Unlinked Contract & FA
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/models/v2/aboutTheData/CoreReportingRow.js
Labels: warm-fix

#2528 7058 copy updates
  src/js/components/aboutTheData/componentMapping/tooltipContentMapping.jsx
Labels: warm-fix

#2533 Dev-7178 Handle Null Values for Missing TAS, Obligation Difference, & Unlinked Columns
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/models/v2/aboutTheData/CoreReportingRow.js
  tests/models/aboutTheData/CoreReportingRow-test.js
Labels: warm-fix

#2535 Dev-7180 remove fake periods added
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: warm-fix

#2532 [DEV-6691] release agency stats pg
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/components/covid19/AwardQuestions.jsx
  src/js/components/covid19/Heading.jsx
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/sharedComponents/GlossaryLink.jsx
  src/js/components/sharedComponents/header/NavBar.jsx
  src/js/components/sharedComponents/header/mobile/MobileNav.jsx
  src/js/containers/Footer.jsx
  src/js/containers/glossary/GlossaryListener.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/helpers/glossaryHelper.js
  src/js/helpers/metaTagHelper.js
  tests/helpers/glossaryHelper-test.js
Labels: warm-fix

#2539 Demote warmfixes qat -> dev (w/ conflicts resolved)
  scripts/sitemaps/pages.js
  src/_scss/pages/bulkDownload/bulkDownloadPage.scss
  src/_scss/pages/bulkDownload/dictionary/dictionary.scss
  src/_scss/pages/dataDictionary/_dictionaryTable.scss
  src/_scss/pages/dataDictionary/_header.scss
  src/_scss/pages/dataDictionary/_searchBar.scss
  src/_scss/pages/dataDictionary/_sorter.scss
  src/_scss/pages/dataDictionary/dataDictionaryPage.scss
  src/js/apis/dataDictionary.js
  src/js/components/about/MoreInfo.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/components/aboutTheData/componentMapping/tooltipContentMapping.jsx
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/covid19/AwardQuestions.jsx
  src/js/components/covid19/Heading.jsx
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/dataDictionary/DataDictionary.jsx
  src/js/components/dataDictionary/DataDictionaryPage.jsx
  src/js/components/dataDictionary/DataDictionarySearchBar.jsx
  src/js/components/dataDictionary/table/DataDictionaryTable.jsx
  src/js/components/dataDictionary/table/DataDictionaryTableSorter.jsx
  src/js/components/sharedComponents/GlossaryLink.jsx
  src/js/components/sharedComponents/header/NavBar.jsx
  src/js/components/sharedComponents/header/mobile/MobileNav.jsx
  src/js/containers/Footer.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/containers/dataDictionary/DataDictionaryContainer.jsx
  src/js/containers/glossary/GlossaryListener.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/dataMapping/navigation/menuOptions.jsx
  src/js/helpers/bulkDownloadHelper.js
  src/js/helpers/glossaryHelper.js
  src/js/helpers/metaTagHelper.js
  src/js/models/v2/aboutTheData/BaseReportingPeriodRow.js
  src/js/models/v2/aboutTheData/CoreReportingRow.js
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/containers/aboutTheData/mockData.js
  tests/containers/bulkDownload/dictionary/DataDictionaryContainer-test.jsx
  tests/containers/bulkDownload/mockBulkDownloadHelper.js
  tests/containers/bulkDownload/mockData.js
  tests/containers/dataDictionary/DataDictionaryContainer-test.jsx
  tests/helpers/glossaryHelper-test.js
  tests/mockApi/responses/dataDictionary.js
  tests/models/aboutTheData/BaseReportingPeriodRow-test.js
  tests/models/aboutTheData/CoreReportingRow-test.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
  tests/testResources/mockApiHelper.js
Labels: down merge
