Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-12, with the labels that each got.

#2807 Demote hotfixes to QAT
  src/js/components/search/header/NoDownloadHover.jsx
  src/js/containers/covid19/SummaryInsightsContainer.jsx
  src/js/containers/covid19/recipient/RecipientTableContainer.jsx
  src/js/helpers/index.js
  tests/containers/covid19/SummaryInsightsContainer-test.jsx
  tests/containers/covid19/recipient/RecipientTableContainer-test.jsx
Labels: down merge

#2808 Increase download limit to 250k
  src/js/components/search/header/NoDownloadHover.jsx
Labels: hotfix

#2809 Downmerge Master -> Staging
  src/js/components/search/header/NoDownloadHover.jsx
Labels: down merge

#2812 Downmerge Staging -> QAT
  src/js/components/search/header/NoDownloadHover.jsx
Labels: down merge

#2813 Sprint 143 Staging Deploy
  package-lock.json
  package.json
  scripts/buildRedirectConfig.js
  src/_scss/pages/agencyV2/overview/_overview.scss
  src/_scss/pages/agencyV2/statusOfFunds/_drilldownSidebar.scss
  src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
  src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
  src/js/GlobalConstants.js
  src/js/components/agencyV2/statusOfFunds/DrilldownSidebar.jsx
  src/js/components/agencyV2/statusOfFunds/DrilldownSidebarLevel.jsx
  src/js/components/agencyV2/statusOfFunds/IntroSection.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFundsNotes.jsx
  src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx
  src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx
  src/js/components/recipient/topFive/TopFiveRow.jsx
  src/js/components/state/topFive/TopFiveRow.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/recipient/RecipientTableContainer.jsx
  src/js/containers/recipient/topFive/TopFiveContainer.jsx
  src/js/containers/state/topFive/TopFiveContainer.jsx
  src/js/dataMapping/agencyV2/agencyIdsToSlugs.js
  src/js/helpers/moneyFormatter.js
  src/js/models/v2/agency/BaseAgencyBudgetaryResources.js
  src/js/models/v2/agency/BaseStatusOfFundsLevel.js
  src/js/models/v2/state/BaseStateCategoryResult.jsx
  src/js/propTypes/index.js
  src/js/redux/actions/agencyV2/agencyV2Actions.js
  src/js/redux/reducers/agencyV2/agencyV2Reducer.js
  src/js/registerIcons.js
  tests/components/agency/StatusOfFunds/DrilldownSidebar-test.jsx
  tests/components/agency/StatusOfFunds/DrilldownSidebarLevel-test.jsx
  tests/components/agency/StatusOfFunds/IntroSection-test.jsx
  tests/components/agency/visualizations/StatusOfFundsChart-test.jsx
  tests/helpers/moneyFormatter-test.js
  tests/models/agency/BaseAgencyBudgetaryResources-test.js
  tests/models/agency/BaseStatusOfFundsLevel-test.js
  tests/models/state/BaseStateCategoryResult-test.js
  tests/models/state/mockStateApi.js
  tests/redux/reducers/agencyV2/agencyV2Reducer-test.js
Labels: ENV Promotion

#2777 dev 7955 add TOP page
  src/_scss/pages/covid19/opportunityProject.scss
  src/img/opportunity-project-logo.png
  src/img/opportunity-project-map.png
  src/img/opportunity-project-map.webp
  src/js/components/covid19/OpportunityProjectPage.jsx
  src/js/components/covid19/OtherResources.jsx
  src/js/components/sharedComponents/PageWrapper.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/helpers/metaTagHelper.js
Labels: hotfix

#2819 Demote hotfix master -> staging
  src/_scss/pages/covid19/opportunityProject.scss
  src/img/opportunity-project-logo.png
  src/img/opportunity-project-map.png
  src/img/opportunity-project-map.webp
  src/js/components/covid19/OpportunityProjectPage.jsx
  src/js/components/covid19/OtherResources.jsx
  src/js/components/sharedComponents/PageWrapper.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/helpers/metaTagHelper.js
Labels: down merge

#2821 Demote hotfix staging -> qat
  src/_scss/pages/covid19/opportunityProject.scss
  src/img/opportunity-project-logo.png
  src/img/opportunity-project-map.png
  src/img/opportunity-project-map.webp
  src/js/components/covid19/OpportunityProjectPage.jsx
  src/js/components/covid19/OtherResources.jsx
  src/js/components/sharedComponents/PageWrapper.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/helpers/metaTagHelper.js
Labels: down merge

#2822 Sprint 143 deploy staging -> master
  package-lock.json
  package.json
  scripts/buildRedirectConfig.js
  src/_scss/pages/agencyV2/_awardSpendingNotes.scss
  src/_scss/pages/agencyV2/index.scss
  src/_scss/pages/agencyV2/overview/_overview.scss
  src/_scss/pages/agencyV2/statusOfFunds/_drilldownSidebar.scss
  src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
  src/_scss/pages/agencyV2/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/agencyV2/statusOfFunds/_statusOfFundsNotes.scss
  src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
  src/js/GlobalConstants.js
  src/js/components/agencyV2/awardSpending/AwardSpendingNotes.jsx
  src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx
  src/js/components/agencyV2/statusOfFunds/DrilldownSidebar.jsx
  src/js/components/agencyV2/statusOfFunds/DrilldownSidebarLevel.jsx
  src/js/components/agencyV2/statusOfFunds/IntroSection.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFundsNotes.jsx
  src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx
  src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx
  src/js/components/covid19/amountsVisualization/AmountsVisualization.jsx
  src/js/components/explorer/detail/UnreportedErrorScreen.jsx
  src/js/components/recipient/topFive/TopFiveRow.jsx
  src/js/components/state/topFive/TopFiveRow.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
  src/js/containers/covid19/recipient/RecipientTableContainer.jsx
  src/js/containers/recipient/topFive/TopFiveContainer.jsx
  src/js/containers/state/topFive/TopFiveContainer.jsx
  src/js/dataMapping/agencyV2/agencyIdsToSlugs.js
  src/js/helpers/moneyFormatter.js
  src/js/models/v2/agency/BaseAgencyBudgetaryResources.js
  src/js/models/v2/agency/BaseStatusOfFundsLevel.js
  src/js/models/v2/state/BaseStateCategoryResult.jsx
  src/js/propTypes/index.js
  src/js/redux/actions/agencyV2/agencyV2Actions.js
  src/js/redux/reducers/agencyV2/agencyV2Reducer.js
  src/js/registerIcons.js
  tests/components/agency/StatusOfFunds/DrilldownSidebar-test.jsx
  tests/components/agency/StatusOfFunds/DrilldownSidebarLevel-test.jsx
  tests/components/agency/StatusOfFunds/IntroSection-test.jsx
  tests/components/agency/visualizations/StatusOfFundsChart-test.jsx
  tests/helpers/moneyFormatter-test.js
  tests/models/agency/BaseAgencyBudgetaryResources-test.js
  tests/models/agency/BaseStatusOfFundsLevel-test.js
  tests/models/state/BaseStateCategoryResult-test.js
  tests/models/state/mockStateApi.js
  tests/redux/reducers/agencyV2/agencyV2Reducer-test.js
Labels: ENV Promotion
