Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-01, with the labels that each got.

#2292 Hotfix DEV-6558, DEV-6576, DEV-6577 migration banners
  package-lock.json
  package.json
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  tests/components/sharedComponents/InfoBanner-test.jsx
Labels: hotfix

#2291 Hotfix DEV-6575 map error
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/helpers/mapHelper.js
  tests/helpers/mapHelper-test.js
Labels: hotfix

#2296 Resolve master -> qat conflict
  package-lock.json
  package.json
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/helpers/mapHelper.js
  tests/components/sharedComponents/InfoBanner-test.jsx
  tests/helpers/mapHelper-test.js
Labels: down merge

#2297 Qat -> Dev
  package-lock.json
  package.json
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/helpers/mapHelper.js
  tests/components/sharedComponents/InfoBanner-test.jsx
  tests/helpers/mapHelper-test.js
Labels: down merge

#2301 upgrades axios to 21.1 to remove security vulnerability of SSRF
  package-lock.json
  package.json
Labels: hotfix

#2300 Dev-6484 IDV Additional Details Text Update
  src/js/dataMapping/award/additionalDetailsIdv.js
Labels: hotfix

#2304 Master --> QAT (#2301, #2300, #2298)
  package-lock.json
  package.json
  src/js/components/about/AboutContent.jsx
  src/js/components/about/DataQuality.jsx
  src/js/components/about/DataSources.jsx
  src/js/dataMapping/award/additionalDetailsIdv.js
Labels: down merge

#2305 Qat -> Dev
  package-lock.json
  package.json
  src/js/components/about/AboutContent.jsx
  src/js/components/about/DataQuality.jsx
  src/js/components/about/DataSources.jsx
  src/js/dataMapping/award/additionalDetailsIdv.js
Labels: down merge

#2315 [DEV-6584] Updating PDF and obsolete copy content
  src/data/data-limitations.pdf
  src/js/containers/covid19/recipient/RecipientContainer.jsx
Labels: hotfix

#2310 [DEV-6536] Publication Dates Table API Integration
  src/_scss/pages/aboutTheData/agenciesPage.scss
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/helpers/aboutTheDataHelper.js
Labels: do not merge

#2316 Master -> QAT
  src/data/data-limitations.pdf
  src/js/containers/covid19/recipient/RecipientContainer.jsx
Labels: down merge

#2319 update legal content side bar links
  src/js/components/about/legal/common/LegalContent.jsx
Labels: warm-fix

#2320 Demote hotfix & warmfix qat -> dev
  package-lock.json
  package.json
  src/data/data-limitations.pdf
  src/js/components/about/legal/common/LegalContent.jsx
  src/js/containers/covid19/recipient/RecipientContainer.jsx
Labels: down merge

#2323 Sprint 123 Promotion to Production
  package-lock.json
  package.json
  src/_scss/pages/aboutTheData/agenciesPage.scss
  src/_scss/pages/aboutTheData/agencyDetailsPage.scss
  src/js/components/about/legal/common/LegalContent.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/TimeFilters.jsx
  src/js/components/aboutTheData/dataMapping/tooltipContentMapping.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/containers/search/SearchContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/helpers/searchHelper.js
  src/js/models/v2/aboutTheData/BaseAgencyRow.js
  tests/components/aboutTheData/AboutTheDataPage-test.jsx
  tests/components/aboutTheData/TimeFilters-test.jsx
  tests/containers/search/SearchContainer-test.jsx
  tests/containers/search/filters/searchHelper.js
  tests/containers/search/mockSearchHashes.js
  tests/containers/search/table/ResultsTableContainer-test.jsx
  tests/helpers/searchHelper-test.js
  tests/models/aboutTheData/BaseAgencyRow-test.js
Labels: ENV Promotion

#2326 DEV-6577 Hotfix reset info banner
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  tests/components/sharedComponents/InfoBanner-test.jsx
Labels: hotfix

#2322 [DEV-6609] Ensuring Fiscal Year for Account Data is Accurate in drop downs, tables, and Network Calls
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/TimeFilters.jsx
  src/js/components/account/Account.jsx
  src/js/components/agency/AgencyContent.jsx
  src/js/components/covid19/DateNote.jsx
  src/js/components/sharedComponents/QuarterPickerWithFY.jsx
  src/js/components/sharedComponents/pickers/FYPicker.jsx
  src/js/containers/account/AccountContainer.jsx
  src/js/containers/account/WithLatestFy.jsx
  src/js/containers/account/filters/AccountTimePeriodContainer.jsx
  src/js/containers/accountLanding/AccountLandingContainer.jsx
  src/js/containers/agency/visualizations/ObligatedContainer.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
  src/js/helpers/accountHelper.js
  src/js/propTypes/index.js
  src/js/redux/actions/account/accountActions.js
  src/js/redux/reducers/account/accountReducer.js
  tests/components/aboutTheData/AboutTheDataPage-test.jsx
  tests/components/aboutTheData/TimeFilters-test.jsx
  tests/containers/account/AccountContainer-test.jsx
  tests/containers/account/filters/AccountTimePeriodContainer-test.jsx
  tests/containers/accountLanding/AccountLandingContainer-test.jsx
  tests/containers/covid19/homepage/CovidHighlights-test.jsx
  tests/redux/reducers/account/accountReducer-test.js
Labels: hotfix

#2324 [DEV-6342] cleaning up broken styles on homepage tooltip
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/pages/covid19/_covidTooltip.scss
  src/_scss/pages/covid19/index.scss
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
Labels: hotfix

#2328 Demote hotfixes master -> qat
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/pages/covid19/_covidTooltip.scss
  src/_scss/pages/covid19/index.scss
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/TimeFilters.jsx
  src/js/components/account/Account.jsx
  src/js/components/agency/AgencyContent.jsx
  src/js/components/covid19/DateNote.jsx
  src/js/components/sharedComponents/QuarterPickerWithFY.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/components/sharedComponents/pickers/FYPicker.jsx
  src/js/containers/account/AccountContainer.jsx
  src/js/containers/account/WithLatestFy.jsx
  src/js/containers/account/filters/AccountTimePeriodContainer.jsx
  src/js/containers/accountLanding/AccountLandingContainer.jsx
  src/js/containers/agency/visualizations/ObligatedContainer.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
  src/js/helpers/accountHelper.js
  src/js/propTypes/index.js
  src/js/redux/actions/account/accountActions.js
  src/js/redux/reducers/account/accountReducer.js
  tests/components/aboutTheData/AboutTheDataPage-test.jsx
  tests/components/aboutTheData/TimeFilters-test.jsx
  tests/components/sharedComponents/InfoBanner-test.jsx
  tests/containers/account/AccountContainer-test.jsx
  tests/containers/account/filters/AccountTimePeriodContainer-test.jsx
  tests/containers/accountLanding/AccountLandingContainer-test.jsx
  tests/containers/covid19/homepage/CovidHighlights-test.jsx
  tests/redux/reducers/account/accountReducer-test.js
Labels: down merge

#2331 Down merge hotfixes: QAT >> DEV
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/pages/covid19/_covidTooltip.scss
  src/_scss/pages/covid19/index.scss
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/TimeFilters.jsx
  src/js/components/account/Account.jsx
  src/js/components/agency/AgencyContent.jsx
  src/js/components/covid19/DateNote.jsx
  src/js/components/sharedComponents/QuarterPickerWithFY.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/components/sharedComponents/pickers/FYPicker.jsx
  src/js/containers/account/AccountContainer.jsx
  src/js/containers/account/WithLatestFy.jsx
  src/js/containers/account/filters/AccountTimePeriodContainer.jsx
  src/js/containers/accountLanding/AccountLandingContainer.jsx
  src/js/containers/agency/visualizations/ObligatedContainer.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/covid19/homepage/CovidHighlights.jsx
  src/js/helpers/accountHelper.js
  src/js/propTypes/index.js
  src/js/redux/actions/account/accountActions.js
  src/js/redux/reducers/account/accountReducer.js
  tests/components/aboutTheData/AboutTheDataPage-test.jsx
  tests/components/aboutTheData/TimeFilters-test.jsx
  tests/components/sharedComponents/InfoBanner-test.jsx
  tests/containers/account/AccountContainer-test.jsx
  tests/containers/account/filters/AccountTimePeriodContainer-test.jsx
  tests/containers/accountLanding/AccountLandingContainer-test.jsx
  tests/containers/covid19/homepage/CovidHighlights-test.jsx
  tests/redux/reducers/account/accountReducer-test.js
Labels: down merge

#2327 Sprint 124 DEV >>> QAT
  Dockerfile
  react-testing-library.md
  scripts/sitemaps/package-lock.json
  scripts/sitemaps/package.json
  src/_scss/pages/aboutTheData/_actionCell.scss
  src/_scss/pages/aboutTheData/agenciesPage.scss
  src/_scss/pages/aboutTheData/agencyDetailsPage.scss
  src/js/components/aboutTheData/AboutTheDataModal.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/components/aboutTheData/DrilldownCell.jsx
  src/js/components/aboutTheData/TimeFilters.jsx
  src/js/components/covid19/DataSourcesAndMethodology.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/containers/aboutTheData/modals/MissingAccountBalanceContainer.jsx
  src/js/containers/aboutTheData/modals/PublicationDatesContainer.jsx
  src/js/containers/aboutTheData/modals/ReportingDifferencesContainer.jsx
  src/js/dataMapping/aboutTheData/modals.js
  src/js/helpers/aboutTheDataHelper.js
  src/js/helpers/agencyV2Helper.js
  src/js/helpers/pageAndSortHelper.js
  src/js/models/v2/aboutTheData/BaseReportingPeriodRow.js
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  src/js/models/v2/aboutTheData/ReportingOverviewRow.js
  src/js/models/v2/agencyV2/BaseAgencyOverview.js
  src/js/redux/actions/aboutTheData/index.js
  src/js/redux/reducers/aboutTheData/index.js
  tests/components/aboutTheData/AboutTheDataModal-test.jsx
  tests/components/aboutTheData/AboutTheDataPage-test.jsx
  tests/components/aboutTheData/TimeFilters-test.jsx
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/containers/aboutTheData/PublicationDatesContainer-test.jsx
  tests/containers/aboutTheData/ReportingDifferencesContainer-test.jsx
  tests/helpers/aboutTheDataHelper-test.js
  tests/helpers/accountHelper-test.js
  tests/helpers/pageAndSortHelper-test.js
  tests/mockData.js
  tests/mockData/helpers/aboutTheDataHelper.js
  tests/models/aboutTheData/BaseReportingPeriodRow-test.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
  tests/models/aboutTheData/ReportingOverviewRow-test.js
  tests/models/agency/BaseAgencyOverview-test.js
  tests/redux/reducers/aboutTheData/index-test.js
Labels: ENV Promotion

#2329 Dev-6533 CSS Changes After Demo Reviewal
  src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
  src/js/containers/aboutTheData/modals/ReportingDifferencesContainer.jsx
Labels: warm-fix

#2337 Bump DTUI 1.3.6
  package-lock.json
  package.json
Labels: warm-fix

#2336 Promoting 3 PRs pushed to DEV that should've been warm fixes
  README.md
  package-lock.json
  package.json
  src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/containers/aboutTheData/modals/ReportingDifferencesContainer.jsx
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
Labels: do not merge, warm-fix

#2344 [DEV-6536] Period 1 and Period 2 are combined, actually
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: warm-fix

#2348 [DEV-6536] Agency Details Page Drill down and Updating P07 to be under Q3
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
Labels: warm-fix

#2347 Down Merge QAT (w/ conflicts resolved)
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: do not merge, down merge

#2352 [DEV-6449] refactoring logic for fetching new data & custom hook "usePagination"
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/helpers/aboutTheDataHelper.js
Labels: warm-fix

#2354 Demote warmfix qat -> dev
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/helpers/aboutTheDataHelper.js
Labels: down merge

#2356 Sprint 124 QAT >>> Master
  Dockerfile
  README.md
  package-lock.json
  package.json
  react-testing-library.md
  scripts/sitemaps/package-lock.json
  scripts/sitemaps/package.json
  src/_scss/pages/aboutTheData/_actionCell.scss
  src/_scss/pages/aboutTheData/agenciesPage.scss
  src/_scss/pages/aboutTheData/agencyDetailsPage.scss
  src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
  src/js/components/aboutTheData/AboutTheDataModal.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/components/aboutTheData/DrilldownCell.jsx
  src/js/components/aboutTheData/TimeFilters.jsx
  src/js/components/covid19/DataSourcesAndMethodology.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/containers/aboutTheData/modals/MissingAccountBalanceContainer.jsx
  src/js/containers/aboutTheData/modals/PublicationDatesContainer.jsx
  src/js/containers/aboutTheData/modals/ReportingDifferencesContainer.jsx
  src/js/dataMapping/aboutTheData/modals.js
  src/js/helpers/aboutTheDataHelper.js
  src/js/helpers/agencyV2Helper.js
  src/js/helpers/pageAndSortHelper.js
  src/js/models/v2/aboutTheData/BaseReportingPeriodRow.js
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  src/js/models/v2/aboutTheData/ReportingOverviewRow.js
  src/js/models/v2/agencyV2/BaseAgencyOverview.js
  src/js/redux/actions/aboutTheData/index.js
  src/js/redux/reducers/aboutTheData/index.js
  tests/components/aboutTheData/AboutTheDataModal-test.jsx
  tests/components/aboutTheData/AboutTheDataPage-test.jsx
  tests/components/aboutTheData/TimeFilters-test.jsx
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/containers/aboutTheData/PublicationDatesContainer-test.jsx
  tests/containers/aboutTheData/ReportingDifferencesContainer-test.jsx
  tests/helpers/aboutTheDataHelper-test.js
  tests/helpers/accountHelper-test.js
  tests/helpers/pageAndSortHelper-test.js
  tests/mockData.js
  tests/mockData/helpers/aboutTheDataHelper.js
  tests/models/aboutTheData/BaseReportingPeriodRow-test.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
  tests/models/aboutTheData/ReportingOverviewRow-test.js
  tests/models/agency/BaseAgencyOverview-test.js
  tests/redux/reducers/aboutTheData/index-test.js
Labels: ENV Promotion

#2363 Promote demo feedback fixes dev -> qat
  src/js/containers/Footer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: ENV Promotion
