Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-03, with the labels that each got.

#2415 [DEV-6951] Handling falsy values from API for data that represents dollar amounts:
  src/js/helpers/moneyFormatter.js
  src/js/models/v2/aboutTheData/CoreReportingRow.js
  tests/helpers/moneyFormatter-test.js
  tests/models/aboutTheData/CoreReportingRow-test.js
Labels: warm-fix

#2422 [DEV-6749] Copy Edits to DS&M PG
  src/_scss/pages/data-sources/index.scss
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Labels: warm-fix

#2427 3/4/2021 Demo from Staging: About the Data Sprint 128 Warmfixes
  src/_scss/pages/data-sources/index.scss
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/helpers/moneyFormatter.js
  src/js/helpers/stickyHeaderHelper.js
  src/js/models/v2/aboutTheData/CoreReportingRow.js
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/helpers/moneyFormatter-test.js
  tests/models/aboutTheData/CoreReportingRow-test.js
Labels: ENV Promotion

#2434 Down Merge: QAT --> DEV (Sprint 128 Warmfixes and Hotfix to COVID DS&M)
  src/_scss/pages/data-sources/index.scss
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/helpers/moneyFormatter.js
  src/js/helpers/stickyHeaderHelper.js
  src/js/models/v2/aboutTheData/CoreReportingRow.js
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/helpers/moneyFormatter-test.js
  tests/models/aboutTheData/CoreReportingRow-test.js
Labels: down merge

#2437 Warmfix COVID Data Sources & Methodology copy
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Labels: warm-fix

#2439 Demote warmfix qat -> dev
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Labels: down merge

#2442 Promote warmfix qat -> staging
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Labels: ENV Promotion

#2446 Down Merge NPM Audit Fix: Staging. --> QAT
  package-lock.json
Labels: down merge

#2445 Sprint 128 Promotion: DEV --> QAT
  package-lock.json
  package.json
  src/_scss/pages/about/_section.scss
  src/_scss/pages/aboutTheData/_tableControls.scss
  src/_scss/pages/agencyV2/_sidebar.scss
  src/_scss/pages/agencyV2/_tables.scss
  src/_scss/pages/agencyV2/_tabs.scss
  src/_scss/pages/agencyV2/index.scss
  src/_scss/pages/covid19/_overviewData.scss
  src/_scss/pages/covid19/index.scss
  src/js/components/about/AboutContent.jsx
  src/js/components/about/DataQuality.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/TimeFilters.jsx
  src/js/components/agencyV2/AgencyPage.jsx
  src/js/components/agencyV2/AgencySection.jsx
  src/js/components/agencyV2/CountTab.jsx
  src/js/components/agencyV2/accountSpending/AccountSpending.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/covid19/recipient/SpendingByRecipient.jsx
  src/js/components/sharedComponents/QuarterPickerWithFY.jsx
  src/js/components/sharedComponents/sidebar/Sidebar.jsx
  src/js/components/sharedComponents/sidebar/SidebarLink.jsx
  src/js/containers/account/WithLatestFy.jsx
  src/js/containers/agency/v2/AgencyContainerV2.jsx
  src/js/containers/agencyV2/AgencyContainerV2.jsx
  src/js/containers/agencyV2/accountSpending/CountTabContainer.jsx
  src/js/containers/agencyV2/accountSpending/TableContainer.jsx
  src/js/containers/covid19/recipient/RecipientContainer.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/helpers/aboutTheDataHelper.js
  src/js/helpers/moneyFormatter.js
  src/js/helpers/queryParams.js
  src/js/models/v2/aboutTheData/BaseAgencyRow.js
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/components/about/AboutContent-test.jsx
  tests/components/about/DataQuality-test.jsx
  tests/components/aboutTheData/AboutTheDataPage-test.jsx
  tests/components/aboutTheData/TimeFilters-test.jsx
  tests/components/covid19/DataSourcesAndMethodologiesPage-test.jsx
  tests/containers/account/WithLatestFy-test.js
  tests/containers/agencyV2/AgencyContainerV2-test.jsx
  tests/helpers/moneyFormatter-test.js
  tests/helpers/queryParams-test.js
Labels: ENV Promotion

#2444 Dev-6956 Update Bulk Download Sidebar Links
  src/js/components/bulkDownload/sidebar/BulkDownloadSidebar.jsx
  src/js/components/bulkDownload/sidebar/SidebarButton.jsx
Labels: warm-fix

#2450 Demote warmfixes qat -> dev
  src/_scss/pages/aboutTheData/aboutTheData.scss
  src/js/components/aboutTheData/AboutTheDataModal.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/components/aboutTheData/TimeFilters.jsx
  src/js/components/aboutTheData/componentMapping/agencyNotes.jsx
  src/js/components/aboutTheData/componentMapping/modalContentMapping.jsx
  src/js/components/aboutTheData/componentMapping/tooltipContentMapping.jsx
  src/js/components/bulkDownload/sidebar/BulkDownloadSidebar.jsx
  src/js/components/bulkDownload/sidebar/SidebarButton.jsx
  src/js/components/sharedComponents/Note.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/dataMapping/aboutTheData/periodToQuarterMapping.js
  src/js/dataMapping/aboutTheData/timeFilters.js
  src/js/helpers/aboutTheDataHelper.js
  tests/models/agency/BaseAgencyOverview-test.js
Labels: down merge

#2421 [DEV-6937] Changes from SEO Audit pt I
  scripts/sitemaps/buildSitemap.js
  src/js/components/award/shared/overview/Recipient.jsx
  src/js/components/recipient/RecipientMultiParentCollapse.jsx
  src/js/components/sharedComponents/metaTags/MetaTags.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
  src/js/helpers/metaTagHelper.js
  tests/containers/covid19/SpendingByRecipientContainer-test.jsx
  tests/helpers/aboutTheDataHelper-test.js
  tests/helpers/metaTagHelper-test.js
Labels: warm-fix

#2454 Dynamic Renderer Release + Minor Copy Updates to COVID DS&M [DEV-6973]
  scripts/sitemaps/buildSitemap.js
  src/js/components/award/shared/overview/Recipient.jsx
  src/js/components/recipient/RecipientMultiParentCollapse.jsx
  src/js/components/sharedComponents/metaTags/MetaTags.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
  src/js/helpers/metaTagHelper.js
  tests/containers/covid19/SpendingByRecipientContainer-test.jsx
  tests/helpers/aboutTheDataHelper-test.js
  tests/helpers/metaTagHelper-test.js
Labels: do not merge

#2456 Demote master -> qat
  scripts/sitemaps/buildSitemap.js
  src/js/components/award/shared/overview/Recipient.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/components/recipient/RecipientMultiParentCollapse.jsx
  src/js/components/sharedComponents/metaTags/MetaTags.jsx
  src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
  src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
  src/js/helpers/metaTagHelper.js
  tests/containers/covid19/SpendingByRecipientContainer-test.jsx
  tests/helpers/aboutTheDataHelper-test.js
  tests/helpers/metaTagHelper-test.js
Labels: down merge

#2453 [DEV-4521] remove hard coded FY in agency v2 table
  src/js/components/agencyV2/accountSpending/AccountSpending.jsx
  src/js/containers/agencyV2/accountSpending/CountTabContainer.jsx
  src/js/containers/agencyV2/accountSpending/TableContainer.jsx
  tests/components/agency/AccountSpending-test.jsx
Labels: warm-fix

#2467 Down Merge Warmfix to QAT #2453
  src/js/components/agencyV2/accountSpending/AccountSpending.jsx
  src/js/containers/agencyV2/accountSpending/CountTabContainer.jsx
  src/js/containers/agencyV2/accountSpending/TableContainer.jsx
  tests/components/agency/AccountSpending-test.jsx
Labels: down merge

#2471 Sprint 129 Promotion: DEV --> QAT
  package-lock.json
  package.json
  src/_scss/components/_stickyTable.scss
  src/_scss/pages/aboutTheData/_agenciesPage.scss
  src/_scss/pages/aboutTheData/_agencyDetailsPage.scss
  src/_scss/pages/agencyV2/index.scss
  src/_scss/pages/covid19/_budgetCategoriesTable.scss
  src/_scss/pages/covid19/_tables.scss
  src/_scss/pages/covid19/_unlinkedData.scss
  src/_scss/pages/covid19/assistanceListing/_assistanceListing.scss
  src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/_scss/pages/explorer/detail/visualization/visualization.scss
  src/js/components/about/AboutContent.jsx
  src/js/components/about/Careers.jsx
  src/js/components/account/Account.jsx
  src/js/components/account/SearchResults.jsx
  src/js/components/account/visualizations/sankey/SankeyVisualizationHorizontal.jsx
  src/js/components/account/visualizations/sankey/SankeyVisualizationVertical.jsx
  src/js/components/agencyV2/AgencySection.jsx
  src/js/components/bulkDownload/awards/AwardDataContent.jsx
  src/js/components/covid19/Covid19Section.jsx
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
  src/js/components/sharedComponents/Note.jsx
  src/js/containers/Footer.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/helpers/covid19.jsx
  src/js/containers/covid19/recipient/map/MapContainer.jsx
  src/js/models/account/FederalAccount.js
  tests/components/about/AboutContent-test.jsx
Labels: ENV Promotion

#2474 Fix/dev 6896 object class tip missing percent
  src/js/components/agency/visualizations/objectClass/MajorObjectClasses.jsx
  src/js/components/agency/visualizations/objectClass/MinorObjectClasses.jsx
Labels: warm-fix

#2476 Demote hotfix master -> qat
  src/js/components/explorer/detail/UnreportedErrorScreen.jsx
Labels: down merge

#2475 Warmfix DEV-7038 Agency Submission Statistics tooltips
  src/_scss/pages/aboutTheData/_tableControls.scss
Labels: warm-fix

#2479 dev 7035 update wording
  src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
Labels: warm-fix

#2480 Demote hotfix & warmfixes qat -> dev
  src/_scss/pages/aboutTheData/_tableControls.scss
  src/js/components/explorer/detail/UnreportedErrorScreen.jsx
  src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
Labels: down merge

#2484 Warmfix DEV-7088 Percent of Total Federal Budget
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/helpers/aboutTheDataHelper.js
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/containers/aboutTheData/mockData.js
  tests/helpers/aboutTheDataHelper-test.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: warm-fix

#2485 Demote warmfix qat -> dev
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/helpers/aboutTheDataHelper.js
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  tests/containers/aboutTheData/mockData.js
  tests/helpers/aboutTheDataHelper-test.js
  tests/models/aboutTheData/PublicationOverviewRow-test.js
Labels: down merge
