Repository fedspendingtransparency/usaspending-website, pull requests merged in 2021-02, with the labels that each got.

#2366 [About-The-Data] P4 should be in Q2, not Q1
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
Labels: warm-fix

#2357 Mod/dev 6087 improve error message
  src/js/containers/covid19/assistanceListing/CFDAOpportunityTotals.jsx
Labels: do not merge

#2369 QAT --> DEV: Down Merge #2366
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
Labels: down merge

#2371 [DEV-6464] Updating copy content of Tab on About the data Page
  src/js/components/aboutTheData/AboutTheDataPage.jsx
Labels: warm-fix

#2365 [DEV-6748] Refactor Adv Search to use Query Params
  src/js/containers/router/RouterRoutes.js
  src/js/containers/search/SearchContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/dataMapping/shared/checkboxTree/checkboxTree.jsx
  src/js/helpers/searchHelper.js
  tests/containers/search/SearchContainer-test.jsx
  tests/containers/search/table/ResultsTableContainer-test.jsx
  tests/helpers/searchHelper-test.js
Labels: warm-fix

#2375 Demote warmfixes qat -> dev
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/containers/search/SearchContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/dataMapping/shared/checkboxTree/checkboxTree.jsx
  src/js/helpers/searchHelper.js
  tests/containers/search/SearchContainer-test.jsx
  tests/containers/search/table/ResultsTableContainer-test.jsx
  tests/helpers/searchHelper-test.js
Labels: down merge

#2380 Sprint 126 ENV Promotion DEV --> QAT
  package-lock.json
  package.json
  src/_scss/pages/aboutTheData/aboutTheData.scss
  src/js/components/bulkDownload/DEFCheckboxTreeDownload.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/containers/account/AccountContainer.jsx
  src/js/containers/account/WithLatestFy.jsx
  src/js/containers/account/filters/AccountTimePeriodContainer.jsx
  src/js/containers/accountLanding/AccountLandingContainer.jsx
  src/js/containers/award/AwardContainer.jsx
  src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/WithDefCodes.jsx
  src/js/containers/covid19/assistanceListing/CFDAOpportunityTotals.jsx
  src/js/containers/homepage/CovidHighlights.jsx
  src/js/containers/search/filters/def/DEFCheckboxTree.jsx
  src/js/helpers/aboutTheDataHelper.js
  src/js/models/v2/aboutTheData/BaseAgencyRow.js
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  src/js/propTypes/index.js
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/containers/aboutTheData/AgencyDetailsContainer-test.jsx
  tests/containers/aboutTheData/mockData.js
  tests/containers/account/WithLatestFy-test.js
  tests/containers/award/AwardContainer-test.jsx
  tests/containers/award/awardHelper.js
  tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
  tests/containers/covid19/WithDefCodes-test.js
  tests/containers/homepage/CovidHighlights-test.jsx
  tests/containers/search/filters/DEFCheckboxxTree-test.jsx
  tests/helpers/aboutTheDataHelper-test.js
  tests/mockData/helpers/disasterHelper.js
  tests/models/aboutTheData/BaseReportingPeriodRow-test.js
Labels: ENV Promotion

#2386 [DEV-6870] Hotfix DEFC "U" message
  src/js/components/about/DataQuality.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  tests/components/about/DataQuality-test.jsx
  tests/components/covid19/DataSourcesAndMethodologiesPage-test.jsx
  tests/components/homepage/hero/TotalAmount-test.jsx
Labels: hotfix

#2383 [DEV-6871] Home Page Data as of Bug (perpetual loading after refresh)
  src/js/containers/homepage/CovidHighlights.jsx
Labels: hotfix

#2387 Demote hotfixes master -> qat (w/ conflicts resolved)
  src/js/components/about/DataQuality.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  tests/components/about/DataQuality-test.jsx
  tests/components/covid19/DataSourcesAndMethodologiesPage-test.jsx
  tests/components/homepage/hero/TotalAmount-test.jsx
Labels: down merge

#2388 Down Merge QAT --> DEV
  src/js/components/about/DataQuality.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  tests/components/about/DataQuality-test.jsx
  tests/components/covid19/DataSourcesAndMethodologiesPage-test.jsx
  tests/components/homepage/hero/TotalAmount-test.jsx
Labels: down merge

#2396 [DEV-6852] Warmfix Federal Account profile bug
  src/js/components/account/AccountOverview.jsx
  src/js/containers/account/AccountContainer.jsx
  tests/containers/account/AccountContainer-test.jsx
Labels: warm-fix

#2397 Demote warmfix qat -> dev
  src/js/components/account/AccountOverview.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/account/AccountContainer.jsx
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/containers/account/AccountContainer-test.jsx
Labels: down merge

#2395 Dev-6698 Unlinked Modals API Integration
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/containers/aboutTheData/modals/UnlinkedDataContainer.jsx
  src/js/helpers/aboutTheDataHelper.js
  tests/containers/aboutTheData/UnlinkedDataContainer-test.jsx
Labels: pending-api

#2403 QAT --> Staging for Sprint 126 Deploy
  src/js/components/about/DataQuality.jsx
  src/js/components/account/AccountOverview.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/account/AccountContainer.jsx
  tests/components/about/DataQuality-test.jsx
  tests/components/covid19/DataSourcesAndMethodologiesPage-test.jsx
  tests/components/homepage/hero/TotalAmount-test.jsx
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/containers/account/AccountContainer-test.jsx
Labels: ENV Promotion

#2404 Sprint 126 Promotion: Staging --> Master
  package-lock.json
  package.json
  src/_scss/pages/aboutTheData/aboutTheData.scss
  src/js/components/account/AccountOverview.jsx
  src/js/components/bulkDownload/DEFCheckboxTreeDownload.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/aboutTheData/AgenciesContainer.jsx
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
  src/js/containers/account/AccountContainer.jsx
  src/js/containers/account/WithLatestFy.jsx
  src/js/containers/account/filters/AccountTimePeriodContainer.jsx
  src/js/containers/accountLanding/AccountLandingContainer.jsx
  src/js/containers/award/AwardContainer.jsx
  src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/covid19/WithDefCodes.jsx
  src/js/containers/covid19/assistanceListing/CFDAOpportunityTotals.jsx
  src/js/containers/homepage/CovidHighlights.jsx
  src/js/containers/search/filters/def/DEFCheckboxTree.jsx
  src/js/helpers/aboutTheDataHelper.js
  src/js/models/v2/aboutTheData/BaseAgencyRow.js
  src/js/models/v2/aboutTheData/PublicationOverviewRow.js
  src/js/propTypes/index.js
  tests/containers/aboutTheData/AgenciesContainer-test.jsx
  tests/containers/aboutTheData/AgencyDetailsContainer-test.jsx
  tests/containers/aboutTheData/mockData.js
  tests/containers/account/AccountContainer-test.jsx
  tests/containers/account/WithLatestFy-test.js
  tests/containers/award/AwardContainer-test.jsx
  tests/containers/award/awardHelper.js
  tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
  tests/containers/covid19/WithDefCodes-test.js
  tests/containers/homepage/CovidHighlights-test.jsx
  tests/containers/search/filters/DEFCheckboxxTree-test.jsx
  tests/helpers/aboutTheDataHelper-test.js
  tests/mockData/helpers/disasterHelper.js
  tests/models/aboutTheData/BaseReportingPeriodRow-test.js
Labels: ENV Promotion

#2405 Sprint 127 Promotion: DEV --> QAT
  .gitignore
  jest.config.js
  package.json
  scripts/buildRedirectConfig.js
  scripts/sitemaps/buildSitemap.js
  scripts/sitemaps/pages.js
  src/_scss/components/_stickyTable.scss
  src/_scss/pages/aboutTheData/_agenciesPage.scss
  src/_scss/pages/account/overview/overview.scss
  src/js/GlobalConstants.js
  src/js/components/about/AboutContent.jsx
  src/js/components/about/legal/common/LegalContent.jsx
  src/js/components/aboutTheData/AboutTheDataPage.jsx
  src/js/components/aboutTheData/AgencyDetailsPage.jsx
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/aboutTheData/DrilldownCell.jsx
  src/js/components/aboutTheData/dataMapping/tooltipContentMapping.jsx
  src/js/components/account/AccountOverview.jsx
  src/js/components/agency/AgencyContent.jsx
  src/js/components/covid19/AmountsVisualization.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/components/recipient/RecipientContent.jsx
  src/js/components/sharedComponents/DatePicker.jsx
  src/js/components/sharedComponents/header/DropdownItem.jsx
  src/js/components/sharedComponents/header/NavBar.jsx
  src/js/components/sharedComponents/header/mobile/MobileNav.jsx
  src/js/components/sharedComponents/sidebar/Sidebar.jsx
  src/js/components/sharedComponents/stickyHeader/StickyHeader.jsx
  src/js/components/state/StateContent.jsx
  src/js/components/stateLanding/table/StateLinkCell.jsx
  src/js/containers/Footer.jsx
  src/js/containers/aboutTheData/modals/PublicationDatesContainer.jsx
  src/js/containers/aboutTheData/modals/UnlinkedDataContainer.jsx
  src/js/containers/covid19/Covid19Container.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/containers/state/StateContainer.jsx
  src/js/dataMapping/covid19/covid19.js
  src/js/dataMapping/navigation/menuOptions.jsx
  src/js/dataMapping/state/stateNames.js
  src/js/dataMapping/stickyHeader/stickyHeader.js
  src/js/helpers/aboutTheDataHelper.js
  src/js/helpers/checkboxTreeHelper.js
  src/js/helpers/covid19Helper.js
  src/js/helpers/stateHelper.js
  src/js/helpers/stickyHeaderHelper.js
  src/js/models/account/FederalAccount.js
  src/js/redux/reducers/account/accountReducer.js
  tests/components/aboutTheData/AboutTheDataPage-test.jsx
  tests/containers/aboutTheData/UnlinkedDataContainer-test.jsx
  tests/containers/search/filters/psc/mockPSC.js
  tests/containers/state/StateContainer-test.jsx
  tests/containers/state/mockData.js
  tests/helpers/aboutTheDataHelper-test.js
  tests/helpers/checkboxTreeHelper-test.js
  tests/helpers/stateHelper-test.js
  webpack/webpack.common.js
Labels: ENV Promotion

#2412 [DEV-6914] Hotfix COVID Data Sources & Methodology copy
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Labels: hotfix

#2411 [DEV-6930] Fix Unlinked Awards column sort
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
Labels: warm-fix

#2416 Qat -> Dev Unlinked Data Column Sorting Fields
  src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
  src/js/containers/aboutTheData/AgencyTableMapping.jsx
Labels: down merge

#2414 Dev-6876 Covid Banner Floating Off Course
  src/js/helpers/stickyHeaderHelper.js
Labels: warm-fix
