Repository fedspendingtransparency/usaspending-website, pull requests merged in 2022-02, with the labels that each got.

#2909 Promote QAT to Staging
  package-lock.json
  package.json
  src/_scss/elements/_typography.scss
  src/_scss/layouts/default/header/_warning.scss
  src/_scss/pages/agencyV2/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/agencyV2/visualizations/_statusOfFundsChart.scss
  src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/modals/covid19/_covid19.scss
  src/js/components/agencyV2/AgencyPage.jsx
  src/js/components/agencyV2/AgencySection.jsx
  src/js/components/agencyV2/overview/AgencyOverview.jsx
  src/js/components/agencyV2/overview/FySummary.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx
  src/js/components/award/idv/activity/ActivityChartTooltip.jsx
  src/js/components/award/idv/activity/IdvActivityVisualization.jsx
  src/js/components/award/idv/referencedAwards/ReferencedAwardsTable.jsx
  src/js/components/award/shared/additionalInfo/AdditionalInfo.jsx
  src/js/components/award/shared/awardAmounts/AwardAmountsTable.jsx
  src/js/components/bulkDownload/DEFCheckboxTreeDownload.jsx
  src/js/components/covid19/DateNote.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/containers/agencyV2/awardSpending/SubAgencySummaryContainer.jsx
  src/js/containers/covid19/WithDefCodes.jsx
  src/js/containers/globalModal/GlobalModalContainer.jsx
  src/js/containers/homepage/UEIModalContainer.jsx
  src/js/dataMapping/award/additionalDetailsContract.js
  src/js/dataMapping/award/additionalDetailsIdv.js
  src/js/dataMapping/award/awardAmountsSection.js
  src/js/models/v2/award/BaseAwardAmounts.js
  src/js/models/v2/award/BaseContract.js
  src/js/models/v2/award/BaseFinancialAssistance.js
  src/js/models/v2/award/BaseIdv.js
  src/js/models/v2/award/BaseIdvActivityBar.js
  src/js/models/v2/award/BaseParentAwardDetails.js
  src/js/models/v2/award/BaseReferencedAwardResult.js
  src/js/models/v2/award/CoreAward.js
  src/js/redux/actions/agencyV2/agencyV2Actions.js
  src/js/redux/reducers/agencyV2/agencyV2Reducer.js
  tests/components/agency/visualizations/StatusOfFundsChart-test.jsx
  tests/helpers/apiRequest-test.js
  tests/helpers/awardAmountHelper-test.js
  tests/models/award/BaseAwardAmounts-test.js
  tests/models/award/mockAwardApi.js
Labels: ENV Promotion

#2913 Mod/dev 8099 add data through date to agency profiles
  src/js/components/agencyV2/AgencyPage.jsx
  src/js/components/agencyV2/AgencySection.jsx
  src/js/components/agencyV2/overview/FySummary.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
  tests/components/agency/overview/FYSummary-test.jsx
Labels: ENV Promotion

#2915 Staging -> Master - Prod deploy Sprint 146
  package-lock.json
  package.json
  src/_scss/elements/_typography.scss
  src/_scss/layouts/default/header/_warning.scss
  src/_scss/pages/agencyV2/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/agencyV2/visualizations/_statusOfFundsChart.scss
  src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/_scss/pages/homepage/homePage.scss
  src/_scss/pages/modals/covid19/_covid19.scss
  src/js/components/agencyV2/AgencyPage.jsx
  src/js/components/agencyV2/AgencySection.jsx
  src/js/components/agencyV2/overview/AgencyOverview.jsx
  src/js/components/agencyV2/overview/FySummary.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx
  src/js/components/award/idv/activity/ActivityChartTooltip.jsx
  src/js/components/award/idv/activity/IdvActivityVisualization.jsx
  src/js/components/award/idv/referencedAwards/ReferencedAwardsTable.jsx
  src/js/components/award/shared/additionalInfo/AdditionalInfo.jsx
  src/js/components/award/shared/awardAmounts/AwardAmountsTable.jsx
  src/js/components/bulkDownload/DEFCheckboxTreeDownload.jsx
  src/js/components/covid19/DateNote.jsx
  src/js/components/homepage/CovidVaccineLink.jsx
  src/js/components/homepage/Homepage.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/containers/agencyV2/awardSpending/SubAgencySummaryContainer.jsx
  src/js/containers/covid19/WithDefCodes.jsx
  src/js/containers/globalModal/GlobalModalContainer.jsx
  src/js/containers/homepage/UEIModalContainer.jsx
  src/js/dataMapping/award/additionalDetailsContract.js
  src/js/dataMapping/award/additionalDetailsIdv.js
  src/js/dataMapping/award/awardAmountsSection.js
  src/js/models/v2/award/BaseAwardAmounts.js
  src/js/models/v2/award/BaseContract.js
  src/js/models/v2/award/BaseFinancialAssistance.js
  src/js/models/v2/award/BaseIdv.js
  src/js/models/v2/award/BaseIdvActivityBar.js
  src/js/models/v2/award/BaseParentAwardDetails.js
  src/js/models/v2/award/BaseReferencedAwardResult.js
  src/js/models/v2/award/CoreAward.js
  src/js/redux/actions/agencyV2/agencyV2Actions.js
  src/js/redux/reducers/agencyV2/agencyV2Reducer.js
  tests/components/agency/overview/FYSummary-test.jsx
  tests/components/agency/visualizations/StatusOfFundsChart-test.jsx
  tests/helpers/apiRequest-test.js
  tests/helpers/awardAmountHelper-test.js
  tests/models/award/BaseAwardAmounts-test.js
  tests/models/award/mockAwardApi.js
Labels: ENV Promotion

#2930 [DEV-8499] Increase download limit message back to 500k
  package-lock.json
  package.json
  src/js/components/search/header/NoDownloadHover.jsx
Labels: hotfix

#2931 Downmerge into staging
  src/js/components/search/header/NoDownloadHover.jsx
Labels: down merge

#2936 8480 - Recipient page UEI banner downmerge
  src/_scss/pages/recipient/_recipientInfoBanner.scss
  src/_scss/pages/recipient/recipientPage.scss
  src/js/components/recipient/RecipientInfoBanner.jsx
  src/js/components/recipient/RecipientPage.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/components/sharedComponents/header/UEIInfoBanner.jsx
  src/js/dataMapping/stickyHeader/stickyHeader.js
Labels: down merge

#2932 Downmerge into qat
  src/index.ejs
  src/js/components/search/header/NoDownloadHover.jsx
  src/js/containers/glossary/GlossaryListener.jsx
  webpack/webpack.common.js
Labels: do not merge, down merge
