Repository fedspendingtransparency/usaspending-website, pull requests merged in 2022-12, with the labels that each got.

#3354 9346 - reverted several instances of 'data-sources' that were changed…
  scripts/sitemaps/pages.js
  src/js/components/about/AboutContent.jsx
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: hotfix

#3351 9345 - reverted change in spendingByCategory.js to fix api call
  src/js/dataMapping/search/spendingByCategory.js
Labels: hotfix

#3356 Staging to QAT downmerge
  scripts/sitemaps/pages.js
  src/js/components/about/AboutContent.jsx
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/dataMapping/navigation/menuOptions.jsx
  src/js/dataMapping/search/spendingByCategory.js
Labels: down merge

#3393 DEV-9393 covid page dropdown text fix
  src/_scss/pages/covid19/_budgetCategoriesTable.scss
Labels: hotfix

#3395 Staging to qat
  src/_scss/pages/covid19/_budgetCategoriesTable.scss
Labels: down merge

#3385 Mod/8529 add tooltip and glossary to time period filter
  src/_scss/pages/search/filters/timePeriod/_toggleButtons.scss
  src/_scss/pages/search/filters/timePeriod/timePeriod.scss
  src/js/components/search/SearchSidebar.jsx
  src/js/components/search/filters/timePeriod/TimePeriod.jsx
  src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
Labels: do not merge

#3390 Mod/8546 search tabs css
  src/_scss/pages/search/results/_tabs.scss
  src/_scss/pages/search/results/searchResults.scss
Labels: do not merge
