Repository fedspendingtransparency/usaspending-website, pull requests merged in 2022-08, with the labels that each got.

#3171 Promote QAT to Staging
  .nvmrc
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/_scss/components/_newBadge.scss
  src/_scss/components/checkbox/_primaryCheckboxType.scss
  src/_scss/pages/accountLanding/table/_table.scss
  src/_scss/pages/accountLanding/table/resultsSection.scss
  src/_scss/pages/agencyLanding/table/_table.scss
  src/_scss/pages/agencyLanding/table/resultsSection.scss
  src/_scss/pages/homepage/_summaryStats.scss
  src/_scss/pages/homepage/homepage.scss
  src/_scss/pages/recipient/recipientPage.scss
  src/_scss/pages/search/results/_tabs.scss
  src/js/components/dataDives/EquityCovidSpendingPage.jsx
  src/js/components/dataDives/equity/EquitySpotlightCards.jsx
  src/js/components/dataDives/sections/MainCards.jsx
  src/js/components/dataDives/shared/DataDiveHeading.jsx
  src/js/components/dataDives/shared/MainCard.jsx
  src/js/components/dataDives/shared/MainCards.jsx
  src/js/components/homepage/SummaryStats.jsx
  src/js/components/recipient/RecipientInfoBanner.jsx
  src/js/components/recipient/RecipientPage.jsx
  src/js/components/search/table/cells/ResultsTableLinkCell.jsx
  src/js/components/search/visualizations/rank/chart/ChartGroup.jsx
  src/js/components/sharedComponents/PageWrapper.jsx
  src/js/components/sharedComponents/cards/Card.jsx
  src/js/components/sharedComponents/cards/SpotlightCard.jsx
  src/js/components/sharedComponents/header/Dropdown.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/UEIInfoBanner.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdown.jsx
  src/js/containers/account/topFilterBar/AccountTopFilterBarContainer.jsx
  src/js/containers/homepage/HomepageCovidContainer.jsx
  src/js/dataMapping/search/geoVisualizationSection.jsx
  tests/components/aboutTheData/AboutTheDataModal-test.jsx
  tests/components/agency/AgencyOverview-test.jsx
  tests/components/homepage/hero/TotalAmount-test.jsx
  tests/components/sharedComponents/EquityMainCard-test.jsx
  tests/containers/aboutTheData/PublicationDatesContainer-test.jsx
  tests/containers/account/AccountContainer-test.jsx
  tests/containers/account/topFilterBar/AccountTopFilterBarContainer-test.jsx
  tests/containers/award/idv/IdvActivityContainer-test.jsx
  tests/containers/award/shared/AwardHistorySectionContainer-test.jsx
  tests/containers/award/table/FederalAccountTableContainer-test.jsx
  tests/containers/bulkDownload/modal/BulkDownloadBottomBarContainer-test.jsx
  tests/containers/covid19/SummaryInsightsContainer-test.jsx
  tests/containers/explorer/detail/DetailContentContainer-test.jsx
  tests/containers/homepage/CovidHighlights-test.jsx
  tests/containers/recipient/modal/ChildRecipientModalContainer-test.jsx
  tests/containers/recipientLanding/RecipientLandingContainer-test.jsx
  tests/containers/search/filters/naics/NAICSCheckboxTree-test.jsx
  tests/containers/search/filters/programSource/TASCheckboxContainer-test.jsx
  tests/containers/search/filters/psc/PSCCheckboxTreeContainer-test.jsx
  tests/containers/search/modals/fullDownload/DownloadBottomBarContainer-test.jsx
  tests/containers/state/StateContainer-test.jsx
  tests/containers/stateLanding/StateLandingContainer-test.jsx
  tests/setup.js
Labels: ENV Promotion

#3172 8959 - Hotfix Summary stats Promote to Master
  package-lock.json
  src/_scss/pages/homepage/_summaryStats.scss
  src/_scss/pages/homepage/homepage.scss
  src/_scss/pages/search/results/_tabs.scss
  src/js/components/homepage/SummaryStats.jsx
Labels: ENV Promotion

#3175 Promote QAT to Staging
  package-lock.json
  package.json
  src/_scss/components/_chartTableToggle.scss
  src/_scss/pages/agency/index.scss
  src/_scss/pages/agency/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/agency/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/agencyLanding/agencyLandingPage.scss
  src/_scss/pages/agencyLanding/table/resultsSection.scss
  src/_scss/pages/recipient/_contentWrap.scss
  src/_scss/pages/search/results/_tabs.scss
  src/js/components/agency/statusOfFunds/VisualizationSection.jsx
  src/js/components/recipient/RecipientOverview.jsx
  src/js/components/sharedComponents/accordion/Accordion.jsx
  src/js/components/sharedComponents/buttons/ChartTableToggle.jsx
Labels: ENV Promotion

#3195 Downmerge staging to qat
  package-lock.json
Labels: down merge

#3200 9030 - deleted one link that was stale; added two new links under dep…
  src/data/data-limitations.pdf
  src/js/components/covid19/OtherResources.jsx
Labels: hotfix

#3203 Down merge Staging to QAT
  src/data/data-limitations.pdf
  src/js/components/covid19/OtherResources.jsx
  src/js/components/sharedComponents/UnlinkedAwardWarning.jsx
Labels: down merge
