Repository fedspendingtransparency/usaspending-website, pull requests merged in 2022-11, with the labels that each got.

#3308 9223 - removed the glossary button and its wrapper from the footer; r…
  src/_scss/layouts/default/footer/_floatingGlossaryButton.scss
  src/_scss/layouts/default/footer/footer.scss
  src/js/components/sharedComponents/FloatingGlossaryButton.jsx
  src/js/components/sharedComponents/header/mobile/MobileGlossaryButton.jsx
  src/js/containers/Footer.jsx
  src/js/containers/glossary/GlossaryButtonWrapperContainer.jsx
  tests/containers/account/AccountContainer-test.jsx
Labels: hotfix

#3312 Staging to qat
  package-lock.json
  package.json
  src/_scss/layouts/default/footer/_floatingGlossaryButton.scss
  src/_scss/layouts/default/footer/footer.scss
  src/js/components/homepageUpdate/WordOfTheDay/WordOfTheDay.jsx
  src/js/components/sharedComponents/FloatingGlossaryButton.jsx
  src/js/components/sharedComponents/header/mobile/MobileGlossaryButton.jsx
  src/js/containers/Footer.jsx
  src/js/containers/glossary/GlossaryButtonWrapperContainer.jsx
  tests/containers/account/AccountContainer-test.jsx
Labels: down merge

#3314 no tkt number yet - changed this text in Resources section, again
  src/js/components/homepageUpdate/HomepageResources/HomepageResources.jsx
Labels: hotfix

#3317 9252 - changed 'Data Sources' to 'Data Model'; changed the link in th…
  src/js/components/homepageUpdate/HomepageResources/HomepageResources.jsx
  src/js/components/sharedComponents/commonCards/CardButton.jsx
Labels: hotfix

#3319 9252 - Promote hotfix to master
  src/js/components/homepageUpdate/HomepageResources/HomepageResources.jsx
  src/js/components/sharedComponents/commonCards/CardButton.jsx
Labels: ENV Promotion

#3318 Downmerge Staging to QAT
  src/js/components/homepageUpdate/HomepageResources/HomepageResources.jsx
  src/js/components/sharedComponents/commonCards/CardButton.jsx
Labels: down merge

#3339 Promote QAT to Staging
  package-lock.json
  src/_scss/components/aboutTheDataSidebar/aboutTheData.scss
  src/_scss/core/_variables.scss
  src/_scss/pages/interactiveDataSources/_dataSourcesTitles.scss
  src/_scss/pages/interactiveDataSources/_scrollerOverlayCard.scss
  src/_scss/pages/interactiveDataSources/index.scss
  src/img/interactive-data-sources/10_UUC.json
  src/img/interactive-data-sources/1_FSO.json
  src/img/interactive-data-sources/1_FSO_COIN.json
  src/img/interactive-data-sources/2_DA.json
  src/img/interactive-data-sources/2_DA_BG.json
  src/img/interactive-data-sources/3_DT.json
  src/img/interactive-data-sources/3_DT_BG.json
  src/img/interactive-data-sources/3_DT_GIRL.json
  src/img/interactive-data-sources/4_DSS.json
  src/img/interactive-data-sources/4_DSS_BG.json
  src/img/interactive-data-sources/4_DSS_TYPES.json
  src/img/interactive-data-sources/5_DS_ACCOUNT.json
  src/img/interactive-data-sources/5_DS_ACCOUNT_BG.json
  src/img/interactive-data-sources/5_DS_ADDITIONAL.json
  src/img/interactive-data-sources/5_DS_ADDITIONAL_BG.json
  src/img/interactive-data-sources/5_DS_AWARD.json
  src/img/interactive-data-sources/5_DS_AWARD_BG.json
  src/img/interactive-data-sources/6_DSE.json
  src/img/interactive-data-sources/6_DSE_BG.json
  src/img/interactive-data-sources/7_FDU.json
  src/img/interactive-data-sources/7_FDU_UPDATES.json
  src/img/interactive-data-sources/8_DVBS.json
  src/img/interactive-data-sources/9_DA.json
  src/img/interactive-data-sources/intro-animation.json
  src/js/components/aboutTheDataSidebar/AboutTheData.jsx
  src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx
  src/js/components/interactiveDataSources/InteractiveDataSourcesSection.jsx
  src/js/components/interactiveDataSources/scroller/scrollerOverlay/ScrollerOverlayCard.jsx
  src/js/components/interactiveDataSources/scrollerSections/AccountData.jsx
  src/js/components/interactiveDataSources/scrollerSections/AdditionalData.jsx
  src/js/components/interactiveDataSources/scrollerSections/AwardData.jsx
  src/js/components/interactiveDataSources/scrollerSections/DataAvailable.jsx
  src/js/components/interactiveDataSources/scrollerSections/DataFeatures.jsx
  src/js/components/interactiveDataSources/scrollerSections/DataSourceSystems.jsx
  src/js/components/interactiveDataSources/scrollerSections/DataSubmissionExtraction.jsx
  src/js/components/interactiveDataSources/scrollerSections/DataTypes.jsx
  src/js/components/interactiveDataSources/scrollerSections/DataUseCases.jsx
  src/js/components/interactiveDataSources/scrollerSections/DataValidation.jsx
  src/js/components/interactiveDataSources/scrollerSections/FederalSpendingOverview.jsx
  src/js/components/interactiveDataSources/scrollerSections/Frequency.jsx
  tests/components/interactiveDataSources/ScrollerOverlayCard-test.jsx
Labels: ENV Promotion

#3343 Promote QAT to Staging
  package-lock.json
  src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx
Labels: ENV Promotion

#3345 DEV-9340 fixed homepage link
  package-lock.json
  src/js/components/homepageUpdate/ReadyToGetStarted/ReadyToGetStarted.jsx
Labels: hotfix

#3346 Down merge Hotfix to Staging
  package-lock.json
  src/js/components/homepageUpdate/ReadyToGetStarted/ReadyToGetStarted.jsx
Labels: down merge

#3347 Down merge Hotfix to QAT
  package-lock.json
  src/js/components/homepageUpdate/ReadyToGetStarted/ReadyToGetStarted.jsx
Labels: down merge
