Repository fedspendingtransparency/usaspending-website, pull requests merged in 2022-01, with the labels that each got.

#2860 Mid-Sprint Merge QAT --> Staging
  package-lock.json
  package.json
  src/_scss/components/_moreOptionsTabs.scss
  src/_scss/mixins/profilePage.scss
  src/_scss/pages/agencyV2/index.scss
  src/_scss/pages/agencyV2/overview/_overview.scss
  src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
  src/_scss/pages/agencyV2/visualizations/_barChart.scss
  src/_scss/pages/agencyV2/visualizations/_obligationsByAwardType.scss
  src/_scss/pages/agencyV2/visualizations/_totalObligationsOverTime.scss
  src/_scss/pages/covid19/_sidebarFooter.scss
  src/_scss/pages/covid19/index.scss
  src/_scss/pages/recipientLanding/_recipientLabels.scss
  src/_scss/pages/recipientLanding/_table.scss
  src/_scss/pages/recipientLanding/recipientLandingPage.scss
  src/js/components/agencyLanding/table/cells/AgencyLinkCell.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/AgencyBudgetLine.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx
  src/js/components/covid19/Covid19Page.jsx
  src/js/components/covid19/DateNote.jsx
  src/js/components/covid19/Heading.jsx
  src/js/components/covid19/SidebarFooter.jsx
  src/js/components/covid19/amountsVisualization/AmountsVisualization.jsx
  src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
  src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
  src/js/components/covid19/budgetCategories/BudgetCategories.jsx
  src/js/components/covid19/recipient/RecipientSection.jsx
  src/js/components/recipient/RecipientMultiParentCollapse.jsx
  src/js/components/recipientLanding/RecipientLandingContent.jsx
  src/js/components/recipientLanding/RecipientLandingTabs.jsx
  src/js/components/search/visualizations/rank/sections/SpendingByRecipientSection.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/components/sharedComponents/header/InfoBanner.jsx
  src/js/components/sharedComponents/moreOptionsTabs/MoreOptionsTabs.jsx
  src/js/components/state/topFive/TopFiveSection.jsx
  src/js/containers/account/WithLatestFy.jsx
  src/js/containers/agencyLanding/AgencyLandingContainer.jsx
  src/js/containers/agencyV2/AgencyContainerV2.jsx
  src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
  src/js/containers/state/topFive/TopFiveContainer.jsx
  src/js/dataMapping/award/additionalDetailsIdv.js
  src/js/dataMapping/search/awardTableColumnTypes.js
  src/js/dataMapping/search/awardTableColumns.jsx
  src/js/dataMapping/search/filterFields.js
  src/js/helpers/covid19Helper.js
  src/js/helpers/queryParams.js
  src/js/models/v2/agency/BaseAgencyOverview.js
  src/js/models/v2/recipient/BaseRecipientLandingRow.js
  tests/components/sharedComponents/InfoBanner-test.jsx
  tests/containers/account/WithLatestFy-test.js
  tests/helpers/queryParams-test.js
Labels: ENV Promotion

#2863 DEV-8053 Link to Federal Account profiles status of funds viz
  src/_scss/pages/agencyV2/statusOfFunds/_drilldownSidebar.scss
  src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
  src/js/apis/agencyV2.js
  src/js/components/agencyV2/statusOfFunds/DrilldownSidebar.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx
  src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx
  src/js/models/v2/agency/BaseAgencySubcomponentsList.js
  src/js/models/v2/agency/BaseStatusOfFundsLevel.js
  src/js/redux/actions/agencyV2/agencyV2Actions.js
  src/js/redux/reducers/agencyV2/agencyV2Reducer.js
  tests/components/agency/visualizations/StatusOfFundsChart-test.jsx
  tests/models/agency/BaseAgencySubcomponentsList-test.js
  tests/models/agency/BaseStatusOfFundsLevel-test.js
Labels: do not merge

#2871 QAT -> Staging
  package-lock.json
  src/_scss/pages/agency/_overview.scss
  src/_scss/pages/agencyV2/statusOfFunds/_drilldownSidebar.scss
  src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/agencyV2/visualizations/_totalObligationsOverTime.scss
  src/graphics/agency/PRESIDIO.png
  src/js/GlobalConstants.js
  src/js/apis/agencyV2.js
  src/js/components/agencyV2/overview/FySummary.jsx
  src/js/components/agencyV2/statusOfFunds/DrilldownSidebar.jsx
  src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx
  src/js/components/agencyV2/visualizations/ObligationsByAwardType.jsx
  src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx
  src/js/components/award/shared/federalAccounts/FederalAccountsTable.jsx
  src/js/components/award/shared/overview/AwardingAgency.jsx
  src/js/components/award/table/FederalAccountTable.jsx
  src/js/containers/agencyV2/visualizations/ObligationsByAwardTypeContainer.jsx
  src/js/containers/agencyV2/visualizations/TotalObligationsOverTimeContainer.jsx
  src/js/containers/recipient/RecipientContainer.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/dataMapping/agencyV2/visualizations/totalObligationsOverTime.js
  src/js/dataMapping/award/additionalDetailsContract.js
  src/js/dataMapping/award/additionalDetailsFinancialAssistance.js
  src/js/dataMapping/award/additionalDetailsIdv.js
  src/js/helpers/fiscalYearHelper.js
  src/js/models/v2/agency/BaseAgencyBudgetaryResources.js
  src/js/models/v2/agency/BaseAgencySubcomponentsList.js
  src/js/models/v2/agency/BaseStatusOfFundsLevel.js
  src/js/models/v2/award/BaseContract.js
  src/js/models/v2/award/BaseFederalAccount.js
  src/js/models/v2/award/BaseFederalAccountFunding.js
  src/js/models/v2/award/BaseFinancialAssistance.js
  src/js/models/v2/award/BaseIdv.js
  src/js/models/v2/award/CoreAwardAgency.js
  src/js/redux/actions/agencyV2/agencyV2Actions.js
  src/js/redux/reducers/agencyV2/agencyV2Reducer.js
  tests/components/agency/visualizations/StatusOfFundsChart-test.jsx
  tests/helpers/fiscalYearHelper-test.js
  tests/models/agency/BaseAgencySubcomponentsList-test.js
  tests/models/agency/BaseStatusOfFundsLevel-test.js
Labels: ENV Promotion

#2874 Promote QAT -> Staging
  package-lock.json
  src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
  src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/AgencyBudgetLine.jsx
  src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx
Labels: ENV Promotion

#2876 8339 replace agency mapping with new
  src/js/dataMapping/agencyV2/agencyIdsToSlugs.js
Labels: hotfix

#2882 Staging -> qat
  src/js/GlobalConstants.js
  src/js/components/award/idv/activity/ActivityChartTooltip.jsx
  src/js/components/award/idv/referencedAwards/ReferencedAwardsTable.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/dataMapping/agency/tableColumns.js
  src/js/dataMapping/agencyV2/agencyIdsToSlugs.js
  src/js/dataMapping/award/additionalDetailsContract.js
  src/js/helpers/agencyV2/AwardSpendingSubagencyHelper.js
  src/js/models/v2/agency/BaseSubagencySpendingRow.js
  src/js/models/v2/agency/BaseSubagencySpendingRowChildren.js
  src/js/redux/reducers/agencyV2/agencyV2Reducer.js
  tests/helpers/agencyV2/visualizations/ObligationsByAwardTypeHelper-test.js
  tests/models/agency/BaseSubagencySpendingRow-test.js
Labels: down merge

#2886 Staging -> qat
  src/js/GlobalConstants.js
  src/js/containers/router/RouterRoutes.js
  src/js/dataMapping/agencyV2/agencyIdsToSlugs.js
Labels: down merge

#2892 Mod/dev 8305 update covid spending tag - down merge
  src/_scss/pages/agencyV2/overview/_pageTitle.scss
  src/_scss/pages/award/awardPage.scss
  src/js/components/agencyV2/overview/PageTitle.jsx
  src/js/components/award/shared/AwardPageWrapper.jsx
  src/js/components/award/shared/InfoTooltipContent.jsx
Labels: down merge

#2903 8410 remove vaccine.gov banner
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/_scss/pages/homepage/homePage.scss
  src/js/components/homepage/CovidVaccineLink.jsx
  src/js/components/homepage/Homepage.jsx
Labels: hotfix

#2905 Staging -> qat
  src/_scss/pages/homepage/covid-vaccine-link.scss
  src/_scss/pages/homepage/homePage.scss
  src/js/components/homepage/CovidVaccineLink.jsx
  src/js/components/homepage/Homepage.jsx
Labels: down merge
