Repository fedspendingtransparency/usaspending-website, pull requests merged in 2022-05, with the labels that each got.

#3065 Hotfix/8430 8778 agency headings training copy
  src/_scss/pages/agencyV2/overview/_visualizationSection.scss
  src/js/components/agencyV2/overview/FySummary.jsx
  src/js/components/sharedComponents/Training.jsx
Labels: ENV Promotion

#3066 Down merge DEV8430 & DEV8778 to QAT
  src/_scss/pages/agency/overview/_visualizationSection.scss
  src/js/components/agency/overview/FySummary.jsx
  src/js/components/sharedComponents/Training.jsx
Labels: down merge

#3084 8616 - added names without links to top 5 when no slug is available
  src/js/components/state/topFive/TopFiveRow.jsx
Labels: ENV Promotion

#3080 DEV-8484 keyword shake
  src/_scss/pages/search/_filterExpand.scss
Labels: do not merge

#3079 no ticket for this one; moved some css from one file to another to cl…
  src/_scss/pages/homepageUpdate/_gettingStarted.scss
  src/_scss/pages/homepageUpdate/features/_dropdown.scss
Labels: do not merge

#3086 8822 - changed text size in tooltips at mobile only for spending over…
  src/_scss/pages/account/results/visualizations/time/time.scss
Labels: do not merge
