Repository fedspendingtransparency/usaspending-website, pull requests merged in 2022-04, with the labels that each got.

#2993 DEV-8644 To be done on 4/1/22: Update FAQ and Community Platform URL
  src/js/components/about/Contact.jsx
  src/js/components/about/MoreInfo.jsx
  src/js/components/errorPage/ErrorPage.jsx
  src/js/components/explorer/landing/ExplorerLanding.jsx
  src/js/components/homepage/community/Community.jsx
  src/js/components/homepageUpdate/community/Community.jsx
  src/js/containers/Footer.jsx
Labels: hotfix

#2997 Staging > Prod Env Promotion for Hotfix DEV-8644
  src/js/components/about/Contact.jsx
  src/js/components/about/MoreInfo.jsx
  src/js/components/errorPage/ErrorPage.jsx
  src/js/components/explorer/landing/ExplorerLanding.jsx
  src/js/components/homepage/community/Community.jsx
  src/js/components/homepageUpdate/community/Community.jsx
  src/js/containers/Footer.jsx
Labels: ENV Promotion

#2998 8582 add word "legacy" to duns label environment promotion
  src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
  src/js/GlobalConstants.js
  src/js/components/recipient/modal/table/ChildRecipientModalTable.jsx
  src/js/components/recipientLanding/RecipientLandingSearchBar.jsx
  src/js/components/recipientLanding/table/RecipientLandingTable.jsx
  src/js/components/search/filters/recipient/RecipientName.jsx
  src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
  src/js/models/v2/recipient/BaseChildRecipient.js
Labels: ENV Promotion

#3003 Environment promotion for UEI hotfix
  src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
  src/_scss/pages/modals/recipient/_table.scss
  src/_scss/pages/stateLanding/_header.scss
  src/js/GlobalConstants.js
  src/js/components/recipient/modal/table/ChildRecipientModalTable.jsx
  src/js/components/recipientLanding/RecipientLandingSearchBar.jsx
  src/js/components/recipientLanding/table/RecipientLandingTable.jsx
  src/js/components/search/filters/recipient/RecipientName.jsx
  src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
  src/js/models/v2/recipient/BaseChildRecipient.js
Labels: ENV Promotion

#3007 Down merge hotfix
  src/js/components/about/Contact.jsx
  src/js/components/about/MoreInfo.jsx
  src/js/components/errorPage/ErrorPage.jsx
  src/js/components/explorer/landing/ExplorerLanding.jsx
  src/js/components/homepage/community/Community.jsx
  src/js/components/homepageUpdate/community/Community.jsx
  src/js/containers/Footer.jsx
Labels: down merge

#3006 Env Promotion - Push QAT to Staging
  package-lock.json
  package.json
  src/_scss/all.scss
  src/_scss/components/_card.scss
  src/_scss/core/_variables.scss
  src/_scss/elements/_accordion.scss
  src/_scss/elements/_buttons.scss
  src/_scss/pages/analystGuide/_analystGuideHeader.scss
  src/_scss/pages/analystGuide/analystGuide.scss
  src/_scss/pages/homepageUpdate/_homepageCovidSection.scss
  src/_scss/pages/homepageUpdate/hero/_hero.scss
  src/_scss/pages/homepageUpdate/homepageUpdate.scss
  src/img/analyst-guide-hero-graphic-2x.png
  src/img/homepage-covid-official-spending-data.svg
  src/img/homepage-hero-people-right.svg
  src/img/homepage-hero-person-left.svg
  src/js/GlobalConstants.js
  src/js/components/analystGuide/AnalystGuideHeader.jsx
  src/js/components/analystGuide/AnalystGuideIntro.jsx
  src/js/components/analystGuide/AnalystGuidePage.jsx
  src/js/components/analystGuide/AnalystGuideQuestions.jsx
  src/js/components/homepageUpdate/covid/Covid.jsx
  src/js/components/homepageUpdate/gettingStarted/GettingStarted.jsx
  src/js/components/homepageUpdate/hero/Hero.jsx
  src/js/components/sharedComponents/Card.jsx
  src/js/components/sharedComponents/accordion/Accordion.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/helpers/metaTagHelper.js
  src/js/helpers/recipientHelper.js
  src/js/helpers/stickyHeaderHelper.js
  src/js/registerIcons.js
  tests/components/analystGuide/AnalystGuide-test.jsx
  tests/components/sharedComponents/Accordion-test.jsx
  webpack/webpack.common.js
  webpack/webpack.dev.config.js
Labels: ENV Promotion

#3015 8647 - Agency Landing Page CJ Link Env Promotion
  package.json
  src/js/components/agencyLanding/AgencyLandingContent.jsx
Labels: ENV Promotion

#3020 Down merged staging to QAT
  src/js/GlobalConstants.js
  src/js/components/homepageUpdate/HomepageUpdate.jsx
Labels: down merge

#3021 QAT -> Staging Environment Promotion
  src/_scss/pages/analystGuide/analystGuide.scss
  src/js/GlobalConstants.js
  src/js/components/analystGuide/AnalystGuideIntro.jsx
  src/js/components/analystGuide/AnalystGuidePage.jsx
  src/js/components/analystGuide/AnalystGuideQuestions.jsx
Labels: ENV Promotion

#3022 Promote Staging to PROD
  package-lock.json
  package.json
  src/_scss/all.scss
  src/_scss/components/_card.scss
  src/_scss/core/_variables.scss
  src/_scss/elements/_accordion.scss
  src/_scss/elements/_buttons.scss
  src/_scss/pages/analystGuide/_analystGuideHeader.scss
  src/_scss/pages/analystGuide/analystGuide.scss
  src/_scss/pages/homepageUpdate/_homepageCovidSection.scss
  src/_scss/pages/homepageUpdate/hero/_hero.scss
  src/_scss/pages/homepageUpdate/homepageUpdate.scss
  src/img/analyst-guide-hero-graphic-2x.png
  src/img/homepage-covid-official-spending-data.svg
  src/img/homepage-hero-people-right.svg
  src/img/homepage-hero-person-left.svg
  src/js/GlobalConstants.js
  src/js/components/aboutTheData/TimeFilters.jsx
  src/js/components/agencyLanding/AgencyLandingContent.jsx
  src/js/components/analystGuide/AnalystGuideHeader.jsx
  src/js/components/analystGuide/AnalystGuideIntro.jsx
  src/js/components/analystGuide/AnalystGuidePage.jsx
  src/js/components/analystGuide/AnalystGuideQuestions.jsx
  src/js/components/covid19/recipient/map/MapFilters.jsx
  src/js/components/homepageUpdate/HomepageUpdate.jsx
  src/js/components/homepageUpdate/covid/Covid.jsx
  src/js/components/homepageUpdate/gettingStarted/GettingStarted.jsx
  src/js/components/homepageUpdate/hero/Hero.jsx
  src/js/components/sharedComponents/Card.jsx
  src/js/components/sharedComponents/accordion/Accordion.jsx
  src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
  src/js/containers/router/RouterRoutes.js
  src/js/dataMapping/navigation/menuOptions.jsx
  src/js/helpers/metaTagHelper.js
  src/js/helpers/recipientHelper.js
  src/js/helpers/stickyHeaderHelper.js
  src/js/registerIcons.js
  tests/components/analystGuide/AnalystGuide-test.jsx
  tests/components/sharedComponents/Accordion-test.jsx
  webpack/webpack.common.js
  webpack/webpack.dev.config.js
Labels: ENV Promotion

#3026 DEV-8669 analyst page params
  src/js/components/analystGuide/AnalystGuideQuestions.jsx
Labels: do not merge

#3038 8669 - Remove params from submission-statistics link (Env promotion)
  src/js/components/analystGuide/AnalystGuideQuestions.jsx
Labels: ENV Promotion

#3039 8669 - Remove params from submission-statistics link (Env Promotion)
  src/js/components/analystGuide/AnalystGuideQuestions.jsx
Labels: ENV Promotion
