Repository fedspendingtransparency/usaspending-website, pull requests merged in 2023-06, with the labels that each got.

#3646 promote QAT to Staging
  package-lock.json
  package.json
  src/_scss/layouts/default/header/nav/_megaMenu.scss
  src/_scss/pages/analystGuide/analystGuide.scss
  src/_scss/pages/search/results/_tabs.scss
  src/_scss/pages/search/searchPage.scss
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/agency/statusOfFunds/DrilldownSidebar.jsx
  src/js/components/agency/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agency/statusOfFunds/VisualizationSection.jsx
  src/js/components/agency/visualizations/StatusOfFundsChart.jsx
  src/js/components/agency/visualizations/StatusOfFundsTable.jsx
  src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx
  src/js/components/glossary/definition/GlossaryDefinition.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/search/modals/fullDownload/screens/DownloadScope.jsx
  src/js/components/search/table/ResultsTable.jsx
  src/js/components/sharedComponents/header/megaMenu/AnimatedNavbar.jsx
  src/js/components/sharedComponents/header/megaMenu/DropdownContainer.jsx
  src/js/components/sharedComponents/header/megaMenu/FadeContents.jsx
  src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx
  src/js/components/sharedComponents/header/megaMenu/MegaMenu.jsx
  src/js/components/sharedComponents/header/megaMenu/Navbar.jsx
  src/js/components/sharedComponents/header/megaMenu/NavbarItem.jsx
  src/js/components/trainingVideos/videoCard/VideoCard.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/dataMapping/search/awardTableColumnTypes.js
  src/js/dataMapping/search/awardTableColumns.jsx
  src/js/dataMapping/trainingVideos/playListMetadata.js
  src/js/helpers/agency/StatusOfFundsVizHelper.js
  src/js/helpers/metaTagHelper.js
  src/js/models/v2/agency/BaseAgencySubcomponentsList.js
  src/js/redux/actions/agency/agencyActions.js
  src/js/redux/reducers/agency/agencyReducer.js
Labels: ENV Promotion

#3649 Promote Staging to Master
  package-lock.json
  package.json
  src/_scss/layouts/default/header/nav/_megaMenu.scss
  src/_scss/pages/analystGuide/analystGuide.scss
  src/_scss/pages/search/results/_tabs.scss
  src/_scss/pages/search/searchPage.scss
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/agency/statusOfFunds/DrilldownSidebar.jsx
  src/js/components/agency/statusOfFunds/StatusOfFunds.jsx
  src/js/components/agency/statusOfFunds/VisualizationSection.jsx
  src/js/components/agency/visualizations/StatusOfFundsChart.jsx
  src/js/components/agency/visualizations/StatusOfFundsTable.jsx
  src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx
  src/js/components/glossary/definition/GlossaryDefinition.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/search/modals/fullDownload/screens/DownloadScope.jsx
  src/js/components/search/table/ResultsTable.jsx
  src/js/components/sharedComponents/header/megaMenu/AnimatedNavbar.jsx
  src/js/components/sharedComponents/header/megaMenu/DropdownContainer.jsx
  src/js/components/sharedComponents/header/megaMenu/FadeContents.jsx
  src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx
  src/js/components/sharedComponents/header/megaMenu/MegaMenu.jsx
  src/js/components/sharedComponents/header/megaMenu/Navbar.jsx
  src/js/components/sharedComponents/header/megaMenu/NavbarItem.jsx
  src/js/components/trainingVideos/videoCard/VideoCard.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/dataMapping/search/awardTableColumnTypes.js
  src/js/dataMapping/search/awardTableColumns.jsx
  src/js/dataMapping/trainingVideos/playListMetadata.js
  src/js/helpers/agency/StatusOfFundsVizHelper.js
  src/js/helpers/metaTagHelper.js
  src/js/models/v2/agency/BaseAgencySubcomponentsList.js
  src/js/redux/actions/agency/agencyActions.js
  src/js/redux/reducers/agency/agencyReducer.js
Labels: ENV Promotion

#3654 fixing 404 issue
  src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx
Labels: hotfix

#3655 master to staging
  src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx
Labels: down merge

#3656 Staging to qat downmerge
  src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx
Labels: down merge

#3670 HOTFIX fixed marshall islands bug
  src/js/components/search/filters/location/EntityDropdown.jsx
Labels: hotfix

#3673 9962 - new dtui version; fixed 404 errors on homepage
  package-lock.json
  package.json
  src/_scss/pages/homepageUpdate/_homepageResources.scss
  src/_scss/pages/homepageUpdate/_wordOfTheDay.scss
  src/js/components/homepageUpdate/HomepageResources/HomepageResources.jsx
  src/js/components/homepageUpdate/WordOfTheDay/ErrorWordOfTheDay.jsx
  src/js/components/homepageUpdate/WordOfTheDay/WordOfTheDay.jsx
Labels: hotfix

#3692 Promote QAT to Staging
  package-lock.json
  package.json
  scripts/buildRedirectConfig.js
  src/_scss/all.scss
  src/_scss/components/_footer.scss
  src/_scss/components/footer/_footerBig.scss
  src/_scss/components/footer/_footerMedium.scss
  src/_scss/components/footer/_footerPrimary.scss
  src/_scss/components/footer/_footerSecondary.scss
  src/_scss/components/footer/_footerSlim.scss
  src/_scss/components/footer/_footerSocial.scss
  src/_scss/layouts/default/footer/_stayInTouch.scss
  src/_scss/layouts/default/header/nav/_logo.scss
  src/_scss/layouts/default/header/nav/_megaMenu.scss
  src/_scss/layouts/default/header/nav/_mobileHamburger.scss
  src/_scss/layouts/default/header/nav/mobile/_animations.scss
  src/_scss/layouts/default/header/nav/mobile/_dropdown.scss
  src/_scss/layouts/default/header/nav/mobile/_nav.scss
  src/_scss/layouts/default/header/nav/mobile/_top.scss
  src/_scss/layouts/default/header/nav/mobile/mobileNav.scss
  src/_scss/pages/agency/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/explorer/detail/header/header.scss
  src/_scss/pages/testStyle/_codeBlock.scss
  src/_scss/pages/testStyle/testStyle.scss
  src/content/about-the-data/congressional-district-data.md
  src/img/caret.svg
  src/js/components/about/DataSources.jsx
  src/js/components/agency/visualizations/StatusOfFundsChart.jsx
  src/js/components/agency/visualizations/StatusOfFundsTable.jsx
  src/js/components/analystGuide/AnalystGuideIntro.jsx
  src/js/components/explorer/detail/ExplorerInfoTooltip.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/sharedComponents/StayInTouch.jsx
  src/js/components/sharedComponents/header/NavbarWrapper.jsx
  src/js/components/sharedComponents/header/megaMenu/DropdownContainer.jsx
  src/js/components/sharedComponents/header/megaMenu/NavbarItem.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdown.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdownItem.jsx
  src/js/components/sharedComponents/header/mobile/MobileNav.jsx
  src/js/components/sharedComponents/header/mobile/MobileTop.jsx
  src/js/components/testStyles/ButtonsExample.jsx
  src/js/components/testStyles/IconsExample.jsx
  src/js/components/testStyles/TestStyleIconItem.jsx
  src/js/components/testStyles/TestStylePage.jsx
  src/js/components/trainingVideos/listOfVideos/ListOfVideos.jsx
  src/js/containers/award/AwardContainer.jsx
  src/js/containers/explorer/detail/DetailContentContainer.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: ENV Promotion

#3693 Staging to Master
  package-lock.json
  package.json
  scripts/buildRedirectConfig.js
  src/_scss/all.scss
  src/_scss/components/_footer.scss
  src/_scss/components/footer/_footerBig.scss
  src/_scss/components/footer/_footerMedium.scss
  src/_scss/components/footer/_footerPrimary.scss
  src/_scss/components/footer/_footerSecondary.scss
  src/_scss/components/footer/_footerSlim.scss
  src/_scss/components/footer/_footerSocial.scss
  src/_scss/layouts/default/footer/_stayInTouch.scss
  src/_scss/layouts/default/header/nav/_logo.scss
  src/_scss/layouts/default/header/nav/_megaMenu.scss
  src/_scss/layouts/default/header/nav/_mobileHamburger.scss
  src/_scss/layouts/default/header/nav/mobile/_animations.scss
  src/_scss/layouts/default/header/nav/mobile/_dropdown.scss
  src/_scss/layouts/default/header/nav/mobile/_nav.scss
  src/_scss/layouts/default/header/nav/mobile/_top.scss
  src/_scss/layouts/default/header/nav/mobile/mobileNav.scss
  src/_scss/pages/agency/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/explorer/detail/header/header.scss
  src/_scss/pages/testStyle/_codeBlock.scss
  src/_scss/pages/testStyle/testStyle.scss
  src/content/about-the-data/congressional-district-data.md
  src/img/caret.svg
  src/js/components/about/DataSources.jsx
  src/js/components/agency/visualizations/StatusOfFundsChart.jsx
  src/js/components/agency/visualizations/StatusOfFundsTable.jsx
  src/js/components/analystGuide/AnalystGuideIntro.jsx
  src/js/components/explorer/detail/ExplorerInfoTooltip.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/sharedComponents/StayInTouch.jsx
  src/js/components/sharedComponents/header/NavbarWrapper.jsx
  src/js/components/sharedComponents/header/megaMenu/DropdownContainer.jsx
  src/js/components/sharedComponents/header/megaMenu/NavbarItem.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdown.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdownItem.jsx
  src/js/components/sharedComponents/header/mobile/MobileNav.jsx
  src/js/components/sharedComponents/header/mobile/MobileTop.jsx
  src/js/components/testStyles/ButtonsExample.jsx
  src/js/components/testStyles/IconsExample.jsx
  src/js/components/testStyles/TestStyleIconItem.jsx
  src/js/components/testStyles/TestStylePage.jsx
  src/js/components/trainingVideos/listOfVideos/ListOfVideos.jsx
  src/js/containers/award/AwardContainer.jsx
  src/js/containers/explorer/detail/DetailContentContainer.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: do not merge
