Repository fedspendingtransparency/usaspending-website, pull requests merged in 2023-04, with the labels that each got.

#3573 Downmerge staging to QAT
  src/_scss/components/_unlinkedAwardWarning.scss
  src/js/components/award/shared/InfoTooltipContent.jsx
  src/js/components/sharedComponents/UnlinkedAwardWarning.jsx
  src/js/helpers/awardAmountHelper.js
Labels: down merge

#3568 DEV-9630 fix learn more footer
  src/js/components/sharedComponents/StayInTouch.jsx
Labels: do not merge

#3572 DEV-9590 fixed menu not closing on blur
  src/js/components/search/visualizations/rank/RankVisualizationTitle.jsx
Labels: do not merge

#3561 DEV-9636 toggles weren't tabbable properly
  src/_scss/components/_roundedtoggle.scss
  src/js/components/search/visualizations/SubawardToggle.jsx
Labels: do not merge

#3585 Promote QAT to Staging
  src/_scss/components/_roundedtoggle.scss
  src/_scss/components/search/_keywordSearchLink.scss
  src/_scss/components/tooltips/_customTooltipContent.scss
  src/_scss/pages/award/visualizations/_additionalInfo.scss
  src/_scss/pages/bulkDownload/form/_locationFilter.scss
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/_scss/pages/glossary/_definition.scss
  src/_scss/pages/search/_pagePositioning.scss
  src/_scss/pages/search/filters/location/location.scss
  src/_scss/pages/search/results/_tabs.scss
  src/_scss/pages/search/results/visualizations/geo/_disclaimer.scss
  src/_scss/pages/search/results/visualizations/geo/geoVisualization.scss
  src/_scss/pages/search/results/visualizations/geo/map/_toggle.scss
  src/_scss/pages/search/results/visualizations/geo/map/map.scss
  src/_scss/pages/search/searchSidebar.scss
  src/_scss/pages/state/visualizations/geo/geoVisualization.scss
  src/js/components/aboutTheDataSidebar/AboutTheDataHeader.jsx
  src/js/components/award/shared/additionalInfo/Accordion.jsx
  src/js/components/covid19/Covid19Tooltips.jsx
  src/js/components/covid19/recipient/map/MapFilters.jsx
  src/js/components/covid19/recipient/map/MapFiltersHeader.jsx
  src/js/components/glossary/definition/GlossaryDefinition.jsx
  src/js/components/search/KeywordSearchLink.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/search/SearchSidebar.jsx
  src/js/components/search/filters/location/EntityDropdown.jsx
  src/js/components/search/filters/location/EntityDropdownAutocomplete.jsx
  src/js/components/search/filters/location/EntityDropdownList.jsx
  src/js/components/search/filters/timePeriod/TimePeriod.jsx
  src/js/components/search/visualizations/SubawardToggle.jsx
  src/js/components/search/visualizations/VisualizationTabItem.jsx
  src/js/components/search/visualizations/VisualizationWrapper.jsx
  src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
  src/js/components/search/visualizations/geo/MapLayerToggle.jsx
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/components/search/visualizations/rank/RankVisualizationTitle.jsx
  src/js/components/search/visualizations/rank/sections/SpendingByAgencySection.jsx
  src/js/components/search/visualizations/rank/sections/SpendingByCFDASection.jsx
  src/js/components/search/visualizations/rank/sections/SpendingByIndustryCodeSection.jsx
  src/js/components/search/visualizations/rank/sections/SpendingByRecipientSection.jsx
  src/js/components/search/visualizations/time/TimeVisualizationSection.jsx
  src/js/components/sharedComponents/AboutTheDataLink.jsx
  src/js/components/sharedComponents/ReadMore.jsx
  src/js/components/sharedComponents/StayInTouch.jsx
  src/js/components/state/overview/StateOverview.jsx
  src/js/components/state/visualizations/geo/GeoVisualizationSection.jsx
  src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
  src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
  src/js/containers/search/visualizations/time/TimeVisualizationSectionContainer.jsx
  src/js/containers/state/visualizations/geo/GeoVisualizationSectionContainer.jsx
  src/js/dataMapping/shared/mobileBreakpoints.js
  src/js/helpers/aboutTheDataSidebarHelper.js
  src/js/redux/actions/search/appliedFilterActions.js
Labels: ENV Promotion

#3593 Fix/9723 - Downmerge
  package-lock.json
  package.json
  src/js/components/search/visualizations/rank/RankVisualizationTitle.jsx
  src/js/components/search/visualizations/rank/sections/SpendingByAgencySection.jsx
  src/js/components/search/visualizations/rank/sections/SpendingByCFDASection.jsx
  src/js/components/search/visualizations/rank/sections/SpendingByIndustryCodeSection.jsx
  src/js/components/search/visualizations/rank/sections/SpendingByRecipientSection.jsx
  src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
  tests/containers/search/visualizations/rank/RankVisualizationWrapperContainer-test.jsx
Labels: down merge
