Repository fedspendingtransparency/usaspending-website, pull requests merged in 2023-11, with the labels that each got.

#3867 Promote QAT to Staging
  package-lock.json
  package.json
  src/_scss/components/aboutTheDataSidebar/_byPage.scss
  src/_scss/components/aboutTheDataSidebar/aboutTheData.scss
  src/_scss/layouts/default/stickyHeader/_inpagenav.scss
  src/_scss/pages/modals/video/_trainingVideoModal.scss
  src/_scss/pages/search/_filters.scss
  src/_scss/pages/search/filters/recipient/_recipientType.scss
  src/content/about-the-data/pages/agency.md
  src/content/about-the-data/pages/award.md
  src/content/about-the-data/pages/award_data_archive.md
  src/content/about-the-data/pages/covid-19.md
  src/content/about-the-data/pages/custom_account_data.md
  src/content/about-the-data/pages/custom_award_data.md
  src/content/about-the-data/pages/explorer.md
  src/content/about-the-data/pages/federal_account.md
  src/content/about-the-data/pages/keyword_search.md
  src/content/about-the-data/pages/recipient.md
  src/content/about-the-data/pages/search.md
  src/content/about-the-data/pages/state.md
  src/content/about-the-data/pages/submission-statistics.md
  src/js/components/aboutTheDataSidebar/AboutTheDataByPage.jsx
  src/js/components/agency/visualizations/StatusOfFundsChart.jsx
  src/js/components/inPageNav/InPageNav.jsx
  src/js/components/search/filters/recipient/RecipientType.jsx
  src/js/components/search/filters/recipient/RecipientTypeAccordion.jsx
  src/js/components/search/filters/recipient/RecipientTypeList.jsx
  src/js/components/sharedComponents/RoundedToggle.jsx
  src/js/components/sharedComponents/checkbox/PrimaryCheckboxType.jsx
  src/js/components/sharedComponents/checkbox/SecondaryCheckboxType.jsx
  src/js/components/sharedComponents/checkbox/SingleCheckboxType.jsx
  src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdownItem.jsx
  src/js/containers/search/filters/recipient/RecipientTypeContainer.jsx
  src/js/dataMapping/aboutTheDataSchema.js
  src/js/dataMapping/search/recipientType.js
Labels: ENV Promotion

#3872 Promote Staging to Master for PROD deploy
  package-lock.json
  package.json
  src/_scss/components/aboutTheDataSidebar/_byPage.scss
  src/_scss/components/aboutTheDataSidebar/aboutTheData.scss
  src/_scss/layouts/default/stickyHeader/_inpagenav.scss
  src/_scss/pages/modals/video/_trainingVideoModal.scss
  src/_scss/pages/search/_filters.scss
  src/_scss/pages/search/filters/recipient/_recipientType.scss
  src/content/about-the-data/pages/agency.md
  src/content/about-the-data/pages/award.md
  src/content/about-the-data/pages/award_data_archive.md
  src/content/about-the-data/pages/covid-19.md
  src/content/about-the-data/pages/custom_account_data.md
  src/content/about-the-data/pages/custom_award_data.md
  src/content/about-the-data/pages/explorer.md
  src/content/about-the-data/pages/federal_account.md
  src/content/about-the-data/pages/keyword_search.md
  src/content/about-the-data/pages/recipient.md
  src/content/about-the-data/pages/search.md
  src/content/about-the-data/pages/state.md
  src/content/about-the-data/pages/submission-statistics.md
  src/js/components/aboutTheDataSidebar/AboutTheDataByPage.jsx
  src/js/components/agency/visualizations/StatusOfFundsChart.jsx
  src/js/components/inPageNav/InPageNav.jsx
  src/js/components/search/filters/recipient/RecipientType.jsx
  src/js/components/search/filters/recipient/RecipientTypeAccordion.jsx
  src/js/components/search/filters/recipient/RecipientTypeList.jsx
  src/js/components/sharedComponents/RoundedToggle.jsx
  src/js/components/sharedComponents/checkbox/PrimaryCheckboxType.jsx
  src/js/components/sharedComponents/checkbox/SecondaryCheckboxType.jsx
  src/js/components/sharedComponents/checkbox/SingleCheckboxType.jsx
  src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx
  src/js/components/sharedComponents/header/mobile/MobileDropdownItem.jsx
  src/js/containers/search/filters/recipient/RecipientTypeContainer.jsx
  src/js/dataMapping/aboutTheDataSchema.js
  src/js/dataMapping/search/recipientType.js
Labels: ENV Promotion

#3874 HOTFIX - issues mentioned https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1700596326299819
  package-lock.json
  src/js/components/search/filters/recipient/RecipientTypeAccordion.jsx
  src/js/dataMapping/search/recipientType.js
Labels: hotfix

#3877 HOTFIX recipient type filters
  package-lock.json
  src/js/components/search/filters/recipient/RecipientTypeAccordion.jsx
  src/js/dataMapping/search/recipientType.js
Labels: hotfix

#3868 10367 - changed z-index for the map-layer-toggle; removed a console.log
  src/_scss/pages/search/results/visualizations/geo/map/_toggle.scss
  src/js/components/search/visualizations/geo/MapWrapper.jsx
Labels: do not merge
