Repository fedspendingtransparency/usaspending-website, pull requests merged in 2024-10, with the labels that each got.

#4304 DEV-11526 fixed issues caused by new FY
  package-lock.json
  src/js/components/state/StatePage.jsx
  src/js/components/state/topFive/TopFive.jsx
  src/js/components/stateLanding/table/StateLandingTable.jsx
  src/js/containers/state/StateContainer.jsx
Labels: hotfix

#4307 Promote 2 Hotfixes from Staging to Master for PROD deploy
  package-lock.json
  src/js/components/state/StatePage.jsx
  src/js/components/state/topFive/TopFive.jsx
  src/js/components/stateLanding/table/StateLandingTable.jsx
  src/js/containers/state/StateContainer.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: ENV Promotion

#4310 DEV-11535 remove leaving gov't site popup
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: hotfix

#4312 Promote staging to master for DEV-11535 hotfix
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: ENV Promotion

#4313 Staging downmerge and resolving conflict
  src/js/components/sharedComponents/TopFive.jsx
  src/js/components/state/StatePage.jsx
  src/js/components/stateLanding/table/StateLandingTable.jsx
  src/js/containers/state/StateContainer.jsx
  src/js/dataMapping/navigation/menuOptions.jsx
Labels: down merge

#4322 Promote Hotfix (DEV-11565) to PROD
  src/js/GlobalConstants.js
  src/js/components/sharedComponents/header/Header.jsx
Labels: ENV Promotion

#4324 downmerge hotfix banner
  src/js/GlobalConstants.js
  src/js/components/sharedComponents/header/Header.jsx
Labels: down merge

#4348 Downmerge
  src/js/GlobalConstants.js
Labels: down merge
