Repository fedspendingtransparency/usaspending-website, pull requests merged in 2024-04, with the labels that each got.

#4036 Promote Staging to master
  package-lock.json
  package.json
  src/_scss/components/_picker.scss
  src/_scss/components/_titleBarFilter.scss
  src/_scss/components/tempSearchPage/_tempSearchSectionWrapper.scss
  src/_scss/components/tooltips/_index.scss
  src/_scss/data-transparency-ui.css
  src/_scss/pages/covid19/recipient/recipientContainer.scss
  src/_scss/pages/search/_toggleTempSearchPage.scss
  src/_scss/pages/search/results/visualizations/geo/geoVisualization.scss
  src/_scss/pages/search/results/visualizations/geo/map/_legend.scss
  src/_scss/pages/search/results/visualizations/geo/map/map.scss
  src/_scss/pages/search/results/visualizations/time/timeVisualization.scss
  src/_scss/pages/search/searchPage.scss
  src/_scss/pages/trainingVideos/_featuredVideo.scss
  src/_scss/pages/trainingVideos/_listOfVideos.scss
  src/_scss/pages/trainingVideos/_trainingVideosHeading.scss
  src/js/components/search/SearchPage.jsx
  src/js/components/search/SearchSidebar.jsx
  src/js/components/search/filters/location/EntityDropdown.jsx
  src/js/components/search/filters/timePeriod/AllFiscalYears.jsx
  src/js/components/search/filters/timePeriod/TimePeriod.jsx
  src/js/components/search/visualizations/geo/AdvancedSearchMapFilters.jsx
  src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
  src/js/components/search/visualizations/geo/MapFiltersTitle.jsx
  src/js/components/search/visualizations/geo/MapLegend.jsx
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/components/search/visualizations/geo/map/MapBox.jsx
  src/js/components/search/visualizations/time/TimeVisualizationChart.jsx
  src/js/components/search/visualizations/time/TimeVisualizationSection.jsx
  src/js/components/sharedComponents/dropdowns/NewPicker.jsx
  src/js/components/tempPage.jsx
  src/js/components/tempSearchPage/TempPlaceholderComponent.jsx
  src/js/components/tempSearchPage/TempPlaceholderComponents.jsx
  src/js/components/tempSearchPage/TempSearchPage.jsx
  src/js/components/tempSearchPage/TempSearchSectionWrapper.jsx
  src/js/containers/account/filters/AccountTimePeriodContainer.jsx
  src/js/dataMapping/covid19/recipient/map/map.js
Labels: ENV Promotion

#4042 downmerge banner removal
  src/_scss/layouts/default/header/_warning.scss
  src/js/components/search/SearchPage.jsx
Labels: down merge

#4061 Promote QAT to Staging
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/containers/search/SearchSidebarSubmitContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
Labels: ENV Promotion

#4063 fix null checks for download
  src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
Labels: hotfix
