Repository fedspendingtransparency/usaspending-website, pull requests merged in 2024-06, with the labels that each got.

#4108 Staging to qat downmerge
  src/_scss/pages/keyword/keywordPage.scss
  src/_scss/pages/search/results/visualizations/time/timeVisualization.scss
  src/_scss/pages/search/resultsView/_resultsView.scss
Labels: down merge

#4114 Staging to qat downmerge
  package-lock.json
  src/_scss/pages/account/results/table/awardTable.scss
  src/js/components/account/SearchResults.jsx
  src/js/containers/account/awards/AccountAwardsContainer.jsx
Labels: down merge

#4113 Promote hotfix to master
  package-lock.json
  src/_scss/pages/account/results/table/awardTable.scss
  src/js/components/account/SearchResults.jsx
  src/js/containers/account/awards/AccountAwardsContainer.jsx
Labels: ENV Promotion

#4138 Promote QAT to Staging
  package-lock.json
  package.json
  src/_scss/components/_titleBarFilter.scss
  src/_scss/components/cards/_cards.scss
  src/_scss/elements/_table.scss
  src/_scss/pages/about/_contentWrap.scss
  src/_scss/pages/agency/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/homepageUpdate/_featuredContent.scss
  src/_scss/pages/search/results/_tabs.scss
  src/_scss/pages/search/results/searchResults.scss
  src/_scss/pages/search/results/table/resultsTable.scss
  src/_scss/pages/search/results/visualizations/geo/map/map.scss
  src/_scss/pages/search/resultsView/_resultsView.scss
  src/_scss/pages/search/searchPage.scss
  src/img/homepage-featured-content/homepage-feature-FDG@2x.webp
  src/img/homepage-featured-content/homepage-feature-Your-Data-Your-Story@2x.webp
  src/img/homepage-featured-content/homepage-feature-covid-19.webp
  src/img/homepage-featured-content/homepage-featured-youtube.webp
  src/img/map/zoom-in.svg
  src/img/map/zoom-out.svg
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/components/homepageUpdate/AwardSearch/AwardSearch.jsx
  src/js/components/homepageUpdate/FeaturedContent/FeaturedContent.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/search/SearchSidebar.jsx
  src/js/components/search/newResultsView/DsmWrapper.jsx
  src/js/components/search/newResultsView/NewSearchScreen.jsx
  src/js/components/search/newResultsView/PlaceholderComponent.jsx
  src/js/components/search/newResultsView/ResultsView.jsx
  src/js/components/search/newResultsView/SearchSectionWrapper.jsx
  src/js/components/search/newResultsView/SectionsContent.jsx
  src/js/components/search/newResultsView/categories/CategoriesDsm.jsx
  src/js/components/search/newResultsView/categories/CategoriesSection.jsx
  src/js/components/search/newResultsView/fetchAwardTableCount.js
  src/js/components/search/newResultsView/fetchAwardsTableData.js
  src/js/components/search/newResultsView/fetchSpendingByGeographyData.js
  src/js/components/search/newResultsView/map/MapDsm.jsx
  src/js/components/search/newResultsView/map/MapSection.jsx
  src/js/components/search/newResultsView/table/TableDsm.jsx
  src/js/components/search/newResultsView/table/TableSection.jsx
  src/js/components/search/newResultsView/time/TimeDsm.jsx
  src/js/components/search/newResultsView/time/TimeFileDownload.jsx
  src/js/components/search/newResultsView/time/TimeSection.jsx
  src/js/components/search/table/ResultsTable.jsx
  src/js/components/search/visualizations/VisualizationWrapper.jsx
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/components/search/visualizations/geo/map/MapBox.jsx
  src/js/containers/search/newResultsView/CategoriesVisualizationWrapperContainer.jsx
  src/js/containers/search/newResultsView/MapSectionWrapper.jsx
  src/js/containers/search/newResultsView/ResultsTableContainer.jsx
  src/js/containers/search/newResultsView/TimeVisualizationSectionContainer.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
  src/js/dataMapping/search/awardTableColumns.jsx
  src/js/helpers/aboutTheDataSidebarHelper.jsx
  src/js/models/v2/search/visualizations/time/BaseSpendingOverTimeRow.js
Labels: ENV Promotion

#4143 11092 - Hotfix sub stats table
  src/_scss/pages/aboutTheData/_agenciesPage.scss
  src/_scss/pages/aboutTheData/_agencyDetailsPage.scss
  src/_scss/pages/agency/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/covid19/_tables.scss
  src/_scss/pages/covid19/_unlinkedData.scss
  src/_scss/pages/covid19/recipient/_spendingByRecipient.scss
  src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
Labels: hotfix

#4146 Staging to qat downmerge
  src/_scss/pages/aboutTheData/_agenciesPage.scss
  src/_scss/pages/aboutTheData/_agencyDetailsPage.scss
  src/_scss/pages/agency/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/agency/statusOfFunds/_visualizationSection.scss
  src/_scss/pages/covid19/_tables.scss
  src/_scss/pages/covid19/_unlinkedData.scss
  src/_scss/pages/covid19/recipient/_spendingByRecipient.scss
  src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
  src/_scss/pages/search/results/searchResults.scss
  src/_scss/pages/search/resultsView/_resultsView.scss
  src/js/components/search/newResultsView/ResultsView.jsx
  src/js/components/search/newResultsView/SectionDataTable.jsx
  src/js/components/search/newResultsView/categories/CategoriesTable.jsx
  src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
Labels: down merge

#4156 Promote staging to master for hotfix
  src/_scss/pages/agency/statusOfFunds/_dtuiOverrides.scss
  src/_scss/pages/agency/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/search/results/searchResults.scss
  src/_scss/pages/search/resultsView/_dtuiOverrides.scss
  src/_scss/pages/search/searchPage.scss
  src/js/components/search/newResultsView/SearchSectionWrapper.jsx
  src/js/components/search/newResultsView/SectionDataTable.jsx
  src/js/components/search/newResultsView/categories/CategoriesTable.jsx
  src/js/components/search/newResultsView/table/ResultsTableSection.jsx
  src/js/components/search/table/ResultsTable.jsx
Labels: ENV Promotion
