Repository fedspendingtransparency/usaspending-website, pull requests merged in 2024-02, with the labels that each got.

#3964 HOTFIX trailing slash issue
  src/js/helpers/searchHelper.js
Labels: do not merge, hotfix

#3965 HOTFIX trailing slash issue
  src/js/helpers/searchHelper.js
Labels: hotfix

#3966 Staging to qat down merge
  package-lock.json
  src/js/components/search/SearchPage.jsx
  src/js/helpers/searchHelper.js
Labels: down merge

#3981 Promote QAT to Staging
  package-lock.json
  package.json
  src/_scss/all.scss
  src/_scss/components/_titleBarFilter.scss
  src/_scss/core/_base.scss
  src/_scss/layouts/default/stickyHeader/header.scss
  src/_scss/pages/agency/index.scss
  src/_scss/pages/agency/overview/_pageTitle.scss
  src/_scss/pages/bulkDownload/bulkDownloadPage.scss
  src/_scss/pages/bulkDownload/downloadData.scss
  src/_scss/pages/bulkDownload/form/_downloadButtons.scss
  src/_scss/pages/bulkDownload/form/downloadForm.scss
  src/_scss/pages/bulkDownload/sidebar/sidebar.scss
  src/_scss/pages/interactiveDataSources/index.scss
  src/_scss/pages/search/searchPage.scss
  src/js/components/about/navTest/About.jsx
  src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
  src/js/components/aboutTheDataSidebar/AboutTheData.jsx
  src/js/components/agency/AgencyPage.jsx
  src/js/components/agency/overview/PageTitle.jsx
  src/js/components/analystGuide/AnalystGuideQuestions.jsx
  src/js/components/award/Award.jsx
  src/js/components/bulkDownload/BulkDownloadPage.jsx
  src/js/components/bulkDownload/accounts/filters/AgencyFilter.jsx
  src/js/components/bulkDownload/accounts/filters/BudgetFunctionFilter.jsx
  src/js/components/bulkDownload/sidebar/BulkDownloadSidebar.jsx
  src/js/components/bulkDownload/sidebar/SidebarButton.jsx
  src/js/components/search/filters/timePeriod/TimePeriod.jsx
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/components/search/visualizations/geo/map/MapBox.jsx
  src/js/components/sharedComponents/DownloadStaticFile.jsx
  src/js/components/sharedComponents/dropdowns/NewPicker.jsx
  src/js/components/sharedComponents/dropdowns/NumericPickerWrapper.jsx
  src/js/components/sharedComponents/header/Header.jsx
  src/js/containers/search/filters/TimePeriodContainer.jsx
  src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
  src/js/helpers/covid19Helper.js
  src/js/helpers/scrollToHelper.js
  src/js/redux/actions/search/searchFilterActions.js
  src/js/redux/reducers/search/searchFiltersReducer.js
  tests/containers/search/SearchContainer-test.jsx
  tests/containers/search/visualizations/geo/GeoVisualizationSectionContainer-test.jsx
  tests/containers/search/visualizations/geo/mocks/geoHelper.js
  tests/redux/reducers/search/searchFiltersReducer-test.js
Labels: ENV Promotion

#3989 Down merge
  src/js/components/search/visualizations/geo/map/MapBox.jsx
Labels: down merge

#3990 1234 - changed nao var in one place that was forgotten before, causin…
  src/js/models/v1/search/SearchAwardsOperation.js
Labels: hotfix

#3991 Promote staging to master for PROD deploy - Hotfix 10684
  src/js/models/v1/search/SearchAwardsOperation.js
Labels: ENV Promotion
