Repository fedspendingtransparency/usaspending-website, pull requests merged in 2024-01, with the labels that each got.

#3920 10501 - small fix for glossary scrollbar bug
  src/js/components/glossary/Glossary.jsx
Labels: do not merge

#3928 Promote QAT from Staging
  package-lock.json
  src/_scss/layouts/default/header/nav/mobile/_animations.scss
  src/_scss/pages/covid19/recipient/_spendingByRecipient.scss
  src/js/components/covid19/recipient/map/MapWrapper.jsx
  src/js/components/search/table/ResultsTableSection.jsx
  src/js/components/search/visualizations/geo/map/MapBox.jsx
  src/js/components/sharedComponents/header/NavbarWrapper.jsx
  src/js/components/sharedComponents/header/mobile/MobileNav.jsx
  src/js/containers/search/table/ResultsTableContainer.jsx
Labels: ENV Promotion

#3936 Staging to qat
  package-lock.json
  package.json
Labels: down merge

#3947 10569 - Hotfix: Advanced search - Fixed issue where new table rows are not returned after scrolling to the bottom of the table
  src/js/containers/search/table/ResultsTableContainer.jsx
Labels: hotfix

#3953 Promote hotfix (DEV-10569) to master
  src/js/containers/search/table/ResultsTableContainer.jsx
Labels: ENV Promotion

#3952 Hotfix downmerge
  src/js/containers/search/table/ResultsTableContainer.jsx
Labels: down merge
