Repository fedspendingtransparency/usaspending-website, pull requests merged in 2024-09, with the labels that each got.

#4254 11430 - Promote hotfix to PROD
  package-lock.json
  src/js/components/search/table/ResultsTable.jsx
Labels: ENV Promotion

#4255 11277: Added the awarding agency and assistance listings autocomplete filters to the state profile map
  src/_scss/pages/state/statePage.scss
  src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
  src/js/components/state/visualizations/geo/GeoVisualizationSection.jsx
  src/js/components/state/visualizations/geo/MapWrapper.jsx
  src/js/components/state/visualizations/geo/StateProfileMapFilters.jsx
  src/js/components/state/visualizations/geo/agency/StateAgencyList.jsx
  src/js/components/state/visualizations/geo/cfda/StateCFDAList.jsx
  src/js/containers/state/visualizations/geo/GeoVisualizationSectionContainer.jsx
  src/js/dataMapping/state/stateMap.js
Labels: do not merge, pending design review

#4272 Sprint 191: Promote QAT to Staging
  package-lock.json
  package.json
  src/_scss/elements/filters/_typeahead.scss
  src/_scss/pages/search/filters/timePeriod/timePeriod.scss
  src/_scss/pages/search/filters/timePeriod/timePeriodNew.scss
  src/_scss/pages/state/overview/_overview.scss
  src/_scss/pages/state/statePage.scss
  src/_scss/pages/state/topFive/_table.scss
  src/_scss/pages/state/visualizations/awardBreakdown/awardBreakdownVisualization.scss
  src/_scss/pages/state/visualizations/geo/geoVisualization.scss
  src/img/state-categories/defc.png
  src/js/components/about/navTest/About.jsx
  src/js/components/about/navTest/AboutContent.jsx
  src/js/components/search/SearchPage.jsx
  src/js/components/search/filters/timePeriod/DateRange.jsx
  src/js/components/search/filters/timePeriod/DateRangeError.jsx
  src/js/components/search/filters/timePeriod/FiscalYear.jsx
  src/js/components/search/filters/timePeriod/TimePeriod.jsx
  src/js/components/search/newResultsView/SearchSectionWrapper.jsx
  src/js/components/sharedComponents/DatePicker.jsx
  src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
  src/js/components/sharedComponents/dropdowns/NewPicker.jsx
  src/js/components/sharedComponents/filterSidebar/FilterTab.jsx
  src/js/components/sharedComponents/filterSidebar/FilterTabs.jsx
  src/js/components/sharedComponents/timeChart/chart/BarChartLegend.jsx
  src/js/components/state/overview/StateOverview.jsx
  src/js/components/state/overview/SummaryStats.jsx
  src/js/components/state/spendingovertime/StateTimeVisualization.jsx
  src/js/components/state/topFive/TopFive.jsx
  src/js/components/state/topFive/TopFiveSection.jsx
  src/js/components/state/visualizations/awardBreakdown/AwardBreakdownTable.jsx
  src/js/components/state/visualizations/awardBreakdown/AwardBreakdownTreeMap.jsx
  src/js/components/state/visualizations/awardBreakdown/AwardTypeTooltip.jsx
  src/js/components/state/visualizations/geo/GeoVisualizationSection.jsx
  src/js/components/state/visualizations/geo/MapWrapper.jsx
  src/js/components/state/visualizations/geo/StateProfileMapFilters.jsx
  src/js/components/state/visualizations/geo/agency/StateAgencyList.jsx
  src/js/components/state/visualizations/geo/cfda/StateCFDAList.jsx
  src/js/components/state/visualizations/geo/programActivity/ProgramActivityList.jsx
  src/js/containers/router/RouterRoutes.jsx
  src/js/containers/state/topFive/TopFiveContainer.jsx
  src/js/containers/state/visualizations/awardBreakdown/AwardBreakdownContainer.jsx
  src/js/containers/state/visualizations/geo/GeoVisualizationSectionContainer.jsx
  src/js/dataMapping/state/stateMap.js
  src/js/dataMapping/state/topCategories.js
  src/js/helpers/searchHelper.js
  src/js/models/v2/state/BaseStateCategoryResult.jsx
  src/js/models/v2/state/BaseStateProfile.js
Labels: ENV Promotion

#4288 staging to qat downmerge
  src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
  src/js/containers/state/visualizations/geo/GeoVisualizationSectionContainer.jsx
Labels: down merge

#4291 11490 - Promote hotfix to master for PROD deploy
  src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
  src/js/containers/state/visualizations/geo/GeoVisualizationSectionContainer.jsx
Labels: ENV Promotion
