Repository fedspendingtransparency/usaspending-website, pull requests merged in 2024-07, with the labels that each got.

#4157 Downmerge Staging to QAT
  src/_scss/pages/agency/statusOfFunds/_dtuiOverrides.scss
  src/_scss/pages/agency/statusOfFunds/_statusOfFunds.scss
  src/_scss/pages/search/results/searchResults.scss
  src/_scss/pages/search/resultsView/_dtuiOverrides.scss
  src/_scss/pages/search/searchPage.scss
  src/js/components/search/newResultsView/SearchSectionWrapper.jsx
  src/js/components/search/newResultsView/SectionDataTable.jsx
  src/js/components/search/newResultsView/categories/CategoriesTable.jsx
  src/js/components/search/newResultsView/table/ResultsTableSection.jsx
  src/js/components/search/table/ResultsTable.jsx
Labels: ENV Promotion

#4160 DEV-11163 duplicate downloads
  package-lock.json
  src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx
Labels: hotfix

#4163 11163 - Promote hotfix for the duplicate downloads
  package-lock.json
  src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx
Labels: ENV Promotion

#4171 Mod/11131 changes for new stacked view
  package-lock.json
  package.json
  src/_scss/pages/search/resultsView/_dtuiOverrides.scss
  src/js/components/search/table/ResultsTable.jsx
Labels: do not merge, PR dependent

#4173 Fixing package-lock in QAT to prepare prompting to Staging
  package-lock.json
  src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx
Labels: ENV Promotion

#4175 11194 - fix for table borders on agency page, award spending section
  src/_scss/pages/agency/dtuiOverrides.scss
  src/_scss/pages/agency/index.scss
  src/_scss/pages/agency/statusOfFunds/_dtuiOverrides.scss
Labels: hotfix

#4190 hotfix - added css to make table row hover work correctly
  src/_scss/elements/_table.scss
Labels: hotfix
