Repository fedspendingtransparency/usaspending-website, pull requests merged in 2025-02, with the labels that each got.

#4481 DEV-12037 Hotfix/banner recipient
  package-lock.json
  package.json
  src/js/GlobalConstants.js
  src/js/components/sharedComponents/header/Header.jsx
Labels: hotfix

#4485 Hotfix DEV-12037: Promote staging to master
  package-lock.json
  package.json
  src/js/GlobalConstants.js
  src/js/components/sharedComponents/header/Header.jsx
Labels: ENV Promotion

#4486 Downmerge staging to qat and resolving merge conflict
  package-lock.json
  package.json
  src/js/GlobalConstants.js
  src/js/components/sharedComponents/header/Header.jsx
Labels: down merge

#4490 Sprint 198: Promote additional fixes to Staging
  package-lock.json
  package.json
  src/_scss/pages/search/_collapsibleSidebar.scss
  src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx
  src/js/components/sharedComponents/checkbox/AccordionCheckbox.jsx
  src/js/components/sharedComponents/checkbox/ListCheckbox.jsx
  src/js/containers/search/filters/recipient/RecipientSearchContainer.jsx
Labels: ENV Promotion

#4499 HOTFIX - DEV12098 remove Recipient Filter banner
  package-lock.json
  src/js/GlobalConstants.js
Labels: hotfix

#4500 HOTFIX - DEV12098 remove Recipient Filter banner
  package-lock.json
  src/js/GlobalConstants.js
Labels: hotfix

#4512 Staging qat conflict
  package-lock.json
  src/js/components/search/visualizations/geo/map/MapBox.jsx
Labels: do not merge, down merge

#4513 Staging to prod for gulf of america hotfix
  package-lock.json
  src/js/components/search/visualizations/geo/map/MapBox.jsx
Labels: hotfix
