Repository fedspendingtransparency/usaspending-website, pull requests merged in 2025-05, with the labels that each got.

#4672 Downmerge staging to qat
  src/js/GlobalConstants.js
  src/js/containers/account/AccountContainer.jsx
  src/js/containers/search/newResultsView/CategoriesVisualizationWrapperContainer.jsx
  src/js/containers/search/newResultsView/MapSectionWrapper.jsx
  src/js/containers/search/newResultsView/TimeVisualizationSectionContainer.jsx
  src/js/dataMapping/search/awardTableColumns.jsx
Labels: down merge

#4678 DEV-12443 usas mobile table updates
  package-lock.json
  package.json
  src/js/components/agency/visualizations/StatusOfFundsTable.jsx
  src/js/components/search/newResultsView/SectionDataTable.jsx
  src/js/components/search/newResultsView/categories/CategoriesTable.jsx
  src/js/components/search/newResultsView/table/ResultsTableSection.jsx
  src/js/components/search/table/ResultsTable.jsx
Labels: PR dependent

#4695 Fix/keyword search broken
  src/js/containers/keyword/KeywordContainer.jsx
Labels: hotfix

#4699 12728: Fixed issue with loading the recipient profile page without the fy param in the url
  src/js/containers/recipient/RecipientContainer.jsx
Labels: hotfix

#4700 Staging to master for hotfixes
  package-lock.json
  src/js/containers/keyword/KeywordContainer.jsx
  src/js/containers/recipient/RecipientContainer.jsx
Labels: hotfix
