Repository fedspendingtransparency/usaspending-website, pull requests merged in 2025-06, with the labels that each got.

#4710 Fix/dev 12743 psc naics hotfix
  package-lock.json
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
Labels: hotfix

#4714 Downmerge staging to qat
  package-lock.json
  src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
  src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
Labels: down merge

#4728 DEV-12818 - fixed start date for custom award data bulk download
  src/js/components/bulkDownload/awards/filters/dateRange/DownloadDateRange.jsx
  src/js/components/search/filters/timePeriod/DateRange.jsx
  src/js/components/sharedComponents/DatePicker.jsx
Labels: hotfix

#4731 HOTFIX - fixed start date for custom award data bulk download
  src/js/components/bulkDownload/awards/filters/dateRange/DownloadDateRange.jsx
  src/js/components/search/filters/timePeriod/DateRange.jsx
  src/js/components/sharedComponents/DatePicker.jsx
Labels: hotfix, ENV Promotion
