Repository fedspendingtransparency/usaspending-website, pull requests merged in 2025-01, with the labels that each got.

#4456 Promote Staging -> Master for Hotfix
  package-lock.json
  src/graphics/agency/SCRC.png
Labels: do not merge, hotfix

#4458 11865 - Fixed sidebar overlaps
  src/_scss/pages/search/_collapsibleSidebar.scss
  src/js/components/search/collapsibleSidebar/CategoryFilter.jsx
  src/js/components/search/collapsibleSidebar/CateogriesList.jsx
  src/js/components/search/collapsibleSidebar/CollapsibleSidebar.jsx
  src/js/components/search/collapsibleSidebar/SearchPagev2.jsx
  src/js/components/search/collapsibleSidebar/SearchSidebarDrilldown.jsx
  src/js/components/search/collapsibleSidebar/SearchSidebarMainMenu.jsx
  src/js/components/search/collapsibleSidebar/SidebarContent.jsx
  src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx
  src/js/components/search/mobile/MobileFiltersV2.jsx
  src/js/helpers/search/collapsiblesidebarHelper.js
Labels: do not merge, pending design review

#4460 Sprint 197: Promote QAT to Staging
  src/_scss/pages/search/_collapsibleSidebar.scss
  src/_scss/pages/search/_searchv2.scss
  src/_scss/pages/search/filters/recipient/recipient.scss
  src/_scss/pages/search/mobile/mobileFilterButton.scss
  src/_scss/pages/search/mobile/mobileSidebar.scss
  src/_scss/pages/search/searchPage.scss
  src/content/search/dummy_data.md
  src/img/Add-search-filters-icon.svg
  src/img/homepage-featured-content/homepage-feature-API-Feedback-Survey@2x.webp
  src/js/components/award/shared/additionalInfo/AdditionalInfo.jsx
  src/js/components/homepageUpdate/FeaturedContent/FeaturedContent.jsx
  src/js/components/search/SearchSidebarSubmit.jsx
  src/js/components/search/collapsibleSidebar/CategoryFilter.jsx
  src/js/components/search/collapsibleSidebar/CateogriesList.jsx
  src/js/components/search/collapsibleSidebar/CollapsibleSidebar.jsx
  src/js/components/search/collapsibleSidebar/DsmSlider.jsx
  src/js/components/search/collapsibleSidebar/SearchPagev2.jsx
  src/js/components/search/collapsibleSidebar/SearchSidebarDrilldown.jsx
  src/js/components/search/collapsibleSidebar/SearchSidebarMainMenu.jsx
  src/js/components/search/collapsibleSidebar/SidebarContent.jsx
  src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx
  src/js/components/search/filters/awardType/ContractAwardType.jsx
  src/js/components/search/filters/awardType/FinancialAssistanceAwardType.jsx
  src/js/components/search/filters/recipient/RecipientName.jsx
  src/js/components/search/filters/recipient/RecipientResultsContainer.jsx
  src/js/components/search/filters/recipient/RecipientSearch.jsx
  src/js/components/search/filters/timePeriod/TimePeriod.jsx
  src/js/components/search/mobile/MobileFiltersV2.jsx
  src/js/components/search/newResultsView/ResultsView.jsx
  src/js/components/search/visualizations/geo/MapWrapper.jsx
  src/js/components/search/visualizations/geo/map/MapBox.jsx
  src/js/components/sharedComponents/checkbox/AccordionCheckbox.jsx
  src/js/components/sharedComponents/checkbox/AccordionCheckboxSecondary.jsx
  src/js/components/sharedComponents/checkbox/SingleCheckboxType.jsx
  src/js/containers/search/SearchSidebarSubmitContainer.jsx
  src/js/containers/search/filters/AwardTypeContainerV2.jsx
  src/js/containers/search/filters/TimePeriodContainer.jsx
  src/js/containers/search/filters/def/DEFCheckboxTree.jsx
  src/js/containers/search/filters/def/DEFCheckboxTreeContainer.jsx
  src/js/containers/search/filters/recipient/RecipientNameDUNSContainer.jsx
  src/js/containers/search/filters/recipient/RecipientSearchContainer.jsx
  src/js/dataMapping/search/searchFilterCategories.jsx
  src/js/helpers/search/collapsiblesidebarHelper.js
  src/js/helpers/search/filterCheckboxHelper.js
  src/js/helpers/searchHelper.js
  src/js/models/v2/award/BaseFinancialAssistance.js
  src/js/models/v2/award/CorePreAwardDetails.js
  src/js/redux/actions/search/searchFilterActions.js
  src/js/redux/reducers/search/searchFiltersReducer.js
  src/js/registerIcons.js
  tests/containers/search/SearchContainer-test.jsx
  tests/containers/search/mockSearchHashes.js
  tests/helpers/filterCheckboxHelper-test.js
  tests/helpers/searchHelper-test.js
  tests/redux/reducers/search/searchFiltersReducer-test.js
Labels: ENV Promotion
